### ISSUE TITLE
[Bug] I18n isn't working properly since no method to set language.

### ISSUE THREAD

**Issue by wzy9607** [tfedor/AugmentedSteam#102]
As for the old Enhanced Steam, extension's language is automatically set to the language used on Steam pages (see https://github.com/jshackles/Enhanced_Steam/blob/270c5373b2dedd86935bda9853bc067cfdf7b369/enhancedsteam.js#L15-L27).

However, the new extension doesn't automatically set language. And there aren't a language option in options page ether. As a result, it seems that currently the only way to change extension's language is use Chrome console to exec `SyncedStorage.set("language")`.

**Comment by MxtOUT** [comment]
See #84
