### ISSUE TITLE
[BUG] "Set as Background" in Inventory no longer works

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#1021]
### Actual Behavior
As title. I think this was broken along with the update to profile edit options last summer.

### Desired Behavior
The new API endpoints are:
`https://api.steampowered.com/IPlayerService/SetEquippedProfileItemFlags/v1?access_token=`
`https://api.steampowered.com/IPlayerService/SetProfileBackground/v1?access_token=`

`webapi_token` can be retrieved from the page, but looks like the input needs to be encoded.

**Comment by MxtOUT** [comment]
Yes, you can either encode the input with [Protocol Buffers](https://developers.google.com/protocol-buffers) or as a plain JSON.
The body of the POST request to the `SetProfileBackground` should contain the stringified version of `{"communityitemid": id}`.

You could do this without fetching the expensive profile edit page via https://api.steampowered.com/IPlayerService/GetProfileItemsOwned/v1, only problem is the non-existence of the `webapi_token` on your inventory page

**Comment by candela97** [comment]
> only problem is the non-existence of the `webapi_token` on your inventory page

Yeah, it'll have to be fetched from the profile. Should be ok since it only has to be fetched once when the user clicks on a background item.

Or maybe fetch it in the background during login? That way it can be used in other features that require these API calls in the future, but then it'll need to be updated periodically.
