### ISSUE TITLE
[BUG]When using AugmentedSteam unpacked, I have to reload it after each restart of Chromium

### ISSUE THREAD

**Issue by zacjor** [tfedor/AugmentedSteam#1022]
### Expected Behavior
Augmented Steam should remain loaded in between Chromium restarts. I'm not having this issue with any other extension I load unpacked.

### Actual Behavior
Augmented Steam is missing from the extension list and has to be reloaded after restarts.

### Steps to Reproduce the Problem

  1. Load Augmented Steam
  2. Restart Chromium

### Specifications

  - Augmented Steam Version: 2.0.0
  - Browser Version : 87.0.4280.141

Edit: I'm on Arch Linux and I keep my unpacked extensions in /usr/share. Augmented Steam will load after each Chromium restart if I have it loaded from my user directory. I thought maybe there was an ownership issue, but nothing looks off.

**Comment by MxtOUT** [comment]
I had this problem too, removing the "key" field from the manifest should solve it.

https://discord.com/channels/301903094080339968/540532923657617415/699397116316876840
