### ISSUE TITLE
[BUG] "Add a note" (probably solved)

### ISSUE THREAD

**Issue by markwr** [tfedor/AugmentedSteam#1024]
I have just now solved the problem as I was about to post the BUG here. However I will still post to give you my solution, because other people mentioned similar problems here. I was having the problem in Firefox, but not Chrome. I compared the "Augmented Steam Options" pages between the two  browsers, thinking I would try to make Options settings on Firefox match Chrome. Then I noticed the "Reset" button at the bottom of your Options page, and I decided to try that first (in the Firefox browser). Now the problem in Firefox is gone. So, some option (I'm sorry, I don't know which), when set to a non-Default value, had likely caused the problem. I hope this is enough of a clue for you to experiment and find the bug.

### Expected Behavior
At Steam Store page for a game:
Click "Add a note"
Type short text
Click [Save] (or hit Enter key)
You see the note.
When you return to that Steam Store page later, you still see the note.

### Actual Behavior
Everything still works, except for the last part. That is, you can add a note, and it shows after you add it. BUT, if you return to that page later, the note is gone. In fact, after creating the note, simply reload the page, and it is gone. I loaded a Store page for a different game that I had added a note to in the past, and that note is still there.

### Steps to Reproduce the Problem

1. At Steam Store page for a game:
2. Click "Add a note"
3. Type short text
4. Click [Save] (or hit Enter key)
5 .You see the note.
6 .When you reload the page, or return to that Steam Store page later, you DO NOT see the note.

### Specifications

  - Augmented Steam Version: 1.4.8
  - Browser Version : Firefox 84.0.2 (64-bit)

**Comment by MxtOUT** [comment]
Does this also happen after resetting the notes?
