### ISSUE TITLE
[BUG] Incorrect Games/Similar Names

### ISSUE THREAD

**Issue by StrongStyleShiny** [tfedor/AugmentedSteam#1025]
### Expected Behavior
The game Chasm should be showing the lowest price and a link to the source.

### Actual Behavior
On the game Chasm it's pulling up links and data to an unrelated title with Chasm in the name.

### Steps to Reproduce the Problem

  1. Go to Chasm
  2. Look at the price
  3. Click link next to price.

**Comment by MxtOUT** [comment]
This is an IsThereAnyDeal problem, please report it there
