### ISSUE TITLE
[FEATURE REQUEST] Display "All Reviews" as a percentage

### ISSUE THREAD

**Issue by Korb** [tfedor/AugmentedSteam#1028]
### Current Behavior (if any)
Displays the text "Overwhelmingly Negative", "Mostly Negative", "Mixed", etc.

### Desired Behavior
[1-100] %

### Motivation / Use Case for Changing the Behavior
Comparison with the "SteamDB Rating" displayed as a percentage.

**Comment by candela97** [comment]
Same idea as #900?

**Comment by MxtOUT** [comment]
> Same idea as #900?

Yes
