### ISSUE TITLE
[BUG] Wrong link in assassin's creed black flag steam page

### ISSUE THREAD

**Issue by pitprok** [tfedor/AugmentedSteam#1029]
### Expected Behavior
Links should lead to https://isthereanydeal.com/game/assassinscreedivblackflag

### Actual Behavior
Links lead to https://isthereanydeal.com/game/assassinscreedliberationhd

### Steps to Reproduce the Problem

  1. Go to black flag steam page
  2. Check the Current best etc links
  3. 

### Specifications

  - Augmented Steam Version: 1.4.7
  - Browser Version : Google Chrome Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by Revadike** [comment]
This should be reported to IsThereAnyDeal, not to Augmented Steam.
