### ISSUE TITLE
[FEATURE REQUEST] Missing "move to last page" on inventory after update 2.0

### ISSUE THREAD

**Issue by pacopepepipo** [tfedor/AugmentedSteam#1030]
### Current Behavior (if any)
The button that we have before, now have disappeared 

### Desired Behavior
To get the button back

### Motivation / Use Case for Changing the Behavior
Useful for big inventories

https://i.imgur.com/yLc1JuK.png

https://i.imgur.com/5KMxMgW.png

**Comment by candela97** [comment]
Yep, can confirm. Looks like Steam changed it so there're no more DOM changes in the inventory tabs area. I have an open PR that fixes this.

**Comment by pacopepepipo** [comment]
> Does it work if you switch inventories? 

indeed it does, thanks!
