### ISSUE TITLE
[BUG] Review filter's review count section does not work

### ISSUE THREAD

**Issue by randomguyingithub** [tfedor/AugmentedSteam#1039]
### Expected Behavior
Game with Review below specified number (10) should not appear.

### Actual Behavior
Some game filtered out but not all that review counts that are below specific number. Pattern unknown.

### Steps to Reproduce the Problem

  1.  go to Steam store game list e.g https://store.steampowered.com/search/?sort_by=Released_DESC
  2.  set the value in the left box of Reviews count section whatever you want. In my case, 10, then press Enter
  3.  See actual behavior

### Specifications

  - Augmented Steam Version: 2.0.0
  - Browser Version :  Firefox: 85.0 (64-bit) Chrome:  88.0.4324.146 (64-bit)

**Comment by randomguyingithub** [comment]
Don't want to clog up the page with large image so here's  the links
https://user-images.githubusercontent.com/13596387/106709810-00093980-6630-11eb-9b62-79d9b7403a16.png
https://user-images.githubusercontent.com/13596387/106709814-013a6680-6630-11eb-91b6-9cce6358d69e.png
https://user-images.githubusercontent.com/13596387/106709817-01d2fd00-6630-11eb-8b9e-786ed3c6c1bb.png

**Comment by candela97** [comment]
@MxtOUT The bug is our filters (and highlights/eabanners) aren't re-applied on new search rows that appear after scrolling further down and/or applying filters.
