### ISSUE TITLE
[BUG] Augmented Steam no longer filtering all early access titles.

### ISSUE THREAD

**Issue by choirsoftheeye1** [tfedor/AugmentedSteam#1041]
### Expected Behavior

Pre-2.0 the "hide early access" box in Augmented Steam would remove all items tagged as early access from searches.

### Actual Behavior

As of 2.0, only some early access items are excluded from searches. The remaining items have the blue "early access" sash removed. 

Examples of those that are no longer filtered include Compound, Phasmophobia, Satisfactory, Dyson Sphere Program, World of Horror, Prodeus, Door Kickers 2: Task Force North, Master of Pottery, Spin Rhythm DX.

Examples of those still filtered: Ultrakill, Townscaper.

### Steps to Reproduce the Problem

Searching for any of the no longer excluded results with "hide early access" enabled should do it. I was able to replicate the behavior in a private window with Augmented Steam enabled, so that indicates my other steam settings are not generating the problem.

### Specifications

  - Augmented Steam Version: 2.0
  - Browser Version : Firefox 85.0

**Comment by candela97** [comment]
Thanks for the detailed report! This seems to be the same issue as #1039.

**Comment by MxtOUT** [comment]
Seems like it, yeah
