### ISSUE TITLE
[BUG] Microsoft Edge extension cannot be linked to IsThereAnyDeal accounts

### ISSUE THREAD

**Issue by l0wBoB** [tfedor/AugmentedSteam#1043]
### Expected Behavior
The Microsoft Edge extension may be successfully linked to an IsThereAnyDeal account.

### Actual Behavior
After logging in to IsThereAnyDeal  and authorizing the request for permission, IsThereAnyDeal redirects to a 404-error page.

### Steps to Reproduce the Problem

  1. click the connect button in the extension 
  2. (log in to IsThereAnyDeal )
  3. click the authorize button on IsThereAnyDeal

### Specifications

  - Augmented Steam Version: 2.0.0
  - Browser Version: 88.0.705.56

**Comment by MxtOUT** [comment]
Yeah, I noticed that too close before release, but only shortly after reloading the unpacked extension.
I figured it had something to do with our development setup (in particular the randomly assigned extension ID), but that doesn't seem to be the case...
Are you able to consistently reproduce this?

**Comment by l0wBoB** [comment]
> Yeah, I noticed that too close before release, but only shortly after reloading the unpacked extension.
> I figured it had something to do with our development setup (in particular the randomly assigned extension ID), but that doesn't seem to be the case...
> Are you able to consistently reproduce this?

Surprisingly, no. At my other PC with Edge beta 89.0.774.18 it worked just now.

**Comment by l0wBoB** [comment]
On the device where I had this problem initially, it is still reproduceable.
Edge version there is now 88.0.705.68.
