### ISSUE TITLE
No Game Highlighting on Activity Feed

### ISSUE THREAD

**Issue by MrL0G1C** [tfedor/AugmentedSteam#1048]
I've tried:

Turned off all other extensions
Updated Chrome
Chrome: Cleared history data (everything other than passwords)
Closed and re-opened Chrome
Reset data
Reset Augmented Steam
Posted new links to activity feed to see if they highlight.

Augmented Steam is not highlighting Wish-listed, owned or ignored games for me :-(

Win 7 64bit, 
Chrome Version 88.0.4324.150 (Official Build) (64-bit)
Augmented Steam v2.0.0

Some activity feeds (like mine) start with steamcommunity.com/profiles/
and some start with steamcommunity.com/id/
, Related?

Request: Make the highlighting work on more steam pages like those starting with steamcommunity.com/groups/ or add an option to allow us to add urls that have highlighting

**Comment by candela97** [comment]
This has been fixed with #1040, and should be included in the next release.
