### ISSUE TITLE
[BUG] Highlighting does not work after applying new search filter

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1053]
### Expected Behavior
Reapply highlighting after applying filter

### Actual Behavior
No highlighting after applying filter

### Steps to Reproduce the Problem

  1. Go to https://store.steampowered.com/search/?category1=998&publisher=Xbox%20Game%20Studios
  2. Apply filter that retrieves new search results (e.g. games type only)
  3. Observe no highlighting

### Specifications

  - Augmented Steam Version: 2.0.0
  - Browser Version : Brave | 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)

**Comment by candela97** [comment]
Duplicate of #1039.
