### ISSUE TITLE
[FEATURE REQUEST] Report the package/game name after redemption attempt for duplicate and owned games

### ISSUE THREAD

**Issue by SpaceClicker** [tfedor/AugmentedSteam#1058]
### Current Behavior (if any)

After attempting to redeem a key at: https://store.steampowered.com/account/registerkey
If the key is a DUPLICATE or a game already owned in the account it will tell you so, but does not give an indication of what game it is. In some cases you may have a key that can be multiple different games (if won through a giveaway for instance), or is just a key you have and you forgot what game it is for.  If you already own it you may want to give it away to someone, and knowing what game it is for would be good information to have.

### Desired Behavior

My request is to have Augmented Steam display the package name/game name so that you don't need to use the developer console to get the information (and often have to attempt redemption again, since you most likely didn't have the console enabled the first time you attempted redemption).

### Motivation / Use Case for Changing the Behavior

If you turn on Network debugging in the developer console on Firefox, you can see that it actually does send the name of the package for the key that you just attempted to redeem, it just isn't displayed to the end user.

Network debugging shows:

Domain: store.steampowered.com
File: /account/ajaxregisterkey/

"purchase_receipt_info" -> "line_items" may contain multiple packages, those packages each contain:

"packageid" - Package ID number
"appid" - App ID
"line_item_description" - Contains the package name (usually the name of the game)

This information should be displayed to the user so that it is not necessary to turn on the developer console and know where/what to look for.

**Comment by candela97** [comment]
Noted as part of #449.

**Comment by MxtOUT** [comment]
I will close this, since it's already tracked, but thanks for the extra info!
