### ISSUE TITLE
[BUG]steamThe price display error

### ISSUE THREAD

**Issue by moran0** [tfedor/AugmentedSteam#1060]
> ### Expected Behavior

### Steps to Reproduce the Problem

  1. 
  2. 
  3. 

### Specifications

  - Augmented Steam Version: 
  - Browser Version : 
![QQ截图20210212025800](https://user-images.githubusercontent.com/29173838/107687154-1a52af80-6ce1-11eb-8183-e301a9f704c6.jpg)
![QQ截图20210212025707](https://user-images.githubusercontent.com/29173838/107687161-1b83dc80-6ce1-11eb-8649-b3760b84dab6.jpg)
![QQ截图20210212025624](https://user-images.githubusercontent.com/29173838/107687164-1c1c7300-6ce1-11eb-8493-97c06ea60419.jpg)

**Comment by MxtOUT** [comment]
You're region is not supported by ITAD, that's why you're getting the converted prices
