### ISSUE TITLE
Duplicate Remove From Wishlist

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1085]
Seems Steam has continued the trend of implementing features from Augmented Steam.
Steam store pages now added a dropdown menu that allows you to directly remove a game from your wishlist, as so:
![image](https://user-images.githubusercontent.com/4411977/109213479-f008f380-77b0-11eb-89cf-540249de458b.png)
AS:
![image](https://user-images.githubusercontent.com/4411977/109213973-8b9a6400-77b1-11eb-9cd7-e05ab0af6b15.png)

I like it gives you both options, but having to navigate to a dropdown menu is a bit more bothersome than directly clicking on "On Wishlist". So, I don't know what you guys prefer to do. Maybe... disable it by default now and make it replace Steam native dropdown menu when enabled. Or just remove it altogether, since that lowers maintenance work, extension size, etc.

**Comment by candela97** [comment]
Not surprising since it's been a feature on new style sale pages for a while (one click add/remove). Luckily it doesn't break anything on our side, so it's not a serious issue. One thing to consider is there's extra logic attached to our implementation (namely remove from ITAD waitlist), so maybe it's fine to leave it as-is?

**Comment by candela97** [comment]
> Luckily it doesn't break anything on our side, so it's not a serious issue.

I spoke too soon...our add to waitlist dropdown is broken due to this change.

**Comment by Gyumaou** [comment]
> > Luckily it doesn't break anything on our side, so it's not a serious issue.
> 
> I spoke too soon...our add to waitlist dropdown is broken due to this change.

was about to say it does break wishlist menu, no need for separate entry I guess?

![0](https://user-images.githubusercontent.com/6417525/109393923-45addf00-791c-11eb-9ec2-c6433e99e2c9.JPG)
![1](https://user-images.githubusercontent.com/6417525/109393929-4b0b2980-791c-11eb-8a85-3faf42b8e154.PNG)

**Comment by MxtOUT** [comment]
Fixed by #1089
