### ISSUE TITLE
[Bug] Wishlist of 1040 items never loads

### ISSUE THREAD

**Issue by MrJaunty** [tfedor/AugmentedSteam#1091]
Attempting to load my wishlist of 1040 items results in an infinite loading animation. The wishlist never loads. I've attempted clearing my augmented steam cache using augmented steam's dropdown menu but it has had no effect. 

If augmented steam is disabled, all items are loaded and displayed correctly by the wishlist (e.g. when viewing in private browser where augmented steam is disabled)

Notes: 
- it is still possible to add items to/remove items from my wishlist from the application pages with augmented steam enabled. 
- items in the store are still correctly highlighted as being on my wishlist elsewhere in the steam store with augmented steam enabled. 
- only the wishlist page itself, **https://store.steampowered.com/wishlist/profiles/<MY_PROFILE_ID>/**, is affected.

**Comment by candela97** [comment]
Browser/version, Augmented Steam version? Can you consistently reproduce this under the same setup? Have you tested on other wishlists?

The extension shouldn't affect wishlist loading, in fact, none of the additional features are loaded if the wishlist loading icon is still showing. I've viewed wishlists with 2000+ items in the past and they take a while to load but work fine with the extension enabled.

**Comment by Revadike** [comment]
Perhaps related to https://github.com/tfedor/AugmentedSteam/issues/745?

**Comment by MrJaunty** [comment]
@candela97 
Browser Version: Firefox Browser 85.0.2 (64-bit). Will attempt reproduction with most recent version. 
Extension Version: Augmented Steam 2.0.0

Have not attempted with other users' wishlists, if you could provide a link to some I could use I'll verify. I was thinking along exactly the same lines as you re: the extension not actually interfering with loading. The only reason I created the bug report was that with augmented steam disabled, my wishlist loads correctly.

@Revadike 
Thanks for this link, however I can confirm I'm using Augmented Steam and not the deprecated Enhanced Steam.

**Comment by MrJaunty** [comment]
Issue reproduced using Firefox Browser 86.0 (64-bit).

**Comment by Revadike** [comment]
Could you check whether the wishlist load request, result in http error 500? Check the network tab in developer tools (F12).

**Comment by MrJaunty** [comment]
@Revadike they do 
When reloading, I see 5 attempts and each fails with a 500 internal server error. 
Backgrounding and re-focusing on the browser window results in a GetNotificationCounts request that fails with a 401 unauthorized.

**Comment by Revadike** [comment]
Okay, perfect, thanks. This belongs to the issue I linked then! It's about the same problem.

**Comment by MrJaunty** [comment]
Oh weird, sorry for my misunderstanding then. Should I take any action on this ticket (close etc) and is there any action I can take to resolve the issue on my side?

**Comment by Revadike** [comment]
Yeah, closing would be appropriate, as it's a duplicate issue.

**Comment by MrJaunty** [comment]
Duplicate of  #745
