### ISSUE TITLE
[FEATURE REQUEST] Keep order when exporting wishlist

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1094]
### Current Behavior (if any)
Changes user defined order of the current wishlist

### Desired Behavior
Keep the order the user defined when exporting the current wishlist

### Motivation / Use Case for Changing the Behavior
This is what a user expects, to have their export matching the visible wishlist on the web page. 

### Additional Info
https://github.com/tfedor/AugmentedSteam/issues/961#issuecomment-787011475

**Comment by MxtOUT** [comment]
Already implemented by f797f5a2e39392b2ee1c15386d82b2d420eebc35
