### ISSUE TITLE
[BUG] Failed to initiliaze Augmented Steam since V2.0.0 on Firefox ESR

### ISSUE THREAD

**Issue by aaronhatesregex** [tfedor/AugmentedSteam#1110]
### Expected Behavior

The extension loads successfully.

### Actual Behavior

It won't load on Steam. The console says

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. injected.js:1:5003
Some cookies are misusing the recommended “sameSite“ attribute 2
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. 2 User.js:52:44
Augmented Steam initialization Page.js:83:20
Failed to initiliaze Augmented Steam Page.js:84:20
Augmented Steam initialization Page.js:83:20
Failed to initiliaze Augmented Steam Page.js:84:20
    run Page.js:84
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. 2 Page.js:85:20
    run Page.js:85
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. 2 User.js:82:56
```
And I can't import or export config in `extension options` page.

### Specifications

  - Augmented Steam Version: 2.0.0 and 2.0.1 (1.x works fine IIRC)
  - Browser Version: Firefox ESR 78.8.0

### Additional Infomation

A random search of `A mutation operation was attempted on a database that did not allow mutations.` makes me think it can be related to IndexDB so I add some additional info that may help.

- Private Browsing Mode (I guess there is no persistent disk storage as IndexDB)
- First Party Isolation is enabled (seems to affect indexedDB)

That being said, the extension still won't initiliaze when I set `privacy.firstparty.isolate` to `false` and `dom.indexedDB.storageOption.enabled` to `true` :shrug: .

**Comment by MxtOUT** [comment]
The error is thrown at User.js:82:56, which, traced back, is a call to SteamCommunityApi.storeCountry() on the background page.
This function is trying to set a value on `localStorage`, so it shouldn't be IDB related.

I also couldn't reproduce this with the setup you described

**Comment by aaronhatesregex** [comment]
>  This function is trying to set a value on `localStorage`, so it shouldn't be IDB related.

Actually I don't know much about JavaScript so I'm just randomly guessing.

> I also couldn't reproduce this with the setup you described

Weird, I can't reproduce it with a fresh profile with only Augmented Steam installed either. It seems that I have to dig into my `user.js` and stop it from screwing things up.

Besides that, what else information can I provide to help you tackle the problem?

**Comment by aaronhatesregex** [comment]
> It seems that I have to dig into my user.js and stop it from screwing things up.

The issue persists even when I remove `user.js` and `pref.js`, so never mind, I might as well use Chrome version instead.
