### ISSUE TITLE
False Price Drop

### ISSUE THREAD

**Issue by Kallan007** [tfedor/AugmentedSteam#1113]
Current best price for Steam is shown.

Current best price shows a new low price at Newegg for the game Battlefleet Gothic: Armada 2 for $5.99. When I click on the link I get an "OOPS! Your offer could not be found..." message as that price drop does not exist; here is the URL: http://www.qksrv.net/media/offers/?AID=10446076&PID=6305441&URL=https%3A%2F%2Fwww.newegg.com%2Ffocus-home-interactive-battlefleet-gothic-armada-2%2Fp%2FN82E16832844107&utm_medium=affiliates&utm_source=afc-Tomas+Fedor&cjevent=ecd9471c82d311eb818301200a24060e

### Steps to Reproduce the Problem

  1. Ensure that the Current Price is accurate and current.
  2. Ensure that the Current Price link brings up the correct offer.
  3. 

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Microsoft Edge Version 89.0.774.50 (Official build) (64-bit)

**Comment by candela97** [comment]
Yeah seems like the link from ITAD is broken, but works fine if you navigate directly to Newegg: `https://www.newegg.com/focus-home-interactive-battlefleet-gothic-armada-2/p/N82E16832844107`

I've posted about this in the `bugs` channel of the ITAD Discord since it's problem with the ITAD site.

**Comment by Kallan007** [comment]
Thanks for the link, I will check it out.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Kallan007** [comment]
Thanks for the link, I will check it out.
