### ISSUE TITLE
Extend the Note Feature on Game Pages

### ISSUE THREAD

**Issue by SabreRunner** [tfedor/AugmentedSteam#1118]
Currently, the possible note size is very very small. Please allow to write more.

**Comment by candela97** [comment]
If you're hitting storage limitations, see #848, otherwise if you mean characters per note, the max length is 512, presumably to avoid people hitting said limit too quickly.

**Comment by SabreRunner** [comment]
Can this be an option? Is there a cleanup option to save space? It's just that 512 characters is very little.
