### ISSUE TITLE
[BUG] Wishlist does not load

### ISSUE THREAD

**Issue by FallOfValhalla** [tfedor/AugmentedSteam#1127]
### Expected Behavior
Seeing the wishlist

### Actual Behavior
The wishlist does not load, no matter how long I wait
![Capture](https://user-images.githubusercontent.com/50292556/112417712-047ae480-8d8d-11eb-8e6d-f064f3c6353f.PNG)

### Steps to Reproduce the Problem

  1. A massive wishlist I suppose?

### Specifications

  - Augmented Steam Version: 2.0.1 (Although I have been having this issue for almost a year now)

  - Browser Version : Version 89.0.4389.90

**Comment by Revadike** [comment]
If you check the console log (via F12), do you see wishlist network request(s) resulting in http error code 500? If so, you're experiencing the same problem as https://github.com/tfedor/AugmentedSteam/issues/745

**Comment by FallOfValhalla** [comment]
> If you check the console log (via F12), do you see wishlist network request(s) resulting in http error code 500? If so, you're experiencing the same problem as #745

Yeah seems the like same issue. There are a ton of "Failed to load resource". Is there a solution to this?

**Comment by Revadike** [comment]
Sadly not, it's an open issue. Anyway, let's not use duplicate issue threads. We'll discuss this further in the main issue. You may close this issue.
