### ISSUE TITLE
[BUG] Options don't appear on Firefox

### ISSUE THREAD

**Issue by wefalltomorrow** [tfedor/AugmentedSteam#1132]
### Expected Behavior

All options appear and are adjustable.

![image](https://user-images.githubusercontent.com/45746576/114684304-221be800-9d54-11eb-98e4-1276b0858279.png)

### Actual Behavior

Only a select few options appear, even with all other addons disabled and multiple uninstall/reinstalls of the addon amongst browser restarts.

![image](https://user-images.githubusercontent.com/45746576/114684248-14666280-9d54-11eb-828d-0197b3aa00c0.png)

### Steps to Reproduce the Problem

  1. Install AugmentedSteam on Firefox
  2. Go to options page
  3. ????

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Firefox 87.0 (64-bit)

**Comment by wefalltomorrow** [comment]
Still broken on Firefox 89.0 sadly.

**Comment by MxtOUT** [comment]
Is your browser console showing any errors?

**Comment by wefalltomorrow** [comment]
> 
> 
> Is your browser console showing any errors?

![image](https://user-images.githubusercontent.com/45746576/121113527-87bcba00-c855-11eb-89d4-c353a66c10f9.png)

**Comment by MxtOUT** [comment]
Can you expand that error message please?

**Comment by wefalltomorrow** [comment]
> 
> 
> Can you expand that error message please?

Here's all the ones I could expand, not sure how to expand the others.

![image](https://user-images.githubusercontent.com/45746576/121164017-9ffefa00-c892-11eb-8fa3-2401b6432561.png)

**Comment by MxtOUT** [comment]
What do you see if you [inspect Augmented Steam's background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?

**Comment by wefalltomorrow** [comment]
> 
> 
> What do you see if you [inspect Augmented Steam's background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?

I wasn't able to follow the instructions as it seems to be different on Firefox Proton than those screenshots, so this may be incorrect but this is what I see:

![image](https://user-images.githubusercontent.com/45746576/121801370-4e7fb200-cc7a-11eb-88dc-c2e523a88fcf.png)

**Comment by MxtOUT** [comment]
You're on the right track, could you now please switch to the "Console" tab?
I see you already have 99+ errors in the top right

**Comment by wefalltomorrow** [comment]
![image](https://user-images.githubusercontent.com/45746576/121801937-39f0e900-cc7d-11eb-8b7d-0ec8b556e799.png)
![image](https://user-images.githubusercontent.com/45746576/121801940-3f4e3380-cc7d-11eb-8233-b07801280029.png)
![image](https://user-images.githubusercontent.com/45746576/121801946-44ab7e00-cc7d-11eb-98fd-9f098e58ce46.png)
![image](https://user-images.githubusercontent.com/45746576/121801951-483f0500-cc7d-11eb-81c7-62de7d061eca.png)

**Comment by MxtOUT** [comment]
Ok, on the debugging page, what is the internal UUID for Augmented Steam?
I need to be able to assign the errors you sent to AS.
Looks like this:
![image](https://user-images.githubusercontent.com/14999077/121802048-d80f8f80-cc3a-11eb-8131-b53cead01bef.png)

**Comment by wefalltomorrow** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/45746576/121802070-0f536000-cc7e-11eb-9969-cffd7e72fff1.png)

**Comment by MxtOUT** [comment]
The errors that occur at background.js:3007 could you click on that link to the file and send me a snippet of that please?

**Comment by wefalltomorrow** [comment]
Sure!

![image](https://user-images.githubusercontent.com/45746576/121802949-6fe49c00-cc82-11eb-9bfe-59c50568c441.png)

**Comment by MxtOUT** [comment]
This is definitely not Augmented Steam and I can't reproduce this at all, sorry

**Comment by wefalltomorrow** [comment]
"9b465afc-7257-4106-a5d3-de736820cda6" from this image: https://user-images.githubusercontent.com/45746576/121801951-483f0500-cc7d-11eb-81c7-62de7d061eca.png

Which is Bitwarden. That's what you asked to see? 😮

**Comment by wefalltomorrow** [comment]
![image](https://user-images.githubusercontent.com/45746576/121803859-c48a1600-cc86-11eb-9683-ef7c0d2d9477.png)

![image](https://user-images.githubusercontent.com/45746576/121803868-cf44ab00-cc86-11eb-8906-428c19732a38.png)

**Comment by MxtOUT** [comment]
What I meant with my previous comment is that I think the errors you encountered are all not Augmented Steam related.
Though the options page is clearly not working.
Can you try it again with all extensions disabled, clear the console before opening the options page and then send a screenshot?

**Comment by wefalltomorrow** [comment]
Sure, here you go: 
![image](https://user-images.githubusercontent.com/45746576/121804819-93601480-cc8b-11eb-8242-bb2f541048a2.png)

**Comment by MxtOUT** [comment]
Sorry, I meant the background page

**Comment by wefalltomorrow** [comment]
I've uninstalled the extension, sorry.
