### ISSUE TITLE
[BUG] "Filter to games you both own" is removed

### ISSUE THREAD

**Issue by avi12** [tfedor/AugmentedSteam#1133]
### Expected Behavior
The checkbox should stay in place

### Actual Behavior
It is removed

### Steps to Reproduce the Problem

  1. Go to `https://steamcommunity.com/id/<id>/games?tab=all`, e.g. https://steamcommunity.com/id/avi12/games?tab=all
  2. No "Filter to games you both own" checkbox next to the "Filter games" text box

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version: Edge beta 90.0.818.38

**Comment by candela97** [comment]
The extension replaces it with 2 separate checkboxes "Hide games that you do not own" and "Hide games that you own". Much more useful I believe!

**Comment by candela97** [comment]
The extension replaces it with 2 separate checkboxes "Hide games that you do not own" and "Hide games that you own". Does it not work for you?

**Comment by avi12** [comment]
![image](https://user-images.githubusercontent.com/6422804/119213758-4f358600-baca-11eb-852a-90a8da391fe9.png)

**Comment by candela97** [comment]
Are you viewing your own profile? These options won't show on your own profile since they're redundant (the page only shows the games you own already). You can disable the extension to verify this.

**Comment by avi12** [comment]
Fair enough
Just opened a friend's profile, and still, no checkboxes
![image](https://user-images.githubusercontent.com/6422804/119240051-07f4d700-bb56-11eb-8515-0c848cd805bb.png)

**Comment by candela97** [comment]
Any errors in the browser console? Does it show that features are loaded? By default there should be 2, but it looks like you've disabled showing game stats, so there should be 1. Other than that, this feature has a log-in check, so double check if you're logged in to steamcommunity.

**Comment by avi12** [comment]
> Any errors in the browser console?
Nope, it's clear of any output
> Does it show that features are loaded?
Now that you mention it, I notice that Augmented Steam only runs on `steampowered.com`, but not `steamcommunity.com` (no green circle indicator below my profile picture)

**Comment by candela97** [comment]
Well, I just installed the extension from Microsoft Store on Edge 90, and this feature along with other community-related features seems to work fine for me, so I'm out of ideas. Tried reinstalling? (don't forget to backup your setting first)

**Comment by avi12** [comment]
Reinstalling the extension solved the issue
I wonder why it was caused in the first place

**Comment by avi12** [comment]
Though now there's a visual issue
![image](https://user-images.githubusercontent.com/6422804/119562031-8f3c8780-bdae-11eb-96b9-a200fc626dff.png)

**Comment by candela97** [comment]
> Reinstalling the extension solved the issue
> I wonder why it was caused in the first place

I just noticed the install size on your screenshot was off (it should a little over 15 MB), so maybe it was corrupt.

> Though now there's a visual issue

Yeah that's due to Steam adding the "Achievement Completion" sorting method. It'll hopefully be sorted out in the next version.

**Comment by avi12** [comment]
Alrighty, thanks for your help!
