### ISSUE TITLE
[BUG] Incorrect best price for Steam

### ISSUE THREAD

**Issue by jacobgelling** [tfedor/AugmentedSteam#1134]
### Expected Behavior
When Steam has the best price, it should display Steam with the correct price.

### Actual Behavior
For all titles where Steam has the best price, the current best price is either greater the actual Steam price, or lists another Store with a worse price.

2 examples:

![Screenshot 2021-04-17 at 23 10 32](https://user-images.githubusercontent.com/3254275/115126797-205f5800-9fd2-11eb-879f-c6219c47da6f.png)

![Screenshot 2021-04-17 at 23 07 39](https://user-images.githubusercontent.com/3254275/115126736-b9da3a00-9fd1-11eb-9905-b8da300b2909.png)

### Steps to Reproduce the Problem

  1. Go to a title where the best price is on Steam.

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : 89.0.4389.128

**Comment by candela97** [comment]
If your currency isn't supported by ITAD, the prices can be misleading, see #482

**Comment by jacobgelling** [comment]
Yes, it seems to be the same issue as #482
