### ISSUE TITLE
[FEATURE REQUEST] Add links to the Visual Novel Database (vndb.org)

### ISSUE THREAD

**Issue by bruce-davis** [tfedor/AugmentedSteam#1136]
### Current Behavior (if any)
None

### Desired Behavior
Please add links to the Visual Novel Database (vndb.org) to VN games where appropriate. For example, create a link on Steam page for visual novel _CLANNAD_:

*CLANNAD* on Steam
https://store.steampowered.com/app/324160/CLANNAD/

*CLANNAD* on vndb.org
https://vndb.org/v4

### Motivation / Use Case for Changing the Behavior
Visual novels are popular on Steam and it's helpful to read about them on vndb.org before buying and while playing them.

**Comment by candela97** [comment]
Hmm, this might be difficult because we will need to create and maintain the url mapping info since vndb pages don't query Steam appids.

**Comment by yaron-dav** [comment]
Maybe instead of adding a link to the game page on vndb, just link to a search page (based on the game name/title on steam, filtered for only OS where Steam actually runs on, for any game tagged on Steam as Visual Novel)? This should be fairly usable for a lot of VNs, even if not entirely ideal.

**Comment by MxtOUT** [comment]
This is a very niche case and can be added by the user once #1160 is implemented

**Comment by kazerniel** [comment]
I added VNDB as a search engine in my Firefox, so I just copy the game name and search for it. I agree that its tagging system is vastly more comprehensive than Steam's.

**Comment by candela97** [comment]
From the next version onwards (> 2.1), there'll be a new section under 3rd-party links for app pages for you to add custom links to app pages as well:
![螢幕擷取畫面 2021-10-21 075702](https://user-images.githubusercontent.com/54083835/138188811-772d0aa2-eefb-4ea4-9e23-4b1badc657f6.jpg)
