### ISSUE TITLE
[FEATURE REQUEST] Add links to SteamHunters page on user profiles

### ISSUE THREAD

**Issue by FallOfValhalla** [tfedor/AugmentedSteam#1138]
### Current Behavior (if any)
None

### Desired Behavior
Add users SteamHunters profile, just like the other sites like AStats, Steamrep, etc
https://steamhunters.com/id/RiseOfValhalla/games

### Motivation / Use Case for Changing the Behavior
It is another achievement tracking website. But imo is a must better one than AStats since it is more carefully curated, as there is more instant moderator support since they reply to quite quickly to suspected users. It also provides to various info which other achievement tracking sites doesn't and also links to other similar sites on user's profiles.

**Comment by kazerniel** [comment]
This, plus links to game pages like: https://steamhunters.com/stats/105600/achievements

**Comment by candela97** [comment]
You can add any custom site link that queries SteamID64 to your profile, for example: 
![螢幕擷取畫面 2021-05-22 053450](https://user-images.githubusercontent.com/54083835/119200423-7d619880-babf-11eb-8ce0-32645837f795.jpg)

The game page info looks like a good candidate for 3rd-party links on store pages.

**Comment by FallOfValhalla** [comment]
> You can add any custom site link that queries SteamID64 to your profile, for example:
> ![螢幕擷取畫面 2021-05-22 053450](https://user-images.githubusercontent.com/54083835/119200423-7d619880-babf-11eb-8ce0-32645837f795.jpg)
> 
> The game page info looks like a good candidate for 3rd-party links on store pages.

Thanks! Is there a way to get a direct link from game pages as well?

**Comment by candela97** [comment]
> Thanks! Is there a way to get a direct link from game pages as well?

That will need to be added to the extension. I'll make a PR once I have time (or you can if you want).

**Comment by Revadike** [comment]
> > Thanks! Is there a way to get a direct link from game pages as well?
> 
> That will need to be added to the extension. I'll make a PR once I have time (or you can if you want).

I think custom game links would be a great addition!

**Comment by natelovesyou** [comment]
> 
> 
> > Thanks! Is there a way to get a direct link from game pages as well?
> 
> That will need to be added to the extension. I'll make a PR once I have time (or you can if you want).
A custom link system would be very handy, namely for the Steam Store Page.
