### ISSUE TITLE
[FEATURE REQUEST] Bypass login requirements for adult games

### ISSUE THREAD

**Issue by dojima** [tfedor/AugmentedSteam#1150]
### Current Behavior (if any)
Adult games are censored in search and don't load when clicked unless logged in.
### Desired Behavior
That searches and landing pages be fully uncensored without logging in.
### Motivation / Use Case for Changing the Behavior
I expected Augmented Steam to already do this since it has an age verification bypass, but it doesn't.  Maybe because it's not possible?

**Comment by candela97** [comment]
I don't think it's possible, but really Steam should make it so that you can enter age verification without having to create an account...maybe someday

**Comment by Revadike** [comment]
Yes, not possible, unless logged in.
