### ISSUE TITLE
[BUG] Displays the best price of another game with same name.

### ISSUE THREAD

**Issue by beaves** [tfedor/AugmentedSteam#1151]
### Expected Behavior

Displays the correct best price.

### Actual Behavior

Displays the best price of another game with the same name only in upper case.
Invisible with ID 1607730 cost 3,99€
INVISIBLE with ID 777560 is free.

### Steps to Reproduce the Problem

  1.  Go to https://store.steampowered.com/app/1607730/Invisible/

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Firefox 88.0.1

**Comment by MxtOUT** [comment]
This is an ITAD issue, since the ITAD page has two Steam entries
