### ISSUE TITLE
[BUG]Cannot remove the augmented steam background

### ISSUE THREAD

**Issue by allahfunny** [tfedor/AugmentedSteam#1167]
### Expected Behavior
Being able to remove the steam augmented background so that the default one shows.

### Actual Behavior
No option to remove it.

### Steps to Reproduce the Problem

  1. 
  2. 
  3. 

### Specifications

  - Augmented Steam Version: 
  - Browser Version :

**Comment by candela97** [comment]
Go here https://steamcommunity.com/my/edit/background and select "None" in the dropdown.

**Comment by allahfunny** [comment]
https://cdn.discordapp.com/attachments/809915082670342155/850797910929309726/unknown.png
thats not an option

**Comment by candela97** [comment]
Ah sorry, that's was for profile styles, for backgrounds just click "Clear".
