### ISSUE TITLE
[BUG] Nothing works for me.

### ISSUE THREAD

**Issue by Metaph413** [tfedor/AugmentedSteam#1168]
### Expected Behavior

For price region comparisons to display, the PCGaming and SteamDB links to display, and other features to work.

### Actual Behavior

The store doesn't have any of them visible.

### Steps to Reproduce the Problem

  1. Go to a Steam game page with Augmented Steam installed.

### Specifications

  - Augmented Steam Version: Latest version from Chrome Store
  - Browser Version: Brave 1.16.68
  - OS Version: Pop!_OS 20.10

**Comment by Revadike** [comment]
Can you access the options page? chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/html/options.html

**Comment by candela97** [comment]
Check the "Details" tab of the extension and see if it has access to `steampowered.com` and `steamcommunity.com` urls.

**Comment by Metaph413** [comment]
> Can you access the options page? `chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/html/options.html`

I can.


> Check the "Details" tab of the extension and see if it has access to `steampowered.com` and `steamcommunity.com` urls.

It has access to both sites. The error seems to appear in Inspect.

DevTools failed to load SourceMap: Could not load content for chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

The extension worked perfectly for me before this error showed up in the middle of the year.

**Comment by Revadike** [comment]
We are in the middle of the year. Did u mean last year?
Maybe try reinstalling the web browser?

**Comment by MxtOUT** [comment]
> DevTools failed to load SourceMap: Could not load content for chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

This is only a warning and only relevant when you want to debug the extension.

So you're not seeing any of this?
![image](https://user-images.githubusercontent.com/14999077/123448599-5e34ba00-d5db-11eb-886f-beda536a6dd8.png)

**Comment by DianaNites** [comment]
I have this same issue. AFAIK everything else works fine, but its *some* store page specific stuff, like ProtonDB, that doesn't work. But IsThereAnyDeal stuff shows up fine?

**Comment by MxtOUT** [comment]
Price comparisons should work, they sometimes don't show up if the server is overloaded. If you permanently don't see them, please reopen.
The problem with the extra links is tracked in #1175 and will be fixed with the next version
