### ISSUE TITLE
[BUG] Friendsthatplay page

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1177]
### Expected Behavior
Don't show duplicates.

### Actual Behavior
For some reason AS duplicates a block of friends.

### Steps to Reproduce the Problem

  1. Go to https://steamcommunity.com/my/friendsthatplay/440
  2. Observe `All friends who own this` being added, which includes all friends who were shown already

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Comment by candela97** [comment]
There's an option for this, I believe, somewhere at the bottom. I noticed this too when working on reorganizing the options page.

TODO check the code in ES and see if this is some legacy enhancement that has since been done natively and can be removed.

**Comment by Revadike** [comment]
well, the sorting is added, but the dupe block isn't supposed to be there?

**Comment by Revadike** [comment]
Right, but I wouldn't show both, as dupe. Remove the original one (when request response success is `true`).

**Comment by MxtOUT** [comment]
I found the [original function](https://github.com/jshackles/Enhanced_Steam/blob/7d4b116941e850a3dafd90eb5372f1921e7a6534/enhancedsteam.js#L8088), I suppose that this has since been implemented by Steam. Therefore I'm removing it

> Right, but I wouldn't show both, as dupe. Remove the original one (when request response success is true).

**Comment by Revadike** [comment]
It may be a good idea to compare both responses, just in case. 
For one, I know the API endpoint doesn't work for banned games, while the html page works for them. So that makes the native html page superior. 
But maybe the API has something that makes it superior to the native html page content.

**Comment by Revadike** [comment]
After a quick comparison. It appears the API is really inferior. It does not return owners/friends that have no playtime at all, while the native HTML page does. 
So it was a good idea to remove it!

**Comment by Revadike** [comment]
Tested and it is indeed removed!
