### ISSUE TITLE
[FEATURE REQUEST] Export lists from Library

### ISSUE THREAD

**Issue by Dicur3x** [tfedor/AugmentedSteam#1183]
### Current Behavior (if any)
I can't export my library with lists.

### Desired Behavior
I wanna export my library (with lists) - because i want recommend some games to anyone and games i satisfied in list "Favourite". Also, i have other list, i wanna export games from it too. Please add it. Now i can export wishlist only.

### Motivation / Use Case for Changing the Behavior
Recommend games to someone.
Write Articles or create threads about favourite games.
Analyze how many games i completed (list completed games) and how many i have in "to play". 

LISTS IS WONDERFUL! Please, add ability to export it. I found export all games (includes deleted) on isThereAnyDeal, but there no lists tags. So it useful.

**Comment by MxtOUT** [comment]
You mean the lists that are visible in the Steam client?
I don't think that they are retrievable from your browser

**Comment by Dicur3x** [comment]
Yes, in client. But maybe it somehow possible, idk. It will be BIG advantage of Augmented steam.

**Comment by MxtOUT** [comment]
Unless they add a web interface for this, I don't think there's a (feasible) way to implement this, sorry

**Comment by Dicur3x** [comment]
Maybe it's possible somehow export it from steam client? not with augmented steam, maybe other tool?

**Comment by MxtOUT** [comment]
I don't know, but as you said, this would be done with another tool

**Comment by Revadike** [comment]
You could combine these 2 endpoints:
https://steamapi.xpaw.me/#IPlayerService/GetOwnedGames
https://steamapi.xpaw.me/#ISteamApps/GetAppList

But I feel like this could easily be implemented together with related issues/requests:
https://github.com/tfedor/AugmentedSteam/pull/735
https://github.com/tfedor/AugmentedSteam/issues/1066
https://github.com/tfedor/AugmentedSteam/issues/622

**Comment by Dicur3x** [comment]
Nah, it's just export all games, not only favourite (as i want), i can't filter from all list just list of favourites.
