### ISSUE TITLE
[BUG] SteamDB, PCGamingWiki, etc Links down't show up on store page.

### ISSUE THREAD

**Issue by VSuhas22** [tfedor/AugmentedSteam#1197]
The external links that show up on the store page don't show up.
### Expected Behavior
[These are the link's I'm talking about.](https://lh3.googleusercontent.com/0JZy2GIKBHhdIa65vB8BVKh_dus_GhMMOzvV5bze0yB_TfcdmR-Yy1MF2n0cQm6vChzfBa1FguolFDb8KAM48k7N9g=w640-h400-e365-rj-sc0x00ffffff)

### Actual Behavior
The tab that shows those links just doesn't popup, observed on both [Firefox ](https://raw.githubusercontent.com/VSuhas22/DeloitteTransfer/main/firefox.jpg)and [Chrome](https://raw.githubusercontent.com/VSuhas22/DeloitteTransfer/main/chrome.png).

### Steps to Reproduce the Problem
Just open the page and check

### Specifications
  - Augmented Steam Version: 2.0.1
  - Browser Version : Firefox - 89.0.1; Chrome - 91.0.4472.114

**Comment by Revadike** [comment]
Dupe of https://github.com/tfedor/AugmentedSteam/issues/1175

**Comment by VSuhas22** [comment]
@Revadike Shit, I carefully checked through the recent bug reports to check if this was a duplicate, but forgot to check the pinned bugs.
Sorry my bad

**Comment by VSuhas22** [comment]
I just checked the recently closed bugs, and whew, there are many stupid people like me.
