### ISSUE TITLE
[BUG] All Notes gone.

### ISSUE THREAD

**Issue by markwr** [tfedor/AugmentedSteam#1207]
### Expected Behavior

At the extension Options page, there is a choice in the lower right to "Reset". When I click it, I just expect it to reset all options to their default.

### Actual Behavior

Today, clicking the "Reset" option seems to have removed all my existing Notes (the "Update note" area of steampowered store pages).

I'd like to also reference:
https://github.com/tfedor/AugmentedSteam/issues/848
https://github.com/tfedor/AugmentedSteam/issues/1024

I'm a database programmer, can you suggest any folder or file I might try to use to regain records or restore whatever database or file backup that may still contain all my Notes?

EDIT: I believe I have found the file I want, here are the last 2 saves (Exports) that I have:
06/09/2021 8,916 bytes "AugmentedSteam_v2.0.1.json"
06/28/2021    89 bytes "AugmentedSteam_v2.0.1 6-28-21.json"
As you can see, the Export I did today (after the Reset) is very small.
In the Export I did a few weeks ago, I can see the area that starts the notes as:
"user_notes":{
 and I have 337 notes in that section.
Unfortunately, I've done a great deal of adding notes since then, so I'm still hoping you can help me find a more recent backup area (LET ME KNOW PLEASE). As an extra precaution, I will try to remember to always "Export" before I "Reset", though I hope a future version will fix the bug of removing all notes.

EDIT2:
For what it's worth, I've made backups of these files too:
C:\Users\Mark\AppData\Roaming\Mozilla\Firefox\Profiles\082atqin.Default-1575331692262\sessionstore-backups\previous.jsonlz4	6/28/2021	11:15:55	445,510

6/28/2021...
10:42:35	129,815	addons.json
10:44:37	174,757	extensions.json
11:21:40	2,959	extension-settings.json

### Steps to Reproduce the Problem

  1.  Go to extension Options page.
  2.  Click "Reset"
  3.  Look at steampowered store pages to see if "Update note" area is empty.

### Specifications

  - Augmented Steam Version:  2.0.1
  - Browser Version : Firefox 89.0.2 (64-bit)

**Comment by Revadike** [comment]
They are stored in IndexedDB (F12 -> Application)
![image](https://user-images.githubusercontent.com/4411977/123668866-d3062f00-d83b-11eb-814f-ed35f21d1f9e.png)

**Comment by markwr** [comment]
> IndexedDB

I should say that I am a "retired" database programmer, and the database programming I did was in FoxPro https://en.wikipedia.org/wiki/FoxPro for an insurance company IT department. I do not program extensions for browsers, so you may need to be more specific.

**Comment by Revadike** [comment]
Do this https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page
and follow my instructions from above

**Comment by markwr** [comment]
Thanks. The instructions don't match up to current firefox, but I made my way. It says their is no data in notes, which is odd because I did create one note after the "Reset", though maybe it's in RAM and I'd need to close/re-open browser. So you showed me how to find the Notes data, but what I really need is to know if there is a BACKUP history anywhere that I can access.
![Db_notes](https://user-images.githubusercontent.com/17146589/123678572-72afc700-d814-11eb-97ef-f79669a9b4de.jpg)

**Comment by markwr** [comment]
Also, see my EDIT's in the original post for more info there.

**Comment by markwr** [comment]
So, for now I've edited and imported my Export from a few weeks ago. I'll try to keep the file as small as possible until an update expands the Notes max size. Should I close this, or wait for that update to happen?

**Comment by Revadike** [comment]
Sorry, I was under the impression they were stored in IndexedDB, but they are not (yet). Actually, a new commit (https://github.com/tfedor/AugmentedSteam/commit/8f6b5b70d15d2ef4fb3ce82c8bb4844b0b8c15cf) changed this.

**Comment by MxtOUT** [comment]
There is no backup of your local database. You don't see any entries in your `notes` table there because in the current version it's not used. Notes are currently stored via synced or local storage.
Because this is the same storage area we're using for options, this will get cleared as well.

As @Revadike points out, in the next release we're giving the user the option to store their notes in the local database, which should automatically solve your issue.

Nevertheless I will create a fix for this if the user chooses to keep the old storage method

**Comment by markwr** [comment]
> in the next release we're giving the user the option to store their notes in the local database, which should automatically solve your issue.

Would this also increase the total maximum size of the users Notes collection?

> Nevertheless I will create a fix for this if the user chooses to keep the old storage method

Thanks.

I'd also like to take a moment to express gratitude for the AugmentedSteam extension. It is wonderful. And, the Notes feature is one of the highlights.

**Comment by MxtOUT** [comment]
> Would this also increase the total maximum size of the users Notes collection?

Yes, you will practically be able to store as many notes as you want
