### ISSUE TITLE
[BUG] Wrong trade offer count

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1208]
![image](https://user-images.githubusercontent.com/4411977/123712377-825df880-d872-11eb-9f1e-a428f9ab1cfc.png)

**Comment by MxtOUT** [comment]
I don't have an open trade offer, are you able to debug this @Revadike ?

**Comment by Revadike** [comment]
> I don't have an open trade offer, are you able to debug this @Revadike ?

You can craft a trade offer to anyone (with [me](https://steamcommunity.com/tradeoffer/new/?partner=82699538&token=V7DQVtra) for example). You don't have to actually send one to debug it, I think. I don't know exactly when the bug occurred. I just noticed it when verifying the trade offer just before I wanted to send it.

**Comment by MxtOUT** [comment]
You sure this is AS? Never seen that before

**Comment by Revadike** [comment]
Hmm, seems it is not, my bad. It is from Steam Economy Enhancer. But then I'm confused what `FCountTradeItems` is supposed to do, since it seems to do nothing?

**Comment by MxtOUT** [comment]
![image](https://user-images.githubusercontent.com/14999077/124189239-b6c6f400-dac0-11eb-88ab-8a1e35beb34e.png)
It does this

**Comment by Revadike** [comment]
> It does this

Yes I saw, that's why I edited my comment
