### ISSUE TITLE
[BUG] Gifts and passes in inventory not highlighted/marked

### ISSUE THREAD

**Issue by Cr4zyJ0k3r** [tfedor/AugmentedSteam#1213]
Under the conditions, that a gift contains multiple apps, the highlighting/marking not properly works.

The function is called by one argument
https://github.com/tfedor/AugmentedSteam/blob/5b04581744df735d4ff678c5db6622941a8a357a/src/js/Background/Modules/SteamCommunityApi.js#L154
but provides two paramters
https://github.com/tfedor/AugmentedSteam/blob/5b04581744df735d4ff678c5db6622941a8a357a/src/js/Background/Modules/SteamCommunityApi.js#L132
and the seconds paramters is used, but is null
https://github.com/tfedor/AugmentedSteam/blob/5b04581744df735d4ff678c5db6622941a8a357a/src/js/Background/Modules/SteamCommunityApi.js#L133

Solution:
```javascript
function addGiftsAndPasses(description) {
    const appids = GameId.getAppids(description.value);
```

**Comment by candela97** [comment]
The change looks reasonable, can you submit a PR and have it tested?

**Comment by Cr4zyJ0k3r** [comment]
PR created #1214
