### ISSUE TITLE
[BUG] Workshop item details are moved below top section

### ISSUE THREAD

**Issue by ithinkandicode** [tfedor/AugmentedSteam#1216]
### Expected Behavior
Workshop details should be displayed in the top section:

![](https://i.imgur.com/Jjgiisz.png)

### Actual Behavior
Details are moved to below. The main image now has large black bars above + below, and a large empty space to the right:

![](https://i.imgur.com/8IjyYp6.png)
![](https://i.imgur.com/VI6YDxN.png)

### Steps to Reproduce the Problem

  1. Visit a workshop item page ([example](https://steamcommunity.com/sharedfiles/filedetails/?id=1463543127))

### Specifications

  - Augmented Steam Version: latest (2.0.1)
  - Browser Version : Chrome latest (91)

### Notes

This may be an intended feature, but this is a major change and there's no option to change the behaviour, so it looks like an unintended bug.

**Comment by candela97** [comment]
This is expanded view, click on the expand icon that appears on the top right corner of the preview area to change it back to normal view.

Looks like the expanded view isn't working properly on workshop items...I'll see if it can be fixed.

**Comment by ithinkandicode** [comment]
@candela97 Ah, thank you! I hadn't noticed the expand button. That's solved it for me, thank you :)

I'm happy to close this, unless you'd like to keep it open to address the issue you mentioned.
