### ISSUE TITLE
[SOLVED - PLEASE SEE MY SOLUTION] How do I stop the wishlisted items from overlapping each other?

### ISSUE THREAD

**Issue by idgas01** [tfedor/AugmentedSteam#1226]
**This was my problem:**

I've had this problem ever since I installed AugmentedSteam, which was a super long time ago.  Like a year ago, maybe two years or longer.  It's why I never bothered to use the extension until now, because that overlapping is annoying.  Just now, I decided to try using it again.  I went to Augmented Steam Options and I unchecked every single thing.  The only thing that I was interested in was "Notes" for each wishlisted game.  It doesn't matter if I choose Compact or Expanded mode, as soon as I refresh the page it will show the wishlisted items overlapping each other.  See below screenshots of the overlapping items and more screenshots below those of how the wishlist is supposed to look.

**This is how the wishlisted items looked after a page refresh:**

![firefox_kWvXLJ4m1U](https://user-images.githubusercontent.com/75463665/126869087-7f69f631-e0a5-420c-8a57-d45454dadc12.png)

![firefox_g1yabwB7ik](https://user-images.githubusercontent.com/75463665/126869091-f4f2892f-d103-4731-9668-8d943284f62f.png)

**This is how the wishlisted items were supposed to look:**

![firefox_EXxEr8h0mo](https://user-images.githubusercontent.com/75463665/126869094-91b6f693-29ed-46a9-a39a-85087b4638b1.png)

![firefox_FsUuPQaX9V](https://user-images.githubusercontent.com/75463665/126869097-1ef6e9ee-d859-445f-a6fd-5bdc75d311e2.png)

**Comment by idgas01** [comment]
### I created a workaround.

I created a simple userscript that makes all of the wishlist item rows the default size by moving some of the child elements around.  As a result, the wishlist item rows no longer overlap.


https://pastebin.com/pYU0qcDb


![firefox_NWruzGwKvg](https://user-images.githubusercontent.com/75463665/126872283-3781b572-3fbe-46fb-b616-ee7b50d8be32.png)

**Comment by Revadike** [comment]
Does that also work for the non-compact display?

**Comment by idgas01** [comment]
> 
> 
> Does that also work for the non-compact display?

Good question.  I tested it just now, and yes it works for the non-compact "Expanded" mode.

**Comment by idgas01** [comment]
@Revadike - Yesterday's userscript wasn't working because it was using some old code that I was testing but had already deleted.  And refreshing the page a million times would not stop the old code from displaying.  So that is why I thought that it was working when it wasn't.  But after the thousandth refresh, it finally showed only my new code and that's when I realized my new code was faulty.  So I made the necessary changes.  I have already updated the Pastebin link and the screenshots.  Please give it a try and let me know if it gets rid of the overlapping rows for you.  Thank you.

**Comment by Revadike** [comment]
Seems working. I like it. I suggest you submit a PR.
