### ISSUE TITLE
[BUG] Extension didn't save note because of  over limit.

### ISSUE THREAD

**Issue by naturallucky** [tfedor/AugmentedSteam#1229]
Noteが保存されない

### Expected Behavior
Display that the memo could not be saved

(Currently display only  in browser console)
If possible, I want to know where the capacity has been exceeded 
 ,how much capacity are you using .

### Actual Behavior

silent.

browser console :
`Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.`

### Steps to Reproduce the Problem

  1.  I go to one game page.
  2.  I push note button
  3.  I write some text and  push save button.

Strage location   : Synched/local storage

### Specifications

  - Augmented Steam Version:  2.1.0
  - Browser Version : FF 90.0.2
 
   about:preferences#sync    
 
      同期:オン  
        アドオン  (sync on . include add-on)

**Comment by candela97** [comment]
On this version, there should be a popup dialog that tells you you have exceeded storage limits, and gives you options to switch to other storage methods. Did that not show for you?

**Comment by naturallucky** [comment]
Thanks a lot!

**Comment by Korb** [comment]
Related topic — #1306

**Comment by Korb** [comment]
> On this version, there should be a popup dialog that tells you you have exceeded storage limits, and gives you options to switch to other storage methods. Did that not show for you?

Nope. Augmented Steam 2.2.1, Mozilla Firefox 96.0b3 (64-bit).
