### ISSUE TITLE
[BUG] "Hide Early Access Items" doesn't work

### ISSUE THREAD

**Issue by scowalt** [tfedor/AugmentedSteam#1241]
### Expected Behavior
Early Access items should be filtered from searches when "Hide Early Access Items" is checked

### Actual Behavior
No items are filtered when "Hide Early Access Items" is checked

### Steps to Reproduce the Problem

  1. Go to https://store.steampowered.com/search
  2. Enable "Hide Early Access Items
  3. Observe
![image](https://user-images.githubusercontent.com/1100550/129132000-6110579e-0528-4ab3-8b4e-55bae4ee66c5.png)

In the above example, "Valheim" is an Early Access title, but is still appearing in this search even after toggling the option.

### Specifications

  - Augmented Steam Version: 2.1.0
  - Browser Version : Google Chrome | 92.0.4515.131 (Official Build) (64-bit)
  
 ### Other notes:
 Similar to #1041 , but this seems like a new issue. Maybe a site update?

**Comment by scowalt** [comment]
Weird, it's working on my Mac this morning, it wasn't working on my Windows machine last night...

**Comment by candela97** [comment]
It'll work if the url (specifically the pathname) has a trailing slash https://store.steampowered.com/search/.

This is a different problem and is due to the regexp used for handling different pages, which iirc remains unchanged from ES. Thanks for the report!
