### ISSUE TITLE
[BUG] The Contact page said to use the issue tracker for feature requests.

### ISSUE THREAD

**Issue by MarkitkaM** [tfedor/AugmentedSteam#1244]
Reported on ITAD via #2116

Hello. The Contact page said to use the issue tracker for feature requests.

On the store page under the 'Includes x Steam Achievements' along the right side column it currently shows a link to Astats.

Would it be possible to add our own options similar to how we can on the profile page?
Or would it be possible to add links to SteamHunters & Completionists.me sometime?
Astats is currently the only option there, and it has been down a few days due to hardware problems with no ETA. But, even before this, I thought it could be nice to easily click here to get more information available at these other sites versus just the one. Even if it was just SH as they have links at the top of the profile to quickly get to a few of the other tracking sites.

Thanks for your time and all you do!

**Comment by Revadike** [comment]
You can add custom links. Does that not satisfy your request?

**Comment by MxtOUT** [comment]
As Revadike pointed out, custom links should be accessible in the current public release
