### ISSUE TITLE
[FEATURE REQUEST] Remove all my stuff

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1266]
### Current Behavior (if any)
AS uses my work

### Desired Behavior
Remove all features and work I did for AS
 - NL locale
 - Barter.vg links
 - Global nickname
 - Workshop subscriber
 - Review count filter
 - Export wishlist
 - Support info
 - Favorite emoticons
 - Dev/pub search
 - Context menus
 - Full stats descriptions
 - Media horizontal scrolling
 - Translation percentages
 - Multiple guide languages
 - Workshop sort state
 - Force mp4 videos
 - Back to top button
 - Default community tab
 - Workshop total size
 - Broadcasts remover
 - Steam group manager
 - Reviews sorting
 - Invite friends to group
 - Market history cache
 - Empty wishlist
 - Steamid viewer
 - Quick sell tooltips
 - Group sorting
 - Youtube & Twitch links on app pages
 - My tradeoffers link
 - Global disable custom theme
 - Custom extra links

### Motivation / Use Case for Changing the Behavior
💩

I'm just tired of this shitty behavior... If you're gonna nitpick all the work I do, then I rather just not see you use any of my work at all. Thank you, bye.

**Comment by MxtOUT** [comment]
It's fine that you leave the project but you voluntarily submitted your work to an open source project.
Therefore those features won't be removed by us.
