### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by chrisneyton** [tfedor/AugmentedSteam#127]
View foil badge progress button does not work

**Comment by MxtOUT** [comment]
Fixed with #117

**Comment by KarlCastle** [comment]
Hi! Thank you for this report. However, to find this bug so we can fix it we need some more information.

Which page on steam were you on when this happened?

If you know how to access the dev console, were there any error messages?

The next version (0.9.4) should be coming out later today. Can you check again once it's out and see if you're still having trouble?

**Comment by KarlCastle** [comment]
Confirmed working in 0.9.6
