### ISSUE TITLE
New Feature Suggestion: Download size

### ISSUE THREAD

**Issue by rageknight** [tfedor/AugmentedSteam#134]
Adding a new feature to find out the download size of a game from store front.

**Comment by jellemdekker** [comment]
This information can be retrieved from the `System requirements` section on a Steam store page (which can be inaccurate from time to time with additional DLC's etc.), or using the depots information provided by SteamDB.info. For example: [The Elder Scrolls V: Skyrim](https://steamdb.info/app/72850/depots/).

**Comment by Revadike** [comment]
I hate to say it, but @jellemdekker is right, you can already find this info in system requirements, making this feature essentially redundant. Granted, this information is often inaccurate, but if you want accurate information one has to keep a database of depot information, which I doubt ITAD is willing to do. Therefore, suggesting this feature to the [SteamDB Extension](https://github.com/SteamDatabase/BrowserExtension) instead would be a better idea.

**Comment by Revadike** [comment]
https://github.com/SteamDatabase/BrowserExtension/issues/51
@xpaw mentioned it would even be somehow inaccurate with depot size information, therefore it's best to go with what the system requirements say. And since it's already displayed on the app page, I again suggest to close this issue.
