### ISSUE TITLE
Best price of store I dont have selected

### ISSUE THREAD

**Issue by Josemaloco** [tfedor/AugmentedSteam#135]
Currently, Augmented Steam is [showing the best price](https://i.imgur.com/KuAwBFg.png) of a store I [unchecked in the options](https://i.imgur.com/ahdsmkM.png).

**Comment by MxtOUT** [comment]
I don't think the line that you marked comes from AS.
Have you tried to disable all other extensions and try again?

**Comment by Josemaloco** [comment]
You are right, I checked and its coming from Steam Inventory Helper. 
This issue can be closed.
