### ISSUE TITLE
"Lowest price" and "Best price" inconsistency

### ISSUE THREAD

**Issue by Josemaloco** [tfedor/AugmentedSteam#136]
In cases where Steam shares the same, lowest price with another store, sometimes Augmented Steam shows that external store in the "Best price" spot, even if in "lowest price" it shows Steam.

[https://i.imgur.com/xzAEfXz.png](https://i.imgur.com/xzAEfXz.png)

**Comment by MxtOUT** [comment]
See #135, the bottom line is not from AS

**Comment by Josemaloco** [comment]
As said in #135, this issue should be closed too.
