### ISSUE TITLE
Add option to remove wishlist notes/"add wishlist note" button

### ISSUE THREAD

**Issue by k0zyrev** [tfedor/AugmentedSteam#139]
This arguably useless feature breaks styles, or at least changes the visuals for the items listed on the wishlist page https://i.imgur.com/w7ZoUWg.png

Please add option to disable this feature for those who don't find it useful and, moreover, intrusive.

As a side not, "click to compute stats" should be moved to the bottom of the list for the same reason - breaking the default view of the steam wishlist.

**Comment by k0zyrev** [comment]
The reason for this request is simple without these "add wishlist note" and "click to compute stats" buttons I can see [7 wishlist items ](https://i.imgur.com/NGKIyuZ.png) on my screen, but with them - [just 5](https://i.imgur.com/No1dNhF.png)

**Comment by KarlCastle** [comment]
Confirmed working in 0.9.6 on Chrome 73
