### ISSUE TITLE
Steam in non-English defaults to customizing the front page blank

### ISSUE THREAD

**Issue by KarlCastle** [tfedor/AugmentedSteam#141]
This is the "Lost homepage offers" reported on the extension support page and in the Discord.

The Customizer looks for a key in SyncedStorage that includes the *heading that Steam presents to the user*.

In English, the first block is under a heading `FEATURED & RECOMMENDED` so the key is `show_featuredrecommended` which has an entry in Defaults.

In French (https://store.steampowered.com/?l=french) the same heading is `POPULAIRES ET RECOMMANDÉS` and the key is `show_populairesetrecommands` which **does not have a Default**.

So https://github.com/tfedor/AugmentedSteam/commit/0f35dd75aa4c495fed6e12fbfb238beaf9d8d801 replaced the explicit default `true` with an implicit falsy `undefined` and all of the customizable sections disappeared.

**Comment by KarlCastle** [comment]
Current develop is warning on `addDynamic()` for the home page:
```
store.js:80 Node with textValue CURATORS is not recognized!
addDynamic @ store.js:80
StoreFrontPageClass.customizeHomePage @ store.js:3167
StoreFrontPageClass @ store.js:3061
```

**Comment by MxtOUT** [comment]
Seems like this is caused by `Customizer._textValue`, which doesn't find the text value for this section

**Comment by KarlCastle** [comment]
This is working correctly without the warning.
