### ISSUE TITLE
[FEATURE REQUEST] Option to hide fake discounts displayed on wishlist

### ISSUE THREAD

**Issue by lllIIIlll** [tfedor/AugmentedSteam#1639]
### Current Behavior (if any)

Fake discounts are displayed on wishlist. I assume it's bundle discount?

![1](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/125834307/ce481080-f12c-4f64-98a0-cc77f6e42711)
![2](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/125834307/bdc9476f-166e-4bc8-81b9-6a4e47087af9)

Links to affected games I found
https://store.steampowered.com/app/758690
https://store.steampowered.com/app/237890

### Desired Behavior

Add an option to hide fake discounts displayed on wishlist.

### Motivation / Use Case for Changing the Behavior

Inaccurate and confusing information, and more options are always better.

**Comment by candela97** [comment]
I'd argue it is both logically and legally correct to show the bundle discount if the bundle happens to be best purchase option. This is a nice change even though we still can't add bundles to the wishlist.

**Comment by MxtOUT** [comment]
I agree with @candela97 but can't see how the bundle would be the best purchase option from your screenshots :sweat_smile: 

Using my own wishlist, I couldn't reproduce a situation like is shown in the screenshots.

@IlIRandomIlI, if you can still encounter this problem, please reopen the issue.

**Comment by candela97** [comment]
I think the 12% discount the OP showed had expired already, it's just the wishlist hadn't caught up.

You can see the new behaviour in effect for e.g. `https://store.steampowered.com/app/1085220/Figment_2_Creed_Valley/` if you own Figment 1. Before, the wishlist will only show the discount of the game itself, which is 40%, but now it'll take bundle disounts into consideration.
