### ISSUE TITLE
Friends Activity displaying wrong and Highlighting not working.

### ISSUE THREAD

**Issue by Tudno** [tfedor/AugmentedSteam#164]
Noticed now in v0.9.5 that the friends activity shows achievements weird and the highlighting of owned and wishlist games doesn't seem to be working in the store or on the community.
![bug](https://user-images.githubusercontent.com/14954839/54079179-b42ca900-42cf-11e9-809b-bb854b14f32e.png)

**Comment by Luckz** [comment]
I also don't see highlighting of owned/WL/etc games as working on store search, or store frontpage, only on individual game pages in the title.
Tags do work though, for the same purpose.
(On Firefox)

**Comment by k0zyrev** [comment]
any chance this is going to be fixed any time soon?

**Comment by tfedor** [comment]
We're still waiting for Chrome to approve version 0.9.5, before we can push 0.9.6

**Comment by k0zyrev** [comment]
That's extremely unfortunate, especially considering I'm using Firefox.

**Comment by panda331** [comment]
> We're still waiting for Chrome to approve version 0.9.5, before we can push 0.9.6

so the highlight issue will be fixed in 0.9.6, right?

**Comment by MxtOUT** [comment]
Yes

**Comment by KarlCastle** [comment]
Confirmed working in 0.9.6 on Chrome 73.
