### ISSUE TITLE
Breaks recent updates section

### ISSUE THREAD

**Issue by WildGenius** [tfedor/AugmentedSteam#166]
Even with nothing ticked in options, it replaces recent updates on store pages with reviews.

**Comment by KarlCastle** [comment]
This is a known issue with 0.9.4, the "Recent Update" section defaulted to *hidden*. Clicking the "Customize" button will allow you to turn it back on and the underlying issue is fixed in ef617c4e, which should be in 0.9.5

**Comment by AbteuU** [comment]
Nice, had the same issue now (installed Augmented Steam yesterday) and didn't know the Customize option had a button for re-enabling it.

**Comment by KarlCastle** [comment]
Reset my AS options, reloaded a store page and Recent Updates defaulted to *visible*. Confirmed working in 0.9.6 on Chrome 73.
