### ISSUE TITLE
Market is not showing lowest prices

### ISSUE THREAD

**Issue by grieves13** [tfedor/AugmentedSteam#168]
Community market is not showing lowest prices for all my listing, 
Browser: Chrome 72.0.3626.121

**Comment by MxtOUT** [comment]
Should be fixed with #160

**Comment by KarlCastle** [comment]
Hi @grieves13, 0.9.6 is out now for Chrome. And I can't replicate this on the new version. Are you still affected?

**Comment by grieves13** [comment]
hello @KarlCastle the thing is that at the moment i have only 15 listings on the Market, checked it, all of them loaded, however this issue came out mostly when i had more, so hard to tell if it was fixed, or not... :/
