### ISSUE TITLE
[BUG] Wishlist Notes layout for long titles is lopsided

### ISSUE THREAD

**Issue by KarlCastle** [tfedor/AugmentedSteam#175]
Long app titles, look like this:
<img alt="Wishlist screenshot" src="https://user-images.githubusercontent.com/9707792/54241972-ced27c80-4572-11e9-97d2-defc539e031b.png" width="100" />

The textbox would look less out of place if it was centered, or full width, or if the modal was narrower to force the title to wrap.

**Comment by MxtOUT** [comment]
I personally think that extending the width to the width of the title would be the best solution, but that's probably subjective
