### ISSUE TITLE
Twitch links anywhere on Steam profile page create stream window.

### ISSUE THREAD

**Issue by Galdere** [tfedor/AugmentedSteam#176]
This prevents posting twitch link(s) anywhere on the profile page now, without making a stream window for it. It was understandable to have it automatically do so for any links in the profile text at the top of the page, but to have it open from anywhere on the page now prevents page use for other purposes. Can it please be reverted or better yet have it in the options page to at least be able to turn off or have an input there for which twitch stream to use as well so that profile pages will not have unwanted features activated. Thanks.

**Comment by KarlCastle** [comment]
Hi Galdere,
I wrote #173 after talking to you in Discord :) That PR adds three options, one to turn off all twitch stream boxes, one to turn off twitch stream boxes on your own profile (defaults to off) and one to only look at the profile summary at the top of the page.

**Comment by Galdere** [comment]
Brilliant. Thank you. That covers things perfectly I would think. Cheers

**Comment by Galdere** [comment]
This issue has returned. Please stop assuming twitch link(s) anywhere on your page means you want to have the first link streaming at the top of your profile. I can't find any way to turn this off. Please at least limit it to taking from the personal info box at the top of the page. Thanks.

**Comment by KarlCastle** [comment]
Hi Galdere,
0.9.5 was released for Firefox on the 10th of March. It was *submitted* to Google for the Chrome webstore at the same time and is still in review, pending approval.

The patch I wrote above (#173, from the 15th) will be in the *next* release, it's not available in either of the currently released versions (Chrome 0.9.4 or Firefox 0.9.5).

**Comment by Galdere** [comment]
Hi Karl. Thanks for the clarification. Sorry for the misunderstanding. Cheers.

**Comment by KarlCastle** [comment]
Hi @Galdere,
0.9.6 is out now for Chrome (and 0.9.7 for Firefox is waiting for review), so this should be fixed :)

**Comment by Galdere** [comment]
Thanks @KarlCastle! :)

**Comment by Galdere** [comment]
Hi @KarlCastle 

This issue has just returned.

Thanks

**Comment by Galdere** [comment]
Back again now!

**Comment by Galdere** [comment]
Issue has returned yet again...

**Comment by candela97** [comment]
@Galdere Can you perhaps provide a profile page that you're seeing unwanted Twitch sections appear even with appropriate options selected?

**Comment by Galdere** [comment]
It didn't change back for long, but it was like that for perhaps a day again if I remember right.

Temporary changes seem to be making the issue re-appear sometimes.

My steam profile name is the same as my github name.

Thanks.

**Comment by candela97** [comment]
That's rather strange, since the code surrounding this feature hasn't been touched since March last year.
Just to be sure, is this how you configure your options?
![issue](https://user-images.githubusercontent.com/54083835/101516286-26fb0600-3934-11eb-9d85-3c43cbeb9afd.jpg)

**Comment by Galdere** [comment]
Somehow only the first of those check boxes was selected, despite me choosing both as shown before, as it was me that had requested it! :) 

I wonder how it is only appearing very rarely then.

Sorry for the false report it seems. Thanks.
