### ISSUE TITLE
Early Access banner disables image dropdown list in search results

### ISSUE THREAD

**Issue by kazerniel** [tfedor/AugmentedSteam#186]
Might be easier to explain with a screenshot.

![comparison](https://user-images.githubusercontent.com/5689996/54475758-3bf14680-47ed-11e9-953b-f5c616eae93e.jpg)

I captured each game banner with the cursor over the dropdown arrow. On regular banners in turns blue, and if clicked, shows the Add to you wishlist / Ignore / Preferences dropdown list, but on games with AS's early access banner it stays white, and when clicked it takes the user to the game's store page instead of just showing the dropdown list.

**Comment by MxtOUT** [comment]
Can't replicate it here.
What browser are you using and what's your AS version?

**Comment by kazerniel** [comment]
Waterfox 56.2.8 (x64) and AS 0.9.5

**Comment by KarlCastle** [comment]
Confirmed on Firefox 67. The `span.es_overlay` is square on Chrome and the full width of the image in Firefox. The governing rule has the element `display: block; width: auto; margin: 0;` so... to me the Chrome behaviour seems like a bug?

I think I have a fix, but I want to test it some more.
