### ISSUE TITLE
Community Market Freezes if over 80 pages of Transaction data

### ISSUE THREAD

**Issue by autochesser** [tfedor/AugmentedSteam#191]
I've been using the market for a long time and I have a lot of transactions. I find that the extension causes the community market page to freeze once it hits approximately 70-80 pages of transactions parsed. Is there any potential to update this to prevent this, or even have it so that it will only parse up to certain dates such as Year to date, 2018-2019, etc.

(Maybe even a button to export the data to CSV..... please? :)  )

**Comment by KarlCastle** [comment]
Investigating this, Steam seems to have changed from sending `&count=100` to `&count=10` to fetch the next market history page.

The market history page is also using `https://steamcommunity.com/market/myhistory` only for the first page and following that with `https://steamcommunity.com/market/myhistory/render/?query=&start=10&count=10`

Most of the fields seem to be empty (including `total_count`) if a request isn't perfect.
I needed to set: `Accept: text/javascript, text/html, application/xml, text/xml, */*` to get the `total_count` and even that was unreliable with repeated requests.

Not sure if these are bugs related to load or an "improvement" Valve is doing or a new security feature?

**Comment by KarlCastle** [comment]
tfedor/AugmentedSteam#197 changes how the load market stats button works, so once that is released you'll need to check again if this is still a problem.

Export to CSV is technically possible. There isn't a lot of information available to us as we're scraping the html you see in the "My Market History" tab. The price is there, a date (without a year), the item *name*, the transaction id. What were you hoping to have in the CSV?

**Comment by autochesser** [comment]
Wow forgot to update this, for the CSV, I was hoping that a Listing price, Price that seller gets, and date.

I have transactions I wanted to keep tracks of over time and general profit/loss.

**Comment by MxtOUT** [comment]
Please open a new feature request for the market export
