### ISSUE TITLE
"Hide Install Steam" options not working

### ISSUE THREAD

**Issue by DFNCTSC** [tfedor/AugmentedSteam#193]
The "Install Steam" button next to the "Play Now" button doesn't disappear when the "Hide Install Steam" function is checked.

Worked fine in the previous original version of ES.

No errors in console.

Screenshot of page+console:
![image](https://user-images.githubusercontent.com/6670632/54546529-22710b80-4961-11e9-8475-8cd6a8561629.png)

Edit add: Using the latest version of AS in latest version of Chrome.

**Comment by MxtOUT** [comment]
That's not the button that should be removed with this feature.
This option toggles the visibility of the "Install Steam" button in the header, to the left of your profile icon.
But imo it would be a good idea to also toggle the visibilty of this button with the same option

**Comment by DFNCTSC** [comment]
@MxtOUT Hmm I could've swore I had it hidden before, but good to hear. How would I go about adding a suggestion instead of an "issue"? xD

**Comment by MxtOUT** [comment]
It's fine as it is right now, I noted it in my comment, so it should be tracked :)
