### ISSUE TITLE
'Regional Price Comparison' feature not working

### ISSUE THREAD

**Issue by Orrielel** [tfedor/AugmentedSteam#202]
Will not appear neither with Always or on Mouseover.
Price history still works, along with most other features from what I've noticed.

Tried clearing cache, and reset settings.
Running on Firefox Dev Edition 67.0b3

(Works for me in Chrome 73)

**Comment by KarlCastle** [comment]
It's working for me on FF Dev Edition 67.0b4.

What is your Steam store currency and which currencies do you have selected for the comparison?

If you know how to check, are there any errors in the browser console?

**Comment by Orrielel** [comment]
No errors in the console, using Norwegian (NOK) currency.

![List](https://i.imgur.com/YUBhcCA.png)

**Comment by MxtOUT** [comment]
Is it working?
