### ISSUE TITLE
Add Barter.vg user links to profiles on Steam Community, game page links to Store app pages

### ISSUE THREAD

**Issue by Luckz** [tfedor/AugmentedSteam#207]
Barter.vg

URL: `barter.vg/steam/[ID]`
_[ID] being id64; trailing slash optional_

~icon `barter.vg/favicon.ico`~
icon `bartervg.com/imgs/ico/barter/light-blue-32x32.png`

If the user is not a Barter member, it shows a provisional profile and tries to load their wishlist:
[https://barter.vg/steam/76561197996986999](https://barter.vg/steam/76561197996986999)

Otherwise, it redirects to their user page.

PR for Enhanced steam from long ago:
https://github.com/jshackles/Enhanced_Steam/pull/1352

***

As far as linking to  games from Store pages goes - https://barter.vg/steam/app/1250 - that works great for apps, only for subs that were actually bundled - https://barter.vg/steam/sub/314696/ - , and not at all for Store bundles (there is no `/bundle/`).
The trailing slash is again optional.

=> adding Barter links to the Steam Store pages mostly makes sense on `https://store.steampowered.com/app/.../` pages, so games and DLC

**Comment by Killogy** [comment]
@Luckz you already can add barter user link on steam profiles pages.

Community -> Show profile links to > Press custom button, then use this...

Name: Barter
URL: barter.vg/steam/
Icon: bartervg.com/imgs/ico/barter/favicon-16x16.png

**Comment by Luckz** [comment]
Certainly, but only one (which is a small technical hurdle) and completionist.me was just added to the defaults (https://github.com/tfedor/AugmentedSteam/issues/177 https://github.com/tfedor/AugmentedSteam/pull/182)

**Comment by Killogy** [comment]
@Luckz, true, will be nice if we can add more custom links.

**Comment by Luckz** [comment]
https://bartervg.com/imgs/ico/barter/light-blue-32x32.png looks good both in coloured and grayscale icon mode.

**Comment by tfedor** [comment]
Implemented by adding an option to add more custom links.

**Comment by Luckz** [comment]
That only allows people to add links to the community profiles, not links to the Steam Store. The commit to support completionist.me presumably exists for the same reason.

**Comment by Revadike** [comment]
Please reopen for additional links. I second this request!
