### ISSUE TITLE
Augmented Steam makes the Steam website take much longer to load.

### ISSUE THREAD

**Issue by aaronth07** [tfedor/AugmentedSteam#212]
Without Augmented Steam, the website loads in less than a second. With Augmented Steam, the website takes 6+ seconds to load. 

I know that it is only Augmented Steam that is affecting this load time as Augmented Steam is the only extension enabled/disabled when testing.

**Comment by KarlCastle** [comment]
Are there particular pages you're seeing this behaviour? Or some pages that are affected more than others?

Which browser and version are you using?

For me, with Chrome 73 and the 0.9.4 version of the extension, the Steam front page loads in 1800ms with the extension loaded and 1600ms with it disabled.

Some parts of a page that Augmented Steam adds may take longer to appear (price comparisons in particular) as your browser is waiting for multiple responses from other servers on the internet.

**Comment by aaronth07** [comment]
Store pages seem to take the longest, I just recorded the time for one store page and it took 18 seconds to load. Without the extension it took 1.5 seconds.

I'm on the latest version of Chrome and the extension. And I never had this problem with Enhanced Steam, so it must be something that Augmented Steam added newly.

**Comment by RathaWynter** [comment]
@aaronth07 does this problem go away if you clear your steam-related cookies? I have experienced an issue in Firefox 55.0.3 where one of the steam-related cookies seems to be causing webpages to take 15-30 seconds to load. I was fairly sure it was cookie related, and not Enhanced / Augmented Steam related at the time, but cannot reproduce it on demand to re-test and be sure. Something worth trying to test if no one else can reproduce the problem.

Augmented Steam 0.9.5 in Chrome 73.0.3683.103 (Official Build) (64-bit) on Windows 7 x64 seems to load store pages pretty quickly for me. Roughly two seconds.

**Comment by aaronth07** [comment]
I guess the update fixed it, because I no longer have the problem.
