### ISSUE TITLE
Owned game not outligned (BL GOTY Enchanced)

### ISSUE THREAD

**Issue by jullebarge** [tfedor/AugmentedSteam#213]
Hi,

I got Borderlands GOTY Enchanced but it doesn't outline this game on the Activity page for example. All others games I have are correctly outlined.
If I go to the store page of BL GOTY, it show me that I have this game in my library.
![steam](https://user-images.githubusercontent.com/11553167/55625886-54300200-57aa-11e9-8291-4e76d7b74c71.PNG)

**Comment by jullebarge** [comment]
Proof that I own the game:
![steam2](https://user-images.githubusercontent.com/11553167/55625996-a2dd9c00-57aa-11e9-96a4-63013c283335.PNG)

**Comment by KarlCastle** [comment]
Augmented Steam uses the Game's "appid" to check whether you own it. If you hover over the link in your activity list, does it have the same appid as the URL when you're looking at the store page?

For me, these are `https://steamcommunity.com/app/729040` and `https://store.steampowered.com/app/729040`

**Comment by jullebarge** [comment]
Yes it's the same appid in activity and on the store page (729040)

**Comment by MxtOUT** [comment]
Did you immediately look at your activity page after buying the game?
Because the Dynamic Store only updates every 15 minutes I guess, so it should be resolved right now

**Comment by jullebarge** [comment]
Yes it seems fixed now, but I found the bug the next day after buying the game, so it was not a refresh problem

**Comment by tfedor** [comment]
Hmm, so is this still an issue or was it fixed? Can we close it?

**Comment by jullebarge** [comment]
Yes it's OK now, you can close this issue
