### ISSUE TITLE
Use SteamDB instead of Steam Charts for player counts

### ISSUE THREAD

**Issue by 07416** [tfedor/AugmentedSteam#215]
SteamDB's data extends further than Steam Charts', for example [SC reports misleading numbers (peak) for Call of Duty: Modern Warfare 2](http://steamcharts.com/app/10180) when [SteamDB has tracked the game since the launch](https://steamdb.info/app/10180/graphs/).

**Comment by jellemdekker** [comment]
SteamDB could provide useful for implementing the functionality requested in issue #134.

**Comment by Tristar7** [comment]
SteamDB has their own extension which provides that integration on the store page as well (the play data)

**Comment by MxtOUT** [comment]
I am not sure if we would get an API key for SteamDB, as their extension is more or less a direct competitor of AS

**Comment by tfedor** [comment]
ITAD tracks player counts as well, so we will switch to that in the future.

**Comment by Tristar7** [comment]
> ITAD tracks player counts as well

Though not further back than SteamCharts neither.

Does it track data on its own or is it relying on the other website considering both have an equal amount of data for the game in question.

**Comment by tfedor** [comment]
We track it on our own, and it's true we don't have that long historical data.
