### ISSUE TITLE
Highlight colors missing from games

### ISSUE THREAD

**Issue by MakoSipper** [tfedor/AugmentedSteam#220]
![chrome_2019-04-10_14-13-40](https://user-images.githubusercontent.com/16372995/55899384-098ffa80-5b9b-11e9-91af-0762b492bbf2.png)
Colors are correctly set in the options menu, but they seem to be transparent, regardless of type (owned, wishlisted, ignored...)

Games that shouldn't be highlighted don't show that border (as intended)

**Comment by MxtOUT** [comment]
Fixed by #165 and will be included in the next release

**Comment by ozancakar20** [comment]
Same here, waiting for fix.
