### ISSUE TITLE
Not Working at All

### ISSUE THREAD

**Issue by sarcinelli86** [tfedor/AugmentedSteam#221]
It's not loading and when I enter the preferences it's all blank. I can't click anything.

![augsteam](https://user-images.githubusercontent.com/34447967/55914897-afa12c00-5bbe-11e9-8eb2-3d44e0573832.PNG)

Edit: It's returning the following error: 

chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/core.js:605 Uncaught SyntaxError: Unexpected token =
store.js:3215 Uncaught (in promise) ReferenceError: SyncedStorage is not defined
    at store.js:3215
    at store.js:3281

**Comment by MxtOUT** [comment]
Are you using Opera?

**Comment by sarcinelli86** [comment]
Chrome 64bits on Windows 10 64bits 1809.

**Comment by HAL6000** [comment]
Same here, not loading at all. Opera here.

**Comment by MxtOUT** [comment]
@sarcinelli86 @HAL6000 Ok, I think that is already fixed on the develop branch, but to temporarily fix it you could try to replace line 605 in core.js with
`    static escape(str) {`
You should find this under:

- Chrome: C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default\Extensions\dnhpnfgdlenaccegplpojghhmaamnnfp\0.9.5_0\js\
- Opera: %appdata%\Opera Software\Opera Stable\Extensions\dnhpnfgdlenaccegplpojghhmaamnnfp\0.9.5_0\js\

**Comment by sarcinelli86** [comment]
No dice...
Chrome disables the extension after editing the line.

![corrupted extension](https://user-images.githubusercontent.com/34447967/56072951-2b43da00-5d73-11e9-96a7-c3dd0f58c4c5.png)

**Comment by Luckz** [comment]
My Firefox version stopped loading on Store & Community, is this the same issue?

**Comment by MxtOUT** [comment]
@sarcinelli86 Could you try the following steps?

1. Download the [current development state](https://github.com/tfedor/AugmentedSteam/archive/develop.zip)
2. Unzip the file somewhere
3. Copy config.js from your Web Store installation (C:\Users<user>\AppData\Local\Google\Chrome\User Data\Default\Extensions\dnhpnfgdlenaccegplpojghhmaamnnfp\<version>\js\) into <unzippedFolder>\AugmentedSteam-develop\js\
3. Enable developer mode under the [extensions page](chrome://extensions/) in the top right corner
4. Click "Load unpacked" in the top left corner
5. Select the previously unzipped folder

@Luckz Do you have the same error message as @sarcinelli86 ?

**Comment by sarcinelli86** [comment]
Ok, that solved the problem. Thanks!

**Comment by sarcinelli86** [comment]
It's all working fine now in version 9.6, thanks!
