### ISSUE TITLE
Curator recommendation -- small aesthetic issue

### ISSUE THREAD

**Issue by MakoSipper** [tfedor/AugmentedSteam#222]
As you can see, on curator recommendations, there's this ~~ugly~~ little box to the right of the text:
![chrome_2019-04-10_20-01-42](https://user-images.githubusercontent.com/16372995/55919270-a4a0c880-5bcb-11e9-9ad4-a883ee86a04f.png)
It seems that if you change this:
```
.blotter_block .vote_header {
    height: 44px;
    margin-bottom: 13px;
    margin-top: 4px;
}
```
to this:
```
.blotter_block .vote_header, .vote_header .es_highlighted {
    height: 44px;
    margin-bottom: 13px;
    margin-top: 4px;
    padding: 0!important;
}
```
then this issue is solved:
![chrome_2019-04-10_20-04-56](https://user-images.githubusercontent.com/16372995/55919354-fa757080-5bcb-11e9-81d2-055c97d52b77.png)

I'm a novice (at best) at programming, so I really don't know how or if this is feasible for you guys, or easy to change, but it would be awesome if you could implement it so it can look better.

BR and TIA

**Comment by MxtOUT** [comment]
![curatorFixed](https://user-images.githubusercontent.com/14999077/56079428-94b7fd00-5df4-11e9-82b4-572a11c54221.png)
Fixed with #217
