### ISSUE TITLE
ES code contributor badge missing

### ISSUE THREAD

**Issue by seeeeew** [tfedor/AugmentedSteam#229]
The badge for people who contributed code to Enhanced Steam in the past isn't showing up in profiles because https://es.isthereanydeal.com/img/badges/es_code.png doesn't exist.

You can check [my steam profile](https://steamcommunity.com/id/seeeeew/) for reference.

**Comment by MxtOUT** [comment]
That's a task for @tfedor

**Comment by tfedor** [comment]
Fixed
