### ISSUE TITLE
[Feature Request] Will you consider adding "Steam Web Integration" into AS?

### ISSUE THREAD

**Issue by Black3ird** [tfedor/AugmentedSteam#238]
Dear Sir,

It was great of you to continue and **improve** what jshackles did with Enhanced Steam so that we can still be "Informed Customers" thanks to ITAD+AS combo as well as other tools such as SteamDB Extension and https://greasyfork.org/en/scripts/26273-steam-web-integration (which recently moved to GitHub) like UserScripts.

I would like to urge you to try that UserScript for yourself to see that it provides _Vital Information_ as much as above combo does so it became a "Must Install" for me along with your artworks. As a side note, it uses Barter.VG as an alternative to ITAD for bundling information (mostly same, rarely different results). Unlike AS, UserScript provides **Icons** over Steam URL entries _everywhere_ about if game:  

- Has Cards
- Has Been Bundled  
- Is Wishlisted  
- Is Ignored  
- Is Owned  
- Is Removed  

relying on https://store.steampowered.com/dynamicstore/userdata/ stored locally and updated to check the hits in visited sites so that Consumer knows such data "without" having to go back to the Store Page of the game on Steam.

I know it's uncertain and far fetched to ask such to use someone else's code in your work (also jshackles) but both Author Revadike (formerly RoyalGamer06) is a good guy who take suggestions at SteamGifts and has lots of other useful scripts on GreasyFork while put his code GitHub to be available for everyone else. So if you're to contact to him, I'm pretty sure he could be interested in such _"Merge"_ of his baby with Augmented Steam which could be more beneficial to all Steam Consumers out there knowing one or another unlike few using _both_ like me.

So please install the UserScript (preferably on an empty Profile on your browser for no clashes as a start) and visit everywhere else like SteamGifts, Reddit GameDeals or any other source you get Steam games information about to see it in action, especially when it comes to deciding buying a bundle or not. If you ever like it, I'm pretty sure you and him will come to an beneficial conclusion for all parties involved including yourself, him and we consumers.

Thanks for your time.

Best Regards.

**Comment by MxtOUT** [comment]
Hm, I'm not in the position to decide this but imo Steam Web Integration wouldn't fit at all into AS.
This is due to the different use cases of the programs:
AS is meant to only be used on steamcommunity.com and store.steampowered.com while Steam Web Integration adds links to every site.
Additional permissions would also be required, which I know @tfedor is not a fan of.
Another point would be the huge amount of work that comes with the integration of another codebase (code style, aesthetic adjustion, ...)

**Comment by KarlCastle** [comment]
Hi Black3ird,

Steam Web Integration looks to be a pretty neat userscript. My *opinion* though is that it does it's thing very well and it's thing is a slightly different thing from Augmented Steam's thing. They also seem to coexist happily so the only benefit is a slightly simpler install process?

Browser Extensions/Addons have a *lot* more capabilities than TamperMonkey/GreaseMonkey scripts and are relatively opaque when you're installing them so Google and Mozilla go out of there way to try and protect users.  (Hence the month long delay on releasing 0.9.5 for Chrome.) Asking for a potentially dangerous permission (like "Can read and alter your data on every website you visit.") extends the review process.

(Side note, the GreasyFork link doesn't host the script anymore. It redirects you to the GitHub project, https://github.com/revadike/SteamWebIntegration/ in a way that GitHub aren't a fan of. /raw/ URLs aren't intended to be a CDN. That's what GitHub Pages and jsdelivr are for.)

**Comment by Revadike** [comment]
God, I wish I was tagged for this. I only found this by accident, by looking for something else.
That said, I'd have loved to integrate it into AS, but sadly there are a few problems with this.
Like mentioned before, it requires AS to run on every web page you visit to check for links, which is fine by me, but I doubt @tfedor would approve...
Second challenge would be the acquiring of data. I doubt AS would implement all those API's directly. Instead they would need to provide that data themselves via their API, which can be hard to maintain.
