### ISSUE TITLE
Detach fork from original repository

### ISSUE THREAD

**Issue by seeeeew** [tfedor/AugmentedSteam#249]
I think this fork should be detached from the original repository ([jshackles/Enhanced_Steam](https://github.com/jshackles/Enhanced_Steam)) and turned into a standalone repo.

Detaching the fork would
* prevent accidental PRs to the original repo,
* allow users to fork this fork/repo while also keeping a separate fork of the original repo and
* let contributions made to this repo show up in user profiles.

Since the original project reached EOL, this fork will probably never be merged, which is why I see no reason to keep the fork status.

Unfortunately the only way to detach a fork is by contacting [GitHub Support](https://github.com/contact), but at least it's officially supported, so it should be relatively straight-forward.

Relevant excerpt from [GitHub Help](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork):
> * To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact) or [GitHub Premium Support](https://premium.githubsupport.com/). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "[About forks](https://help.github.com/en/articles/about-forks/)."

**Comment by tfedor** [comment]
We're detached now :)
