### ISSUE TITLE
Some wishlist notes from the previous repo

### ISSUE THREAD

**Issue by chrisblakley** [tfedor/AugmentedSteam#25]
After Steam updated the UI for the Wishlist page, the wishlist notes (which personally was my most-used feature of ES) stopped working.

I'd like to request further development of this feature for the new fork. jshackles hinted that it could be working soon prior to the EOL of the project.

Here are references to some of the wishlist notes issues from the previous repo I think are important. Particularly getting them working again as well as being able to export/import the notes specifically. Currently they are only stored in LocalStorage which unfortunately aren't as permanent as I would hope (having lost all of my notes twice now). Maybe they could be stored in JSON or IndexedDB for easier access?

- https://github.com/jshackles/Enhanced_Steam/issues/1552
- https://github.com/jshackles/Enhanced_Steam/issues/1356
- https://github.com/jshackles/Enhanced_Steam/issues/1238

Many thanks for taking on the project! I was so happy to see the news!

**Comment by tfedor** [comment]
Just a note - notes should work in our version, I'll look at the requested features after 1.0

**Comment by chrisblakley** [comment]
One other feature request I'd like to add for the future would be the ability to see/modify notes when viewing a game page too.

**Comment by Revadike** [comment]
The exporting/importing request can be added to this requested feature: https://github.com/tfedor/AugmentedSteam/issues/591

**Comment by MxtOUT** [comment]
All of the requests should be implemented, although there is currently an upper limit for the amount of user notes (see #848)
