### ISSUE TITLE
Chrome Issues

### ISSUE THREAD

**Issue by BigBodZod** [tfedor/AugmentedSteam#256]
Using Chrome Version 74.0.3729.108 (Official Build) (64-bit), the extension is no longer working on my MAIN Steam Account.

It could be related to the fact I have a very large Steam Library and a very large amount of titles on my Steam wishlist.

I have over 37000 titles on my wishlist.

I have over 13000 games in my library with over 10000 DLC items,

I just installed Augmented Steam in Firefox and it's working but also has some other issues like freezing on the Badge Booster Pack creation page, again could be related to my Steam library size.

You can try to review my Wishlist if you want to but it will not load properly due to the count size, even in the Steam client.

**Comment by MxtOUT** [comment]
What do you mean by not working?
Has this resolved now?

**Comment by BigBodZod** [comment]
Yes all appears to be working once again, I'm sure the recent update/updates to the plugin have resolved the issue as it is now working under both Chrome and Firefox.
