### ISSUE TITLE
Add Youtube and Twitch links on the app page

### ISSUE THREAD

**Issue by tfedor** [tfedor/AugmentedSteam#257]
> Please consider adding Youtube & Twitch links on the Steam page for the games, another extension did this but they started doing some dodgy stuff with the permissions. e.g: https://i.imgur.com/pdnoufq.png

**Comment by infekSK** [comment]
You've added YT to the latest update, while this is cool, can you perhaps have another YT/Twitch button that simply searches the game name on either platform? I don't think many people are going to want to watch whatever videos it defaults to with the YT tab

**Comment by infekSK** [comment]
Progress on this front is okay but I would still implore you to simply add a Twitch and YT button link that just searches the game. The picture in the OP is exactly what it needs to be like, relying on whatever algorithm you're using to find what you're after isn't working great.

**Comment by MxtOUT** [comment]
Tbh, I think it's working pretty well right now and I've never got inappropriate results with the latest update.

The reason I hesitated to add the links is that I couldn't find a good way to search for a game on Twitch

**Comment by infekSK** [comment]
Twitch links won't work with "https://www.twitch.tv/directory/game/xxxx"?

At least the previous extension I used didn't have any special strings

**Comment by MxtOUT** [comment]
You need to have the exact name of the game on Twitch

**Comment by infekSK** [comment]
So you're saying you can't even have it search the title from steam on twitch? The majority of games would work

**Comment by MxtOUT** [comment]
I don't really consider it a search if you have to provide the exact name.
But I'd appreciate if you could show me a way how to do it.
I vaguely recall that you'd need to have an API key to do "real" searches

**Comment by infekSK** [comment]
I've been looking through their source code but I haven't found anything that looks like it yet. If you have a look at this extensions: https://chrome.google.com/webstore/detail/steam-inventory-helper/cmeakgjggjdlcpncigglobpjbkabhmjl it does what I'm trying to convey.

**Comment by Revadike** [comment]
I looked at their source code. This is how they do it:
```js
"https://www.twitch.tv/directory/game/" + encodeURIComponent($J(".apphub_AppName").text().replace(/(\u2122)/g,"").replace(/(\xAE)/g,""));
```
While works in many cases, it is not always correct.

**Comment by infekSK** [comment]
Thanks for finding the part, I wasn't able to find anything (zero coding experience; I was just using my own logic). 

Personally I never had any issues with it, I always got the exact game result so I'm not sure in which ways it wouldn't be correct.

**Comment by Revadike** [comment]
> Thanks for finding the part, I wasn't able to find anything (zero coding experience; I was just using my own logic).
> 
> Personally I never had any issues with it, I always got the exact game result so I'm not sure in which ways it wouldn't be correct.

what about unknown games?

**Comment by infekSK** [comment]
What's an unknown game? The indie titles I tried all worked, but it's not like I went out of my way to see if a shovelware game with 0 reviews had a Twitch page. 

I'd still prefer this system over the current system, gives the user more choice than being locked into a video that could perhaps be a separate game altogether. A button with the query for YT and Twitch would really be great but it doesn't seem like that's the direction you guys want to go.

**Comment by Revadike** [comment]
> shovelware game with 0 reviews

yes, I meant those.

> A button with the query for YT and Twitch would really be great but it doesn't seem like that's the direction you guys want to go.

I actually think they are great too. No reason to not add, if you just make them optional and disabled by default.

**Comment by infekSK** [comment]
Isn't the Twitch game list based on Giant Bomb's wiki api? So if a random game doesn't have a twitch link then it's probably not on the wiki?

Yep, I'd be fine with a toggle option as well!
