### ISSUE TITLE
Toggling hide games feature for certain pages

### ISSUE THREAD

**Issue by tfedor** [tfedor/AugmentedSteam#258]
I'm not sure what would be the best way to go about this. Here's the request from the user:

> There's something I realised, which might be useful feedback: hiding owned apps also afftects the page https://store.steampowered.com/updated/myapps/, which is a page dedicated to info about owned apps. Is it possible to whitelist certain individual URLs from the "hide" script?
>
> I don't know if this would be best as a behind-the-scenes change, or a "unhide owned games where it makes sense" checkbox, or a more flexible "Except for..." option in the Store>Hide section of the Options menu, but if there is any way to implement it I think it could improve UX at some points.

**Comment by AbsenceJam** [comment]
Could you at least separate these hide "Owned" and "Ignored" options from the "Hide" filters in search results so checking hide in the results doesn't enable these options?

That's unexpected and unwanted behaviour.

**Comment by MxtOUT** [comment]
I'm actually currently working on something similar, which also unbinds the hide option from the filters on the search page

**Comment by MxtOUT** [comment]
Also imo the hide functionality should be exclusive to the search page and the options for the hiding should get removed
