### ISSUE TITLE
Brave Browser intermittent behavior on Wishlist and Store Page

### ISSUE THREAD

**Issue by rosswd** [tfedor/AugmentedSteam#259]
Brave Version 0.63.48 Chromium: 74.0.3729.108
Augmented Steam (vers: 0.9.6)
Extensions: 1Password, Chromoji, The Camelizer

Hover doesn't highlight prices on the wishlist page or work on the Store page but it's behavior seems random. Sometimes both the Store page and wishlist work, sometimes not. On the store page the error shown by AS:

```
One or more requests failed:
+ An error occurred in the background context.storepagedata
+ An error occurred in the background context.prices
```

Browser Console log (store page):

![Store Page](https://i.imgur.com/kigxy5x.png)

The errors that trigger as I hover on the Wishlist page and don't get results is: 

```
Uncaught (in promise) An error occurred in the background context.prices
GET https://steamcommunity.com/actions/GetNotificationCounts 401 (Unauthorized)
```

*Apologies if this is a duplicate bug but searches for context, hover, wishlist,  background error turned up empty.*

**Comment by tfedor** [comment]
Are you logged in on steamcommunity.com?

**Comment by rosswd** [comment]
I am logged in to steamcommunity.com yes.

**Comment by MxtOUT** [comment]
I guess that problem is on the server side?

**Comment by MxtOUT** [comment]
Refer to #271
