### ISSUE TITLE
"Current Lowest Price" not showing the actual lowest price

### ISSUE THREAD

**Issue by Eiion** [tfedor/AugmentedSteam#264]
There's an issue with "Current Lowest Price" on game's badge pages:
The prices shown are too low and do not represent the actual lowest price on the market for all games.
Sometimes just one Cent, other times the displayed price differs even more than that. Reloading the badge page doesn't help.

**Comment by JanPokorny** [comment]
Here's a picture showing a discrepancy between the shown "lowest price" and the "lowest price" on IsThereAnyDeal for the game Vampyr. (The IsThereAnyDeal one is correct.)

![obrazek](https://user-images.githubusercontent.com/4580066/57518868-0bdda400-7355-11e9-92c2-b35dc261f1eb.png)

**Comment by Eiion** [comment]
Although my issue was regarding trading card prices, for game prices the issue seems to apply as well.

**Comment by MxtOUT** [comment]
Seems to be the same problem as in #274

**Comment by tfedor** [comment]
I believe the problem here is that you have different region selected on ITAD than on Steam.
