### ISSUE TITLE
[Suggestion] link to steamcardexchange on Shop pages

### ISSUE THREAD

**Issue by Eiion** [tfedor/AugmentedSteam#265]
I'd like to suggest to add a link to the game's showcase page on www.steamcardexchange.net on Steam store pages (if the game has cards).
The extension could alter the "Steam Trading Cards"-link (https://store.steampowered.com/search/?category2=29&snr=1_5_9__423) to the game's showcase page on SCE.

**Comment by MxtOUT** [comment]
This already exists if you enable it under Store > Options for information from 3rd-party sites > 
Show SteamCardExchange links on store pages

**Comment by Eiion** [comment]
Alright, thanks.
