### ISSUE TITLE
[Suggestion] Change workshop home page sorting rate to by playtime

### ISSUE THREAD

**Issue by rcmero** [tfedor/AugmentedSteam#267]
First of all, I apologise for the inherent spam, this is technically a different issue. I have also suggested it on the old Enhanced Steam project but I got no reply.

This is how games on the Workshop home page are displayed currently. If I want to find the Workshop for one of the games I am actively playing I first have to go through two, sometimes three, pages of random games that have recently added Workshop support and that I don't care about.

![image](https://user-images.githubusercontent.com/5708421/57448548-8e7d3b00-7251-11e9-950b-0fb93d3844a6.png)

My suggestion is that Augmented Steam should automatically change the sorting of these games to by playtime, which makes it much more likely for me to find the game I'm looking for right on the first page.

![image](https://user-images.githubusercontent.com/5708421/57448712-f5025900-7251-11e9-8bfc-bbcddecf07bf.png)

**Comment by MxtOUT** [comment]
Tbh I don't see the need for this here because you're just one click away from the function that you want

**Comment by rcmero** [comment]
That may be so, and this just may be something that only annoys me
specifically, but that is why this is just a suggestion.

**Comment by MxtOUT** [comment]
I could imagine to save the last state somewhere, so that it will select the sort option you last used
