### ISSUE TITLE
Extension completely fails to load when some server requests do not respond

### ISSUE THREAD

**Issue by Tristar7** [tfedor/AugmentedSteam#271]
During certain time-frames when apparently the server is down or unable to handle requests the extension **completely** stops working on any browser. 
Checking through the errors reveals that some server requests fail which leads to unhandled exceptions that make the full extension crash and not load at all.

Any server-/online-dependent code should be completely separated or its exceptions of the server not responding properly handled so the extension runs at least.

The offline functionality should not be affected like this by that and is supposed to always run and load immediately without waiting for the server side responses.

Also, I have never observed this kind of behavior on Enhanced Steam and ironically the old extensions still works during these outages.

**Comment by MxtOUT** [comment]
The reason why ES works during the outages is that AS uses it's own API server.
But I agree, the extension should work with less information available instead of not working at all

**Comment by USERNAME-ALREADY-TAKENN** [comment]
Yeah, addon stopped working at all for me. But I'm not sure if it's because of what you said. How do I check that?

**Comment by MxtOUT** [comment]
Anyone still experiencing these outages?
Because I do not
