### ISSUE TITLE
No longer getting ITAD on game pages

### ISSUE THREAD

**Issue by infekSK** [tfedor/AugmentedSteam#277]
Has come out of nowhere, deleted cookies on both ITAD and Steam and nothing's fixed.

**Comment by USERNAME-ALREADY-TAKENN** [comment]
Was same for me, but it magically fixed itself

**Comment by MxtOUT** [comment]
@infekSK Do you see any errors in the browser console (F12)?

**Comment by infekSK** [comment]
The errors seem to only relate to being unable to access a certain font all from "https://steamstore-a.akamaihd.net/public/shared/fonts/*"

There's also this: 

Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vYW5hbHl0aWNzL2Rldmd1aWRlcy9jb2xsZWN0aW9uL2FuYWx5dGljc2pzLwoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07Cgl2YXIgbm9vcG51bGxmbiA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiBudWxsOwoJfTsKCS8vCgl2YXIgVHJhY2tlciA9IGZ1bmN0aW9uKCkgewoJCTsKCX07Cgl2YXIgcCA9IFRyYWNrZXIucHJvdG90eXBlOwoJcC5nZXQgPSBub29wZm47CglwLnNldCA9IG5vb3BmbjsKCXAuc2VuZCA9IG5vb3BmbjsKCS8vCgl2YXIgdyA9IHdpbmRvdywKCQlnYU5hbWUgPSB3Lkdvb2dsZUFuYWx5dGljc09iamVjdCB8fCAn...0gY2F0Y2ggKGV4KSB7CgkJfQoJfTsKCWdhLmNyZWF0ZSA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiBuZXcgVHJhY2tlcigpOwoJfTsKCWdhLmdldEJ5TmFtZSA9IG5vb3BudWxsZm47CglnYS5nZXRBbGwgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gW107Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd1tnYU5hbWVdID0gZ2E7CgkvLyBodHRwczovL2dpdGh1Yi5jb20vZ29yaGlsbC91QmxvY2svaXNzdWVzLzMwNzUKCXZhciBkbCA9IHcuZGF0YUxheWVyOwoJaWYgKCBkbCBpbnN0YW5jZW9mIE9iamVjdCAmJiBkbC5oaWRlIGluc3RhbmNlb2YgT2JqZWN0ICYmIHR5cGVvZiBkbC5oaWRlLmVuZCA9PT0gJ2Z1bmN0aW9uJyApIHsKCQlkbC5oaWRlLmVuZCgpOwoJfQp9KSgpOw==' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamstore-a.akamaihd.net/ https://steamstore-a.akamaihd.net/ *.google-analytics.com https://www.gstatic.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by MxtOUT** [comment]
That's not related to AS.
Could you open the background page of AS (go to chrome://extensions/, enable Developer Mode and click on "Inspect views **background page**") and check for any errors there (you should reload the store page where ITAD isn't working though)?

**Comment by infekSK** [comment]
background.js:698 
SyntaxError: Unexpected token U in JSON at position 0 "rates"
﻿
​That's all I'm getting

**Comment by MxtOUT** [comment]
Are you actually seeing anything AS-related on the page at all?

**Comment by infekSK** [comment]
[dnhpnfgdlenaccegplpojghhmaamnnfp-1558549651049.log](https://github.com/tfedor/AugmentedSteam/files/3208851/dnhpnfgdlenaccegplpojghhmaamnnfp-1558549651049.log)

I had that briefly but I don't know if it's related. I cleared console and refreshed and it didn't come back.

**Comment by MxtOUT** [comment]
Ok, but do you see any other features of AS on the page (e.g. OpenCritic score, AStats link, ...)?

**Comment by infekSK** [comment]
Oh sorry I misunderstood you. No there's no features of AS, only steamdb features but that's from their extension. I don't even get the assortment of links on my or anyone else's profile.
