### ISSUE TITLE
"Regional Price Comparison" doesn't use user's main price as base

### ISSUE THREAD

**Issue by fireattack** [tfedor/AugmentedSteam#278]
![image](https://user-images.githubusercontent.com/4130991/58154200-afbd2e80-7c36-11e9-9bd9-2c511f22c08e.png)

It should use user's main currency/price (CNY 268) as base when doing percentage comparison, instead of fixing on US/USD one.

**Comment by MxtOUT** [comment]
Have you explicitly set Japan as a comparison country in the AS settings?
If not, could you try and type in `User.getCountry()` in your browser console and report the returned value?
It could also be that you explicitly set the price to be in USD under Price > Price History Information > View in

**Comment by fireattack** [comment]
Note: my main currency is CNY (China), not JPY (Japan).

1. I didn't have China an a comparison before. I added it now, makes no difference:

![image](https://user-images.githubusercontent.com/4130991/58213800-11be7800-7cb9-11e9-80cc-d93653c718e8.png)

2. It says `Uncaught ReferenceError: User is not defined`.

3. I set it to "auto-detect".

**Comment by MxtOUT** [comment]
To 2: Are you executing that in a window where AS is active (preferrably on an ap page)?

It seems like AS couldn't detect your country

**Comment by fireattack** [comment]
Yeah, I tried it on https://store.steampowered.com/app/925100/The_Elder_Scrolls_Online__Elsweyr/ and https://store.steampowered.com/app/779340/Total_War_THREE_KINGDOMS/

**Comment by MxtOUT** [comment]
My bad, sorry, you need to set a breakpoint at store.js:3184 and then try again

**Comment by fireattack** [comment]
User.getCountry() returns "US"

**Comment by fireattack** [comment]
OK, so I checked the code for that function (https://github.com/tfedor/AugmentedSteam/blob/ab264b369fe9b9703e0eedbf83b9fef2733fcb40/js/content/common.js#L415).

It looks like it will check the LocalStorage first for `userCountry`, then check cookie of `steamCountry`.

In my case, I have no LocalStorage items at all; and my `steamCountry` is indeed something started with "US".

I'm not sure why, my account is indeed region "China":

![image](https://user-images.githubusercontent.com/4130991/58234614-91256900-7d04-11e9-8ed6-4f89e5ac7872.png)

But I do live in the US currently.

Maybe Steam use IP and/or preferred display language to set that `steamCountry` option instead of user region?

Anyway, I went up to clean all my cookie and re-logged in. This time, it successfully generate LocalStorage item of `userCountry` and set it to `CN`. My  `steamCountry` cookie is still US, though.

Above is my discovery. I see some improvement can be made (like find a more reliable to get user's region. Maybe just use the currency? After all my currency are all CNY.), but if it's worth the effort I will leave it to devs. Thanks and feel free to work on or close this issue.

**Comment by MxtOUT** [comment]
Sadly it's not possible to trace back the user's country based on their currency (take the Euro for example) and I can't think of another solution atm

**Comment by fireattack** [comment]
Indeed. But maybe currency (and the number) is all we need in this very case, isn't it?

It doesn't matter what user's region really is. As soon as it displays "268 CNY" or "€59.99", we should have enough information to do the correct comparison between *that* and prices from other regions.

**Comment by metapone** [comment]
It seems like this issue was fixed?
![Screenshot from 2019-10-21 16-25-20](https://user-images.githubusercontent.com/52821877/67193514-9c99cf00-f41f-11e9-8ed4-55fb9bf7d4c7.png)

**Comment by MxtOUT** [comment]
Could you test one thing for me?
What currency is the result of calling https://store.steampowered.com/api/packagedetails/?packageids=300010&cc=?

**Comment by fireattack** [comment]
It shows 

````json
{
"300010": {
"success": true,
"data": {
"name": "Total War: THREE KINGDOMS",
"page_image": "https://steamcdn-a.akamaihd.net/steam/subs/300010/header.jpg?t=1559224794",
"small_logo": "https://steamcdn-a.akamaihd.net/steam/subs/300010/capsule_231x87.jpg?t=1559224794",
"apps": [
{
"id": 779340,
"name": "Total War: THREE KINGDOMS"
}
],
"price": {
"currency": "USD",
"initial": 5999,
"final": 4799,
"discount_percent": 20,
"individual": 0
},
"platforms": {
"windows": true,
"mac": true,
"linux": true
},
"controller": {
"full_gamepad": false
},
"release_date": {
"coming_soon": false,
"date": "May 23, 2019"
}
}
}
}
```

**I found this bug is gone, though!**

![image](https://user-images.githubusercontent.com/4130991/69908632-525b2480-13b3-11ea-8df0-73d53a13c724.png)
