### ISSUE TITLE
Highlight not working again.

### ISSUE THREAD

**Issue by panda331** [tfedor/AugmentedSteam#292]
![2019-06-04_113125](https://user-images.githubusercontent.com/8310721/58849314-7c5db380-86bc-11e9-9be2-1e4a00e1a838.png)
![2019-06-04_113143](https://user-images.githubusercontent.com/8310721/58849315-7c5db380-86bc-11e9-906b-de61d5584664.png)
I am using Chrome 74.

**Comment by MxtOUT** [comment]
Does highlighting work on other pages?
Does this happen consistently?
What page is the top picture?
