### ISSUE TITLE
Open Critic not appearing on new version, meanwhile the metacritic user scores not showing at vall even tho they seem to be present

### ISSUE THREAD

**Issue by kriki200** [tfedor/AugmentedSteam#296]
![image](https://user-images.githubusercontent.com/13945483/59067159-2dc53a80-88b1-11e9-8aa8-6dfb0fd474b1.png)

Left Chrome, right old version for ff.

![image](https://user-images.githubusercontent.com/13945483/59067209-47668200-88b1-11e9-993b-33c8948ee78e.png)

user score...

**Comment by kriki200** [comment]
It did work here tho: 
![image](https://user-images.githubusercontent.com/13945483/59068013-5c441500-88b3-11e9-837b-be79a5d68c84.png)
...

**Comment by kriki200** [comment]
Seems to work normally on this one:
![image](https://user-images.githubusercontent.com/13945483/59068828-96161b00-88b5-11e9-9f57-f23a07467514.png)

this is on Chrome...

**Comment by MxtOUT** [comment]
Works for me, can you reproduce this?
Any errors in the console?

**Comment by kriki200** [comment]
Yeah itwas here: https://store.steampowered.com/app/49520/Borderlands_2/ and the user scores are still not appearing. Dpesnt seem so... 
![image](https://user-images.githubusercontent.com/13945483/59136550-e78cdb80-8983-11e9-958d-2ae428cbee32.png)

**Comment by MxtOUT** [comment]
I can't find Borderlands 2 on OC, so I think this is working as intended

**Comment by candela97** [comment]
metacritic user scores are not showing for me either
