### ISSUE TITLE
Forced custom background

### ISSUE THREAD

**Issue by Blackbird88** [tfedor/AugmentedSteam#298]
I have this issue since 0.9 and I have no idea what to do. For some reason this gross bg is always forced on me
![image](https://user-images.githubusercontent.com/4414625/59146496-49365f80-89ef-11e9-9aa1-4c51d395240a.png)

What I tried and didn't work
- Reinstalling the extension
- Clear cached data
- Setting the custom bg to None and Save
- Clicking Remove button

Please help. OG ES had option to disable the custom BG functionality entirely...

**Comment by Frorran** [comment]
I have had this issue too since forever. I have also tried all of the mentioned ideas for a fix but to no avail.

**Comment by MxtOUT** [comment]
Could you both check the console on the profile edit page when editing the bg and on the background page (https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?

**Comment by Blackbird88** [comment]
I tried that and the console is just empty
![image](https://user-images.githubusercontent.com/4414625/61278817-2a2ca980-a7b5-11e9-85d5-c704f337b5e1.png)
![image](https://user-images.githubusercontent.com/4414625/61278834-31ec4e00-a7b5-11e9-8b86-aa2133a5bb30.png)

**Comment by MxtOUT** [comment]
And the console on the profile edit page?
You might need to check "Preserve log" in order to see the output when another page loads

**Comment by Blackbird88** [comment]
![image](https://user-images.githubusercontent.com/4414625/61367679-6f6fda80-a88c-11e9-8bb7-b0e8732c6939.png)

**Comment by MxtOUT** [comment]
@Frorran Is it the same picture for you?

**Comment by MxtOUT** [comment]
@Blackbird88 Have you tried disabling all other extensions?

**Comment by Blackbird88** [comment]
Disabled all of them, but AS. Still happens.

**Comment by Frorran** [comment]
Sorry for the late reply. No @MxtOUT I am not getting the same. I've enabled preserved log. And tried disabling any other Chrome Add-Ons.

This image is the console log from 1. Entering my Edit Profile page, 2. Proceeding to "Remove" and then 3. Logging in to verify the change and going back to my Edit Profile page.
![chrome_2019-07-26_20-50-28](https://user-images.githubusercontent.com/52937775/61974593-313e8d80-afe7-11e9-983a-a22533248565.jpg)

**Comment by MxtOUT** [comment]
Then could you check your network log under the "Network" tab and send the request URL starting with https://steamcommunity.com/openid/login ?

**Comment by Blackbird88** [comment]
WIll this do?
[steamcommunity.com.zip](https://github.com/tfedor/AugmentedSteam/files/3463911/steamcommunity.com.zip)

**Comment by MxtOUT** [comment]
Yes, thanks, I think that this is a server side error

**Comment by tfedor** [comment]
@Blackbird88 Can you send me link to your Steam profile please?

**Comment by tfedor** [comment]
Also, did you try to edit background? That doesn't work either I assume?

**Comment by MxtOUT** [comment]
This should be fixed right now

**Comment by tfedor** [comment]
Clear your cached data if you still see incorrect background.

**Comment by Blackbird88** [comment]
Fixed it for me! Thanks so much 😎
