### ISSUE TITLE
[Feature Request] option to use search for developer/publisher when clicking on them

### ISSUE THREAD

**Issue by webtax** [tfedor/AugmentedSteam#311]
when clicking on developer or publisher on store pages, currently it goes to those new  developer/publisher land pages if available.

Example
- clicking the developer , for example, Dead Mage [https://i.imgur.com/5Ao3meC.jpg](https://i.imgur.com/5Ao3meC.jpg)
-Sends you to: https://store.steampowered.com/developer/11bitstudios

The feature would be an option to use the search like it was before. 
-So it would send you instead to: 
https://store.steampowered.com/search/?developer=Dead%20Mage if clicking on developer
https://store.steampowered.com/search/?publisher=11%20bit%20studios if clicking on publisher

**Comment by Revadike** [comment]
Oh yeah, I hated this so much. Nowadays, I just visit steamdb's page for the app and search devs/pubs from there...

**Comment by Revadike** [comment]
Example solution: https://greasyfork.org/scripts/379386
