### ISSUE TITLE
Failed to initialize Currency

### ISSUE THREAD

**Issue by KamiYamabushi** [tfedor/AugmentedSteam#317]
![image](https://user-images.githubusercontent.com/11855669/60218411-49cb5480-983d-11e9-8ad1-72da75f4a92c.png)
Seems like regional pricing is broken for me completely for some reason.

**Comment by MxtOUT** [comment]
Has this resolved yet?

**Comment by KamiYamabushi** [comment]
> 
> 
> Has this resolved yet?

Yes, it seems to have resolved itself late last night for me (last time I checked before bed). I'll close the issue. Thanks!

**Comment by Kissaki** [comment]
I have had this issue for months and it never resolved itself.

```
Error: "UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code."
    message moz-extension://<id>/js/core.js:30
    common.js:601:35
Failed to initialize Currency common.js:863:25
Error: "UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code."
    message moz-extension://<id>/js/core.js:30
```

**Comment by MxtOUT** [comment]
Have you tried reinstalling?

**Comment by Kissaki** [comment]
Reinstalling what? The addon? Reinstalling the addon the issue is still there.

**Comment by MxtOUT** [comment]
Have you tried reinstalling your browser?
The unorthodox error message makes me assume that the roots of the problem are not in AS' code
