### ISSUE TITLE
X request(s) failed, check browser console for more information [Summer Sale]

### ISSUE THREAD

**Issue by abbineni** [tfedor/AugmentedSteam#319]
Ever since the steam sale started, I am getting this error on almost all pages.

Here is the console log from Firefox 67.0.4
![image](https://user-images.githubusercontent.com/739546/60234109-6d6cba00-9892-11e9-9468-7f4dc5696b0b.png)

I am accessing the store from India and I reset the settings to default and still the issue persists.

**Comment by 994346680** [comment]
The same thing happened in Chinese store.
So I registered an account to say this.

**Comment by MxtOUT** [comment]
Has this resolved yet?

**Comment by abbineni** [comment]
> 
> 
> Has this resolved yet?

Yes, after 1.1.1 it seems to be working fine
