### ISSUE TITLE
Show achievement progress on page "all games" is broken

### ISSUE THREAD

**Issue by DagiLajki** [tfedor/AugmentedSteam#321]
For some games it is properly generated and for some games bar is broken... (too big) and translation is wrong example here:

![Adnotacja 2019-06-28 183755](https://user-images.githubusercontent.com/38035844/60357465-fa6b5c80-99d3-11e9-9e8e-9eb9cf501071.png)

**Comment by MxtOUT** [comment]
Could you give me that profile link?

**Comment by DagiLajki** [comment]
Sure here it is:

https://steamcommunity.com/profiles/76561197998492623/games/?tab=all

my profile privacy is set to public
