### ISSUE TITLE
"Show Early Access image banners" setting doesn't work

### ISSUE THREAD

**Issue by snakecase** [tfedor/AugmentedSteam#323]
![2019-06-29_00-00-05](https://user-images.githubusercontent.com/4579891/60364955-f570d200-9a00-11e9-85d6-7be0228fdcd7.png)
![2019-06-29_00-00-36](https://user-images.githubusercontent.com/4579891/60364956-f570d200-9a00-11e9-978f-389bf0d65790.png)
Also no banners in lists and community pages.

**Comment by MxtOUT** [comment]
That seems to be an error on the server side, the `early_access_appids` background call returns an empty array @tfedor

**Comment by tfedor** [comment]
Should be working again
