### ISSUE TITLE
Suggestion: make settings page open in a new tab

### ISSUE THREAD

**Issue by snakecase** [tfedor/AugmentedSteam#324]
I guess this will be more user-friendly since extension options always open in new tabs. At least this is what I expect to get as a user when I want to change something on the website and then jump between tabs to make further adjustments.

**Comment by MxtOUT** [comment]
Tbh I'm also the type of user that likes his links to be opened in a new tab, but with the default option the user is able to decide how to open them

**Comment by snakecase** [comment]
We still must regard the majority of users first. I suppose the majority prefers it to open like all the other extensions, in a new tab. Also I see no problem making it a setting with opening in a new tab as default behaviour.
