### ISSUE TITLE
[Bug] Price history overlay z-order on wishlist after an item removal

### ISSUE THREAD

**Issue by timbolin** [tfedor/AugmentedSteam#330]
Issue:

After removing an item from the wishlist, the price history overlay appears underneath the wishlist items instead of on top.

Steps to reproduce:

* Load an account wishlist while logged in as that account
* Change wishlist to compact mode, and sorted by price (this may occur otherwise, I have only tested this specific configuration)
* Remove an item from the wishlist (I have only tested this with items that are not the first or last item, behavior may vary with first or last item removal)
* Hover over a wishlist item and note the z-order of the price history, it appears beneath the item above the hovered item

Probable cause of issue:

I have not verified this (because i didnt think to check the inspector when i first saw it occur) but i suspect that the items on the wishlist are re-initialized after a removal (i have seen items even re-sort themselves on occasion after a removal) which is changing the z-index and resulting in the price history having an incorrect z-index to appear above the prior item in the new stacking context.

**Comment by MxtOUT** [comment]
I'm currently working on adjusting the entries' position to the bottom when the price info is shown, so that shouldn't even be a problem in that implementation
