### ISSUE TITLE
[Suggestion] More statistics about spend money

### ISSUE THREAD

**Issue by LimitlessWorkaround** [tfedor/AugmentedSteam#332]
Hey,

so I saw this picture and thought it would be a very cool feature for Augmented Steam. If it is possible, I would like to see something like this in the extension. ![Image of spend money](https://i.redd.it/zbbh9fk86m731.png)

**Comment by MxtOUT** [comment]
I can't find the post right now, but I remember seeing a similar photo posted on Reddit, where the guy said that it was a feature of Enhanced Steam.

So I looked after the string "Store Purchases" in ES' repo, but I couldn't find any references besides a localization entry.

Where do you have this picture from?

**Comment by MxtOUT** [comment]
Nevermind, I found the [commit in Enhanced Steam](https://github.com/MxtOUT/Enhanced_Steam/commit/25f4b1f0dbf6077a10d701ef69910d636bbf2404) that explains this.
And then I saw that the link mentioned in the commit message is also there in Augmented Steam.
![Exernal Funds Used](https://user-images.githubusercontent.com/14999077/61335340-74517180-a82d-11e9-8083-e40905e4a649.png)
