### ISSUE TITLE
[Suggestion] "I own this elsewhere"-filter

### ISSUE THREAD

**Issue by oyvho** [tfedor/AugmentedSteam#335]
I'd love a filter to mark a title clearly as owned elsewhere, whether another platform, store etc. Preferably one that works like wishlisting and ignoring, but without any effect on what sort of suggestions steam gives regarding other titles.

**Comment by MxtOUT** [comment]
I'd also love to have that, it would be so useful.
We planned to add a function where you could connect your ITAD account to AS, thus opening the possibilities for stuff like this

**Comment by USERNAME-ALREADY-TAKENN** [comment]
Sync with ITAD please! I got thousands bundle games that are still unredeemed on my account, but many of these bundles are marked as owned on ITAD, because in this way I can see if i'm missing something from new bundles.

**Comment by MxtOUT** [comment]
This is now being tracked in #338
