### ISSUE TITLE
[Feature Request] Keep editable rankings in wishlist even when it's sorted/filtered/searched

### ISSUE THREAD

**Issue by enchained** [tfedor/AugmentedSteam#337]
This issue reminded of itself in the latest event - if you wanted to move your game to # 1, you first had to find it. Manually. By scrolling. Cause ctrl f didn't work and you can't edit ranking when you apply anything to the basic ranking sorting. And if you had a few hundreds on the wishlist then, oh well. It was easier to find in store and re-add so it'll predictably appear at the bottom of the ranked list.

Use cases other than events: re-rank your wishlist based on specific game types or their ratings, etc.

Don't know if it's easily implemented or not, but could be useful.

**Comment by metroid112** [comment]
I worked around this by editing the wishlist with Chrome's console and changing the appid of the element I wanted in that position.

But yes, having the ranking change with the other filters on would be a blessing.

**Comment by Revadike** [comment]
That could work, but only if you disable dragging, as that would mess up the existing order, wouldn't it?

**Comment by gab** [comment]
This is needed more than ever, especially now that adding or re-adding a game to your wishlist doesn't even send it to the bottom anymore, it seems to get in a semi-random position (might be a behavior specific to very large wishlists, but it's been happening consistently to me for months). So the simple task of moving a game to position number 1 in your wishlist is an impossible task if the wishlist is very large.

**Comment by Revadike** [comment]
Can't you guys just change the position number here? You won't have to drag it all the way to the top.

![image](https://user-images.githubusercontent.com/4411977/110797248-2ea2b180-8279-11eb-8ae0-7cbe2661fb80.png)

**Comment by Latelistener** [comment]
@Revadike, to edit the rank field you'll have to find this game in your wishlist through manual scrolling (imagine having 2k+ games in there), because if you try to punch the name of a game in the search field, the rank will not be visible anymore and thus you cannot change it.

![sekiro](https://user-images.githubusercontent.com/10329878/110819984-bdc2c000-829f-11eb-8fae-3e959cb64dca.jpg)

**Comment by Revadike** [comment]
Ah yes, now I see. That's indeed annoying.

**Comment by Latelistener** [comment]
I just tried inspecting HTML and it seems like the ranking is actually still there, it's just having width: 0px. I tried increasing its width and editing the rank input and it worked. The only problem is that it breaks the game item layout and my knowledge of CSS isn't very good to fix it.

**Comment by enchained** [comment]
Steam probably hides it cause the drag and drop of it would be broken - if I unhide it, it just resets the rank within the filtered list position, which may be confusing. A good idea would be to disable drag and drop, leaving just the input. 

Steam uses this handle to hook drag and drop:
`$J('.hover_handle',$el)[0].addEventListener('mousedown', fnDragStart);` I remember it not being possible to removeEventListener without a reference, so another idea would be to clone the input to a new handle element instead:

```
const hasRank = jQuery("#wishlist_ctn").hasClass("sort_order");
if (!hasRank) {
  jQuery("#wishlist_ctn").addClass("esi-show-rank");
  jQuery(".wishlist_row").each((i, row) => {
    jQuery(row).prepend(
      jQuery(
        '<div class="hover_handle esi-rank" draggable="false"></div>'
      ).append(
        jQuery("<div></div>").append(jQuery(".order", jQuery(row)).clone(true))
      )
    );
  });
}
```

And copy the existing styles to make it visible:
```
#wishlist_ctn:not(.sort_order).esi-show-rank .capsule {
  margin-left: 40px;
}

#wishlist_ctn:not(.sort_order).esi-show-rank .hover_handle.esi-rank {
  display: block;
  width: 40px;
  border-right: 1px solid rgba(0, 0, 0, 0.2);
}

#wishlist_ctn:not(.sort_order).esi-show-rank .hover_handle.esi-rank img {
  display: none;
}

#wishlist_ctn.sort_order.esi-show-rank .hover_handle.esi-rank {
  display: none;
}
```

I guess for the extension it also will need to rerun on filters applied/reset, and to account for continuous scrolling, but for quick testing it works from devtools console by running those 3 commands:
```
jQuery("#wishlist_ctn").addClass("esi-show-rank");
jQuery(".wishlist_row").each((i, row) => {jQuery(row).prepend(jQuery('<div class="hover_handle esi-rank" draggable="false"></div>').append(jQuery('<div></div>').append(jQuery(".order", jQuery(row)).clone(true))));});
document.head.insertAdjacentHTML("beforeend","<style> #wishlist_ctn:not(.sort_order).esi-show-rank .capsule { margin-left: 40px; } #wishlist_ctn:not(.sort_order).esi-show-rank .hover_handle.esi-rank { display: block; width: 40px; border-right: 1px solid rgba(0,0,0,0.2); } #wishlist_ctn:not(.sort_order).esi-show-rank .hover_handle.esi-rank img { display: none; } #wishlist_ctn.sort_order.esi-show-rank .hover_handle.esi-rank { display:none; }</style>");
```


Also, until the feature implemented, it can be used as a bookmarklet (preferably for short filters like the search one) by pasting those commands there, and using the result to replace the bookmark url:
`javascript:(function(){replaceWithYourCommands})();`
You'll need to refresh the wishlist page when you don't need it anymore or see something broken.

**Comment by Revadike** [comment]
@enchained You could try to implement this code into the extension and make a [pull request](https://github.com/tfedor/AugmentedSteam/compare). Then, it could be reviewed and merged into the main extension!

**Comment by gab** [comment]
> Also, until the feature is implemented, it can be used as a bookmarklet (preferably for short filters like the search one) by pasting those commands there, and using the result to replace the bookmark url:
> `javascript:(function(){replaceWithYourCommands})();`
> You'll need to refresh the wishlist page when you don't need it anymore or see something broken.

I've tried the bookmarklet tip and it works great as a stopgap measure - shows the rank form when filtered as advertised, and I was able to change one of my games' rank. Thanks @Latelistener for the initial research and @enchained for writing all this code, you guys are awesome. Seems like a good candidate to submit to the extension after a bit of polish?

**Comment by candela97** [comment]
Looks like we'll have to rely on jQuery's `clone()` method in order to copy event handlers, native JS won't work here.

@enchained Are you still working on this? I have a local version working based on your code, and can submit it with you as a co-author.

**Comment by Revadike** [comment]
> Looks like we'll have to rely on jQuery's `clone()` method in order to copy event handlers, native JS won't work here.

http://youmightnotneedjquery.com/#clone

**Comment by candela97** [comment]
Yeah but `cloneNode(true)` doesn't copy event listeners :(

Anyway, I found a way to make it work: we can dispatch a `change` event on the old input to trigger Steam's handlers.
