### ISSUE TITLE
[Bug] Account name not replaced @ Purchase History

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#339]
https://store.steampowered.com/account/history/ still shows my account name. I'd prefer it to say my community name, like everywhere else, when `Replace account name with community name` is enabled.

**Comment by MxtOUT** [comment]
Works for me, do you see any errors in the console?

**Comment by Revadike** [comment]
No, this is it, but these errors are unrelated:
![image](https://user-images.githubusercontent.com/4411977/61158545-8794d200-a4f9-11e9-8a09-e9bd2cb70a13.png)

I did notice that it changes the document title, but `LOGINNAME'S PURCHASE HISTORY` remains unchanged. The css selector for it on my page is: `body > div.page_header_ctn.account_management > div > h2.pageheader`

**Comment by MxtOUT** [comment]
Oh, thanks to the selector I now see what you mean!
I thought you meant the name to the left of your profile picture.
Investigating...

**Comment by Revadike** [comment]
Oh, my bad. I should have screenshotted it.

**Comment by Revadike** [comment]
Same thing, but on the [licenses page](https://store.steampowered.com/account/licenses):
`body > div.responsive_page_frame.with_header > div.responsive_page_content > div.responsive_page_template_content > div.page_header_ctn > div > h2`

Actually, all `https://store.steampowered.com/account/*` pages and subpages.

**Comment by MxtOUT** [comment]
This should be fixed with the PR

**Comment by Revadike** [comment]
Can confirm it's fixed in the latest update.
