### ISSUE TITLE
[Feature Request] Please include Humble Monthly discount as an option

### ISSUE THREAD

**Issue by John-Gee** [tfedor/AugmentedSteam#340]
Pretty please look into this, we currently get -20% with HM, that's quite substantial and often make Humble the cheapest option.

**Comment by MxtOUT** [comment]
That seems like it would fit better in the issue tracker of ITAD.
But I've heard that support for GMG VIP deals is planned for new ITAD, so the chances that the Humble Monthly discount will be added too are very high

**Comment by John-Gee** [comment]
That's fair, ITAD should also display the discounted price.

**Comment by tfedor** [comment]
You can add custom discount via store options https://isthereanydeal.com/settings/stores/

**Comment by John-Gee** [comment]
That's awesome, I did not know I could do that, but it does not seem like the extension pulls that information, or is there something else needed to be setup?

Thank you!

**Comment by MxtOUT** [comment]
No, not yet, look at #338 and #335 for ITAD integration

**Comment by John-Gee** [comment]
Alright, I'll close then, and will await on the others.

Thank you for the quick reply!
