### ISSUE TITLE
[Suggestion/Feature Request] Filter by review number in search hide feature

### ISSUE THREAD

**Issue by Hexogenx** [tfedor/AugmentedSteam#357]
As Steam gets more and more flooded with dozens of releases, games and contents each day, I'd like to filter the search results by number of reviews, for example "Hide results with 500 reviews or less". This should atleast clean up the list of "Very Positve" games with 72 reviews, where most of those reviews could be friends/bought/product recieved for free and have no value at all.

**Comment by Revadike** [comment]
Assign me to this
