### ISSUE TITLE
[BUG] Excluding tags does not work

### ISSUE THREAD

**Issue by Shellshock123** [tfedor/AugmentedSteam#360]
When doing a steam search

https://store.steampowered.com/search/

When i exclude a tag I get an

oops sorry

An error was encountered while processing your request:

There was a problem communicating with the Steam servers. Please try again later.

https://imgur.com/aV0MbUP

and it looks really wonky

**Comment by MxtOUT** [comment]
We are aware of this issue, this was caused by Steam dropping support for excluding tags (or at least in the way that AS tried to do it).
Thus we have to probably fall back to client side filtering

**Comment by Shellshock123** [comment]
Thanks but what is Client-side filtering 

is it when you add a negative sign in included tags in the address bar?

**Comment by MxtOUT** [comment]
Adding a negative sign before the tag id is server side filtering since this was a request to the Steam servers to exclude the specified tags.

Now that this doesn't seem to work anymore, we probably have to fall back on looking at the search results on your (client) side and removing any entries that contain one of the tags you want to exclude

**Comment by the-importer** [comment]
I had forgotten what it was like to look at the new game releases without masking all of the porn, VR, RPG Maker and Visual Novel games being released everyday :(

**Comment by Revadike** [comment]
Added this bug to `Known issues` in the changelog: https://github.com/tfedor/AugmentedSteam/pull/533

**Comment by dahauns** [comment]
Steam is *finally* on the way to integrate this feature in their search options - it is currently available in Steam Labs:

https://imgur.com/a/B1QA3Jd

**Comment by MxtOUT** [comment]
This feature has been removed from AS, since Steam now supports it natively
