### ISSUE TITLE
On Chrome, some functions do not work on store pages for games that are already in Steam library.

### ISSUE THREAD

**Issue by B5F** [tfedor/AugmentedSteam#364]
Sorry if this is an already known issue.

![Sine_Mora](https://user-images.githubusercontent.com/47687553/62424867-f9c69400-b6fe-11e9-8a49-66ab957cde05.png)

In the above screenshot: on the left side is when I signed into Steam, and on the right is when I signed out.

As you can see, many of Augmented Steam do not work at all on owned games' pages.
There is no issue on game pages that I haven't purchased though, even when I signed in.

Here are functions that break:
1. The layout of Steam and YouTube Gameplay taps.
2. Regional Price Comparison.
3. Customize button.
4. Link to AStats.
5. Current Players, Performance Survey, and Player Data.

However, this problem only occurs on Chrome. I use Chrome 76.0.3809.87 with Augmented Steam 1.1.1.
I have tested with Firefox 68.0.1 with Augmented Steam 1.1.1, and everything works properly.

Also, I would like to ask whether there is a way to move Augmented Steam data from Chrome to Firefox?
I have notes on more than hundred games, mostly to remind me why I shouldn't buy certain games (already owned on other platforms, serious bugs, abandoned by developers, etc.). And I do not want to lose all those notes.

**Comment by MxtOUT** [comment]
Ok, do you see any errors in your browser console (F12)?

1. The broken layout of the tabs indicates that a CSS stylesheet is not loaded (yet?)
2. Probably you're getting a time out here
3. This is only added after the data of (5) has been retrieved
4. Have you enabled showing AStats links in the options?
5. That actually has to mean that fetching the app page data fails

That seems like your internet connection is very slow (at least at the point of the recording).

To your second question:

You can [set a breakpoint](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#setting-a-breakpoint) at store.js:3518 and type `copy(SyncedStorage.get("user_notes"))` into the console.
The notes object is now in your clipboard.

Switch to FF and stop at the same breakpoint.
Type in `SyncedStorage.set("user_notes", YOUR_CLIPBOARD_CONTENT)`.

Note that this overrides any notes you had on FF.
If you don't want that, instead type in `SyncedStorage.set("user_notes", Object.assign(SyncedStorage.get("user_notes"), YOUR_CLIPBOARD_CONTENT))`.

I know, this is very inconvenient, but support for import/export of notes is planned

**Comment by B5F** [comment]
After Augmented Steam updated to version 1.1.2 earlier today, everything works perfectly now.

And, MxtOUT, Thank you so much for a tip on moving notes data.
It works great; all my notes are now synced between both browsers.
