### ISSUE TITLE
Sort your steam groups

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#386]
Sort your group list by group name, creation date or total members.
Much like [my userscript](https://greasyfork.org/en/scripts/24800-steam-community-group-list-sorter/) does (currently broken).

**Comment by MxtOUT** [comment]
I don't think that this would really help a lot of people, but on the other side I don't think that such a small button is harmful, so I would approve that.

Where is [this button](https://greasyfork.org/system/screenshots/screenshots/000/005/778/thumb/2016-11-13_01_13_38-Steam_Community____Group_List.png?1478996010) supposed to be placed though?

**Comment by Revadike** [comment]
> I don't think that this would really help a lot of people, but on the other side I don't think that such a small button is harmful, so I would approve that.
> 
> Where is [this button](https://greasyfork.org/system/screenshots/screenshots/000/005/778/thumb/2016-11-13_01_13_38-Steam_Community____Group_List.png?1478996010) supposed to be placed though?

Actually, this really helps with group management. That button is from the outdated UI and as I mentioned currently broken. The new sorting options could appear here:
![image](https://user-images.githubusercontent.com/4411977/63894930-21530880-c9ee-11e9-8054-8013eb5b915a.png)
Just like sorting friends option added by AS.
