### ISSUE TITLE
Steam Context Menu

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#388]
Implement the features from:
 * https://github.com/Skylark95/chrome-steam-context-menu by @Skylark95
 * https://github.com/jshackles/ActivateOnSteam by @jshackles <3
 * https://github.com/Yusyuriv/Community_Market_Search_for_Chrome by @Yusyuriv

Search or activate selected text on any web page on steam and steamdb, via right click.
![image](https://user-images.githubusercontent.com/4411977/62839573-e893ff00-bc8b-11e9-9551-b8a2616845aa.png)
![image](https://user-images.githubusercontent.com/4411977/62840493-1719d600-bc9c-11e9-81b1-5688dfad7195.png)

**Comment by MxtOUT** [comment]
To the links:

1. Sounds cool
2. Damn, this is nuts!
3. Rather useful imo (please tell me what trading communities would find this useful ;) )

**Comment by MxtOUT** [comment]
I see that I wrote "useful" instead of "useless" for point three, sorry

**Comment by Revadike** [comment]
> I see that I wrote "useful" instead of "useless" for point three, sorry

Depends if you are a heavy market user. Anyway, in my pull request I made all context menu options optional (check and uncheck them). Also, I've condensed these market options into 1 market search option.
