### ISSUE TITLE
Fix ds_options tooltip bug

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#389]
The game highlighter draws over the ds_options tooltip, making it impossible to use.

Vanilla:
![image](https://user-images.githubusercontent.com/4411977/62839628-7a9c0780-bc8c-11e9-89b6-78a9d86502a8.png)

Augmented Steam:
![image](https://user-images.githubusercontent.com/4411977/62839636-94d5e580-bc8c-11e9-93e5-7f737f6702fe.png)

**Comment by MxtOUT** [comment]
Hm, I also noticed that bug somewhere, but I can't replicate it right now

**Comment by Revadike** [comment]
> Hm, I also noticed that bug somewhere, but I can't replicate it right now

I used the sale pages, e.g. https://store.steampowered.com/sale/gta/
