### ISSUE TITLE
Improve favorite emoticons

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#391]
This would display your most used emoticons at the top of your emoticon window.

![](https://steamuserimages-a.akamaihd.net/ugc/964232955165101163/D2C00DB4D01AEF30858B3546D81EBAD646C1593C/)

**Comment by MxtOUT** [comment]
Very useful

**Comment by MxtOUT** [comment]
Reopening for [Steam web chat](https://steamcommunity.com/chat/) support and a [minor performance issue](https://github.com/tfedor/AugmentedSteam/pull/483#discussion_r318824667)

**Comment by Revadike** [comment]
> Reopening for [Steam web chat](https://steamcommunity.com/chat/) support and a [minor performance issue](https://github.com/tfedor/AugmentedSteam/pull/483#discussion_r318824667)

I don't think I'll be changing the web chat emoticons, as they already show the most/recently used emoticons on the top:
![image](https://user-images.githubusercontent.com/4411977/63962081-83fde000-ca92-11e9-8b62-02fdf7741214.png)
