### ISSUE TITLE
Accurate profile statuses

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#393]
For example, Steam shows "Online" on steam community profiles, while they are actually "Away"
![image](https://user-images.githubusercontent.com/4411977/62839751-352d0980-bc8f-11e9-92ae-6bfea1c229c5.png)

Maybe also add the device icon (VR, mobile, web, client, etc).

You can actually get this info directly from the `ISteamUser/GetPlayerSummaries` API with the `personastate` property:
```json
{
    "0": "Offline",
    "1": "Online",
    "2": "Busy",
    "3": "Away",
    "4": "Snooze",
    "5": "Looking to trade",
    "6": "Looking to play"
}
```

Implement the features of https://greasyfork.org/en/scripts/26652 by @Delite

**Comment by Revadike** [comment]
A follow-up feature could be to add colors to each status, like this:
![image](https://user-images.githubusercontent.com/4411977/62839817-8d184000-bc90-11e9-8873-8bf20b61b69d.png)

**Comment by Revadike** [comment]
404 https://esapi.isthereanydeal.com/v01/steamapi/GetPlayerSummaries/
Needs to be added

**Comment by tfedor** [comment]
Closing for now as I don't see a way how to implement this properly due to API limits.

**Comment by Revadike** [comment]
> Closing for now as I don't see a way how to implement this properly due to API limits.

Then leave it open?

**Comment by Revadike** [comment]
Actually, how about in the options, people can allow use of their steam API key? Then this will happen clientside

**Comment by tfedor** [comment]
In theory that would be an option, but I don't think it would be a too often used feature due to these hoops.

**Comment by Revadike** [comment]
> In theory that would be an option, but I don't think it would be a too often used feature due to these hoops.

So what? It's worth it if just 1 person uses it. If it's fine by you, I can make it.

**Comment by Revadike** [comment]
Please reopen this! @MxtOUT 
I'd love to see this feature some time in the future.
The API key can be used for other applications, so when we decide to give the user the option to allow it, we can add this.

Similar project: 
https://github.com/DoctorMcKay/steam-profile-detailed-status

**Comment by Revadike** [comment]
Additionally, we can use `IsPlayingSharedGame` api to determine if the game that's currently being played is borrowed or not.

**Comment by Revadike** [comment]
I think using the user's API key (if opted in) is the way to go. This should be re-opened, imo.

**Comment by Revadike** [comment]
This can be done without needing API key with the following endpoint: https://steamcommunity.com/actions/ajaxresolveusers?steamids=STEAMIDS

**Comment by Revadike** [comment]
Hmm, you don't even need an API key for the other endpoint, either. Using `access_token` is sufficient, which conveniently, is already being used in AS.
