### ISSUE TITLE
Sort your steam reviews

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#394]
The ability to sort [your own Steam reviews](https://steamcommunity.com/my/recommended/) by Public/Private, Comments Enable/Disabled, Postive/Negative, Most Helpful, etc. for easier management. Right now they're all listed together page by page in chronological order.

**Comment by MxtOUT** [comment]
> Public/Private, Comments Enable/Disabled, Postive/Negative

These would be filters, right?

**Comment by Revadike** [comment]
> > Public/Private, Comments Enable/Disabled, Postive/Negative
> 
> These would be filters, right?

Correct
