### ISSUE TITLE
Extend steam client links

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#399]
Add a button or link somewhere on (possibly) every steam web page, that would open the equivalent page in Steam Client.
[Steam browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) can be used for this.

**Comment by MxtOUT** [comment]
I don't see the benefits of this in most cases, as the Steam client is just plain Steam without AS' additions.
There are cases though where it would be useful (right now I can only think of linking to your library)

**Comment by Revadike** [comment]
> just plain Steam without AS' additions

Could be exactly what you want sometimes.

**Comment by MxtOUT** [comment]
Then you could just disable AS

**Comment by briank6932** [comment]
I agree this would be really useful

**Comment by Revadike** [comment]
My PR of this issue was merged, but due to it being improperly done... this issue wasn't closed...
