### ISSUE TITLE
Profile SteamID viewer

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#405]
Implement the features from https://github.com/DoctorMcKay/steam-profile-steamid-viewer by @DoctorMcKay

This replaces the permalink field.

**Comment by Revadike** [comment]
@DoctorMcKay Do you have an unminified version of the steamid module?

**Comment by DoctorMcKay** [comment]
I don't think so. It's just a webpacked version of [steamid](https://www.npmjs.com/package/steamid).

**Comment by Revadike** [comment]
> I don't think so. It's just a webpacked version of [steamid](https://www.npmjs.com/package/steamid).

Thanks, managed to convert the node.js module to web js library. Check last commit.

**Comment by Revadike** [comment]
Aside from this being useful information, it can also be used to obtain [your friendcode](https://steamcommunity.com/my/friends/add) to share among your friends :)

**Comment by Revadike** [comment]
Additionally, a dialog can be added to groups too!
