### ISSUE TITLE
"External Funds Used" always links to the English site

### ISSUE THREAD

**Issue by Tarkoviski** [tfedor/AugmentedSteam#412]
The "External Funds Used" link located in the "Account details" always links to the English site, bypassing the user preferences.

This can be fixed by removing the language code from the link (https://help.steampowered.com/en/accountdata/AccountSpend -> https://help.steampowered.com/accountdata/AccountSpend)

Line in question: https://github.com/tfedor/AugmentedSteam/blob/2c81ddbf319d2ed854a70114046a5b6bfcb950c5/js/content/store.js#L2206

**Comment by Revadike** [comment]
Assign me to this
