### ISSUE TITLE
Some collected issues after using it with Firefox 68.0.1

### ISSUE THREAD

**Issue by shakeyourbunny** [tfedor/AugmentedSteam#419]
Hello,

thank you for your ressurection of EnhancedSteam, but I have some issues with it:

- there is no "save options" button in the options page.

- on every store page, there is now a "Make sure that you are logged into steamcommunity.com in order to be able to use all features of Augmented Steam." although I AM logged in.  This is somewhere with ".es_warning".

Most likely reason is that the extension is trying to read a cookie (= third-party cookie) from steamcommunity.com which is blocked due security reasons.  Many more security-concious people are doing this.

Please compensate for this. Thank you.

- if you disable "Show MetaCritic" it is still displayed on store pages, other sources are working correctly.

Thank you.

**Comment by MxtOUT** [comment]
> there is no "save options" button in the options page.

It automatically saves when you change an option.

> on every store page, there is now a "Make sure that you are logged into steamcommunity.com in order to be able to use all features of Augmented Steam." although I AM logged in. This is somewhere with ".es_warning".

I know you opened this issue before #479, but this one has a more suitable title.

> if you disable "Show MetaCritic" it is still displayed on store pages, other sources are working correctly.

The option is indeed named "Show Metacritic **user scores**" and it works as intended.
The Metacritic info you are seeing are reviews by critics, not by users
