### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#420]
After the Steam website today's update, a lot of features become invalid.

**Comment by SighmanSays** [comment]
If you mean that Augmented Steam does not progress in store pages but works fine in community (the green bar starts but never goes further), try disabling "Hide "Install Steam" button / "About" link" in options. Does the trick for me.

**Comment by tfedor** [comment]
Fixed in v1.2.1 (released for Firefox, pending for Chrome)
