### ISSUE TITLE
Note layout on game's page is broken after Steam store update. (Augmented Steam 1.2.1)

### ISSUE THREAD

**Issue by B5F** [tfedor/AugmentedSteam#421]
![Screenshot_Augmenmted_Steam](https://user-images.githubusercontent.com/47687553/63091586-0366bc00-bf89-11e9-9994-0b064cb79f66.jpg)

This issue presents in Augmented Steam 1.2.1 on both Firefox 68.0.2 and Chrome 76.0.3809.100.

**Comment by Revadike** [comment]
I'd like to add that the new dropdown for Ignore is also misplaced, due to the notes button. It should be right behind "ignore", but instead is behind the notes button.

**Comment by Revadike** [comment]
Also https://github.com/tfedor/AugmentedSteam/issues/497
