### ISSUE TITLE
Add ESLint config

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#431]
Most of the extension's codebase is a mixture of coding styles/standards. Some consistency would be nice. ESLint is amazing for that. There are even options to autoformat is onsave.

Once we figure out a appropriate config for ESLint, we should process first all existing pull requests. Once that's done, we should format the entire codebase (most should be done automatically) and merge that. This way we avoid many merge conflicts.

As for generating a good config. Make some suggestions. I'll also put some of my preferences in the comments below, which you can vote on 👍  or 👎 .

**Comment by Revadike** [comment]
Use template literals for every string (`\`string\``), I like this since it offers a convenient way to add variables to your strings. Especially for HTML strings it's nice, as it allows you to use single and double quotes without escaping them.

Also, usage of `+` to concatenate strings will be avoided.

**Comment by Revadike** [comment]
Prefer promises, over callbacks?

**Comment by Revadike** [comment]
Prefer arrow functions, over `function` functions?

**Comment by Revadike** [comment]
No `var`'s, only `let` for "variables" and `const` for global constants/enums

**Comment by Revadike** [comment]
JSON keys must be enclosed with double quotes

**Comment by Revadike** [comment]
Space before and after operators (`==`, `===`, `<`, `>`, `<=`, `>=`, `!=`, `!==`, `=`)

**Comment by Revadike** [comment]
Prefer `===` over `==` where-ever possible.

**Comment by Revadike** [comment]
Prefer dot notation for objects (so avoid `json["key"]`)

**Comment by Revadike** [comment]
snake_case for variables

**Comment by Revadike** [comment]
camelCase for functions

**Comment by Revadike** [comment]
CamelCase with uppercase first letter for classes/prototype objects

**Comment by MxtOUT** [comment]
> Use template literals for every string (`` `string` ``), I like this since it offers a convenient way to add variables to your strings. Especially for HTML strings it's nice, as it allows you to use single and double quotes without escaping them.
> 
> Also, usage of `+` to concatenate strings will be avoided.

I think it's unnecessary to do this for a simple string without any variable replacements.
But when it comes to replacements, definitely prefer template literals over `+`

> snake_case for variables

I don't like snake_case because it adds at least one extra character to each variable

Could you remove your votes on **your** proposes?

**Comment by Revadike** [comment]
There are a lot more rules to discuss. Feel free to add some. Also, I think I should be able to vote on any proposals, so I could propose something I don't necessarily want.

**Comment by MxtOUT** [comment]
> There are a lot more rules to discuss.
I know, but let's put the rules where we've come to an agreement in the OP

**Comment by Revadike** [comment]
> > There are a lot more rules to discuss.
>
> I know, but let's put the rules where we've come to an agreement in the OP

Or make a pull request for a config.

**Comment by MxtOUT** [comment]
Well, let's wait for v1.3.0 before we start with that

**Comment by Revadike** [comment]
I am not sure about:
 * https://eslint.org/docs/rules/max-statements-per-line
 * https://eslint.org/docs/rules/no-case-declarations

Also, not sure how to handle `no-undef` rule with `ExtensionLayer.runInPageContext` functions. Perhaps we should stringify all those functions. But that disables lint checking on those functions.

**Comment by Revadike** [comment]
Also, do we prefer using `class` constructor for classes, or the traditional `let someClass = (function(){...})()`?

**Comment by tfedor** [comment]
In https://github.com/tfedor/AugmentedSteam/tree/feature-eslint branch is my initial take on eslint. This is not meant to be final, I didn't go through code, just through rules and added what made sense to me. We will need to tweak it.

Do not, by no means, start editing current code based on this code. You can write new code based on this though. Go through it, tell me what you don't like, or try it and tell me what annoys you, what you'd add or change.

**Comment by Revadike** [comment]
> In https://github.com/tfedor/AugmentedSteam/tree/feature-eslint branch is my initial take on eslint. This is not meant to be final, I didn't go through code, just through rules and added what made sense to me. We will need to tweak it.
> 
> Do not, by no means, start editing current code based on this code. You can write new code based on this though. Go through it, tell me what you don't like, or try it and tell me what annoys you, what you'd add or change.
> 
> Here's the config itself: https://github.com/tfedor/AugmentedSteam/blob/feature-eslint/.eslintrc.json

Is it based on my config? Did you check my proposal at all?

**Comment by tfedor** [comment]
> Is it based on my config? Did you check my proposal at all?
I do not see any your config here, I read through your comments though

> Also, I do suggest we fix the current code base at some point.
Of course, would be pointless to add ESLint otherwise. What I meant yesterday is that you shouldn't take current config and go rewriting whole repo, because the config is not final and may change and may have issues.

**Comment by tfedor** [comment]
I just noticed your PR, missed it before. So no, I did not based it on your config

**Comment by tfedor** [comment]
I don't know what rules airbnb and prettier sets, but regarding rules themselves, these are the ones from your config that I either don't set or where I differ

```"array-bracket-newline": ["error", "never"],
"array-bracket-spacing": ["error", "never"],
"arrow-body-style": ["error", "as-needed"],
"arrow-parens": ["error", "always"],
"callback-return": ["error", ["callback", "cb", "next"]],
"comma-dangle": ["error", "never"],
"comma-spacing": ["error", { "before": false, "after": true }],
"eol-last": ["error", "never"],
"eqeqeq": ["error", "always"],
"function-paren-newline": ["error", "never"],
"handle-callback-err": "error",
"indent": ["error", 4, {"SwitchCase": 1}],
"max-statements-per-line": ["error", {"max": 1}],
"multiline-ternary": ["error", "never"],
"no-case-declarations": 0,
"no-extra-parens": ["error", "all"],
"no-multi-spaces": "error",
"no-multiple-empty-lines": ["error", {"max": 1 }],
"no-tabs": "error",
"no-trailing-spaces": "error",
"object-curly-newline": ["error", {"multiline": true, "minProperties": 0}],
"object-curly-spacing": "error",
"object-property-newline": "error",
"padded-blocks": ["error", "never"],
"prefer-arrow-callback": "error",
"prefer-spread": "error",
"prefer-template": "error",
"quote-props": ["error", "always"],
"quotes": ["error", "double", {"allowTemplateLiterals": true} ],
"space-before-blocks": "error",
"spaced-comment": "error",
```

**Comment by Revadike** [comment]
> I don't know what rules airbnb and prettier sets, but regarding rules themselves, these are the ones from your config that I either don't set or where I differ
> 
> 
> ```
> "array-bracket-spacing": ["error", "never"],
> "arrow-body-style": ["error", "as-needed"],
> "arrow-parens": ["error", "always"],
> "callback-return": ["error", ["callback", "cb", "next"]],
> "comma-dangle": ["error", "never"],
> "comma-spacing": ["error", { "before": false, "after": true }],
> "eol-last": ["error", "never"],
> "eqeqeq": ["error", "always"],
> "function-paren-newline": ["error", "never"],
> "handle-callback-err": "error",
> "indent": ["error", 4, {"SwitchCase": 1}],
> "max-statements-per-line": ["error", {"max": 1}],
> "multiline-ternary": ["error", "never"],
> "no-case-declarations": 0,
> "no-extra-parens": ["error", "all"],
> "no-multi-spaces": "error",
> "no-multiple-empty-lines": ["error", {"max": 1 }],
> "no-tabs": "error",
> "no-trailing-spaces": "error",
> "object-curly-newline": ["error", {"multiline": true, "minProperties": 0}],
> "object-curly-spacing": "error",
> "object-property-newline": "error",
> "padded-blocks": ["error", "never"],
> "prefer-arrow-callback": "error",
> "prefer-spread": "error",
> "prefer-template": "error",
> "quote-props": ["error", "always"],
> "quotes": ["error", "double", {"allowTemplateLiterals": true} ],
> "space-before-blocks": "error",
> "spaced-comment": "error",
> ```

Okay, thanks for clarifying. Would you be willing to go through these rules 1 by 1, checking whether or not they make sense to you. I'll do the same with the rules you created.

**Comment by Revadike** [comment]
I've taken a look at your config. Here are some points of interests:
 * Check my `globals`, I think you need to add them too. Sadly, ESLint doesn't seem to recognize modules for extensions. Maybe there is another solution for this. Now, these global variables trigger the `no-undef` rule.
 * Not sure why but I get these definition not found errors, even though these rules exist. Why do you think this happens?
![image](https://user-images.githubusercontent.com/4411977/70084702-158b6980-160f-11ea-8e9a-239ca6db4548.png)
 * As you may have noticed in my config, you could add these to environments:
```js
        "commonjs": true,
        "webextensions": true,
```
 * ~~As you may have noticed in my config, I think it is prefered to force string concatenations using template literals. So `"abc" + var + "abc"` should become ``` `abc${var}abc` ```.~~  Nevermind, I now see this is a warning instead of an error.
 * As you may have noticed in my config, I allow inside an indent a `case` block, your config does not current.
 * Still looking for answers from https://github.com/tfedor/AugmentedSteam/issues/431#issuecomment-552048935 
 * I don't think we should allow certain whitelines, like after `function`, `if/else` or `class`.
 * I think we should add spaces between curly brackets and keys and maybe add quotes around a key, e.g. `{key: value}` should become `{ "key": value }`.
 * ~~Seems you can have more than 1 spaces anywhere. I think this should be disallowed (unless it's an indent). ~~ Nevermind, I now see this is a warning instead of an error.
 * You config forces a space after `catch`. Do we want this?
 * You config does now allow empty arrow functions. Do we want this?
 * Do we really want to prefer `const` over `let`? Personally I don't mind, but this causes a lot of warnings, because we never did this.
 * I think `dot-notation` should be `error` rather than `warning`.
 * Are you sure `no-new` rule is working as intended?

**Comment by tfedor** [comment]
> Check my globals, I think you need to add them too. Sadly, ESLint doesn't seem to recognize modules for extensions. Maybe there is another solution for this. Now, these global variables trigger the no-undef rule.

I was thinking about that, I will probably drop no-undef rule. I don't think it's good idea to edit ruleset each time we add or remove class.

> Not sure why but I get these definition not found errors, even though these rules exist. Why do you think this happens?

do you have ESlint up to date?

> As you may have noticed in my config, you could add these to environments:
Why? What do they do?

> As you may have noticed in my config, I allow inside an indent a case block, your config does not current.

Will check

> Still looking for answers from #431 (comment)

Dunno, but see previous comment about dropping no-undef. Don't know how max statements behave, will have to check.

> I don't think we should allow certain whitelines, like after function, if/else or class.

What rule is that?

> I think we should add spaces between curly brackets and keys and maybe add quotes around a key, e.g. {key: value} should become { "key": value }.

I was thinking about that, same about whitespaces in arrays. I think it's better to not force it and let programmer decide what is most readable, as that may vary by situation. About keys, I believe I set it to "consistent", what's the argument for forcing quotes?

> You config forces a space after catch. Do we want this?

Yes, I believe so, it should be the same as a space after `try˙` or `else`

> You config does now allow empty arrow functions. Do we want this?

Why would we want empty functions?

> Do we really want to prefer const over let? Personally I don't mind, but this causes a lot of warnings, because we never did this.

We don't, I noticed that after commiting, will change.

> I think dot-notation should be error rather than warning.

I think you are right

> Are you sure no-new rule is working as intended?

I'm not sure, it might not

**Comment by Revadike** [comment]
> I was thinking about that, I will probably drop no-undef rule. I don't think it's good idea to edit ruleset each time we add or remove class.

It is a good and useful rule, though. Maybe there is a modified version of the rule that better fits our situation.

> do you have ESlint up to date?

Yes, I thought this too, but it still occurs after running `npm update eslint -g`.

> Why? What do they do?

Check the docs on those environments. They seem fitting, no?

> Will check

Ok, don't forget.

> What rule is that?

https://eslint.org/docs/rules/padded-blocks

> About keys, I believe I set it to "consistent", what's the argument for forcing quotes?

https://eslint.org/docs/rules/quote-props
```
        "quote-props": ["error", "always"],
```

> Why would we want empty functions?

Check the code. There is at least one occurrence where this is used.

**Comment by tfedor** [comment]
> Check the docs on those environments. They seem fitting, no?

We don't use CommonJS. webextesions seems like it just sets globals so that might be ok

Ad padded-blocks, I believe this is best to leave up to programmer.
quote-props, not sure why you're sending me link to docs?

> Check the code. There is at least one occurrence where this is used.

If you know of example, can you show me one?

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/70332376-bcefe280-1841-11ea-9e11-025c4549f1d4.png)
![image](https://user-images.githubusercontent.com/4411977/70332426-d42ed000-1841-11ea-98a8-1c87fbcecb1e.png)

**Comment by tfedor** [comment]
All those look like they could be handled better, so I stand by the setting

**Comment by Revadike** [comment]
I implemented some of what we discussed above:
```json
        "arrow-spacing": "error",
        "block-scoped-var": "error",
        "block-spacing": "error",
        "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
        "camelcase": "warn",
        "comma-spacing": ["warn", { "before": false, "after": true }],
        "comma-style": "error",
        "consistent-return": "error",
        "consistent-this": ["error", "that"],
        "curly": ["error", "all"],
        "default-param-last": "error",
        "dot-location": ["error", "property"],
        "dot-notation": "error",
        "eol-last": "error",
        "eqeqeq": ["error", "smart"],
        "func-call-spacing": "error",
        "generator-star-spacing": "error",
        "grouped-accessor-pairs": ["error", "getBeforeSet"],
        "implicit-arrow-linebreak": "error",
        "indent": ["error", 4, { "SwitchCase": 1 }],
        "key-spacing": "error",
        "keyword-spacing": "error",
        "lines-between-class-members": "error",
        "max-len": ["error", 120],
        "max-params": ["warn", 4],
        "max-statements-per-line": ["warn", { "max": 2 }],
        "new-cap": "error",
        "new-parens": "error",
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-caller": "error",
        "no-confusing-arrow": ["warn", { "allowParens": true }],
        "no-constructor-return": "error",
        "no-dupe-else-if": "error",
        "no-else-return": "warn",
        "no-empty-function": "error",
        "no-eq-null": "warn",
        "no-eval": "error",
        "no-floating-decimal": "warn",
        "no-implicit-coercion": "warn",
        "no-implied-eval": "warn",
        "no-invalid-this": "error",
        "no-iterator": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-mixed-operators": "error",
        "no-multi-assign": "error",
        "no-multi-spaces": "warn",
        "no-multi-str": "warn",
        "no-nested-ternary": "error",
        "no-new-func": "error",
        "no-new-object": "error",
        "no-new": "warn",
        "no-octal-escape": "error",
        "no-octal": "error",
        "no-param-reassign": "warn",
        "no-proto": "error",
        "no-redeclare": "error",
        "no-return-assign": "error",
        "no-return-await": "error",
        "no-script-url": "warn",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-setter-return": "error",
        "no-shadow": "warn",
        "no-template-curly-in-string": "warn",
        "no-throw-literal": "warn",
        "no-trailing-spaces": ["error", { "skipBlankLines": true, "ignoreComments": true }],
        "no-undef-init": "error",
        "no-unmodified-loop-condition": "warn",
        "no-unneeded-ternary": "error",
        "no-unused-expressions": "warn",
        "no-useless-call": "error",
        "no-useless-concat": "error",
        "no-useless-constructor": "warn",
        "no-useless-return": "error",
        "no-var": "error",
        "no-void": "error",
        "no-whitespace-before-property": "error",
        "object-curly-newline": ["error", { "multiline": true, "minProperties": 0 }],
        "object-curly-spacing": "error",
        "one-var-declaration-per-line": "error",
        "operator-linebreak": ["error", "before"],
        "padded-blocks": ["error", "never"],
        "prefer-const": "warn",
        "prefer-exponentiation-operator": "warn",
        "prefer-regex-literals": "warn",
        "prefer-rest-params": "error",
        "prefer-template": "warn",
        "quote-props": ["error", "always"],
        "quotes": ["error", "double", { "avoidEscape": true }],
        "require-await": "warn",
        "rest-spread-spacing": "error",
        "semi-spacing": "error",
        "semi-style": "error",
        "semi": ["error", "always"],
        "space-before-function-paren": ["error", "never"],
        "space-infix-ops": "error",
        "space-unary-ops": "error",
        "switch-colon-spacing": "error",
        "template-curly-spacing": ["error", "never"],
        "unicode-bom": "error",
        "wrap-iife": ["error", "inside"]
```

**Comment by MxtOUT** [comment]
We now have a config, see https://github.com/tfedor/AugmentedSteam/blob/featureModules/.eslintrc.json
