### ISSUE TITLE
[BUG] An error occurred in the background context.

### ISSUE THREAD

**Issue by MakoSipper** [tfedor/AugmentedSteam#439]
![chrome_2019-08-17_13-04-54](https://user-images.githubusercontent.com/16372995/63214548-d1239e80-c0ef-11e9-82b1-b549bee16553.png)

Not sure what it affects, but I get the red bar with the exclamation mark.

**Comment by Revadike** [comment]
When and where exactly do these errors occur?

**Comment by MakoSipper** [comment]
Every single time on all Steam pages for me, Store and Community alike.

![chrome_2019-08-18_18-58-52](https://user-images.githubusercontent.com/16372995/63230909-51c6c580-c1ea-11e9-84e0-5128f14627d8.png)

And this is how I noticed:

![chrome_2019-08-18_18-59-14](https://user-images.githubusercontent.com/16372995/63230912-5e4b1e00-c1ea-11e9-9e44-4265956698b0.png)

**Comment by MxtOUT** [comment]
That's a server side error

**Comment by MakoSipper** [comment]
Sorry, as an uneducated person in that area I don't know what it means, I just spotted and reported the issue.

Are you saying this is something related to my computer or connection? If it is, sorry for taking your time, and please disregard this.

**Comment by MxtOUT** [comment]
No worries :)

This was just meant to be a note to other developers.
It basically means that the problem is not on your side, it's a problem with our servers.

Feel free to post any other weird stuff you observer, it helps us a lot :)

**Comment by MxtOUT** [comment]
The situation should have improved, as there were some server side changes.
For a better handling of such errors, refer to #271
