### ISSUE TITLE
[BUG] Store note formatting

### ISSUE THREAD

**Issue by MakoSipper** [tfedor/AugmentedSteam#440]
It looked nice before, but now it shuffles buttons around and looks weird

![chrome_2019-08-17_13-07-12](https://user-images.githubusercontent.com/16372995/63214566-003a1000-c0f0-11e9-9cc0-6beebbaa695d.png)

**Comment by Revadike** [comment]
Duplicate of https://github.com/tfedor/AugmentedSteam/issues/421
