### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#448]
Implement the features of https://github.com/AchooLuv/Back-To-The-Top by @Achooluv

**Comment by MxtOUT** [comment]
I don't know how consistent this would be with the Steam layout, which changes a lot

**Comment by Revadike** [comment]
> I don't know how consistent this would be with the Steam layout, which changes a lot

Maybe take something that already exists in steam, that looks like an upwards arrow. So we have less of a chance it not blending in with the current steam look.

**Comment by MxtOUT** [comment]
Where would this function be available?
Only on the front page?

**Comment by Revadike** [comment]
> Where would this function be available?
> Only on the front page?

On all pages that have a scrolling bar.

![](https://github.com/AchooLuv/Back-To-The-Top/raw/master/images/%E6%84%BF%E6%9C%9B%E5%8D%95.gif)
