### ISSUE TITLE
Language query in URL breaks AS

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#453]
Having `?l=dutch` (forcing a Dutch language) in the URL, seems to break the extension. 
![image](https://user-images.githubusercontent.com/4411977/63231761-c6b4f200-c220-11e9-9794-6cf9ec8e6720.png)

**Comment by MxtOUT** [comment]
In what URL?

**Comment by Revadike** [comment]
Any URL with this search parameter added.

**Comment by Revadike** [comment]
![](https://github.com/AchooLuv/Back-To-The-Top/raw/master/images/%E6%84%BF%E6%9C%9B%E5%8D%95.gif)

**Comment by Revadike** [comment]
So, the problem was property `export_props` was not found in the dutch translation when performing `deepAssign`, which led to it trying to assign a value to something `undefined`.
