### ISSUE TITLE
Latam language is missing

### ISSUE THREAD

**Issue by sharkiller** [tfedor/AugmentedSteam#46]
If my store is in latam spanish I get an error:  

![image](https://user-images.githubusercontent.com/712193/52736569-e84ecb80-2fa8-11e9-8864-7b62a4252a85.png)

and in the option, the language is missing: 
![image](https://user-images.githubusercontent.com/712193/52736631-09afb780-2fa9-11e9-870c-218da6de0e3e.png)

Español Latinoamericano (or "latam" as used by steam backend)

**Comment by tfedor** [comment]
Our localizations needs to be updated, but at least I partially fixed it by showing language key instead of "undefined"

**Comment by vgezer** [comment]
> Our localizations needs to be updated, but at least I partially fixed it by showing language key instead of "undefined"

Can you pull the translations from [here](https://crowdin.com/project/enhanced-steam/tr)? Or can you get ownership as well?
