### ISSUE TITLE
Option to open notifications in steam client

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#466]
![image](https://user-images.githubusercontent.com/4411977/68904719-dddf7f00-073e-11ea-9160-8bb522e37e23.png)

**Comment by MxtOUT** [comment]
I'd prefer to just add this Steam icon (as in #486) to the "unread chat messages" row

**Comment by Revadike** [comment]
> I'd prefer to just add this Steam icon (as in #486) to the "unread chat messages" row

What if I want to open the other rows in my client?

**Comment by MxtOUT** [comment]
Wait, this issue is about just adding an action to the "unread chat messages" row, right?
So why do you now talk about other rows?

**Comment by Revadike** [comment]
#486

**Comment by MxtOUT** [comment]
> What if I want to open the other rows in my client?

Ok, but why would you?

**Comment by Revadike** [comment]
Same reason as the "unread chat messages" row.

**Comment by MxtOUT** [comment]
Correct me if I'm wrong, but every other link would just open the same page just in the Steam browser.
No value added

**Comment by Revadike** [comment]
In the client, not the browser and that's the point.

**Comment by MxtOUT** [comment]
Why do people use the browser?
Because the client browser is trash.
Plus, they have AS.
