### ISSUE TITLE
Unrestricted Steam guide editing

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#467]
Implement the features of https://github.com/LiteOnE/Steam-Scripts/blob/dev/Extended-Guide-Editing.user.js by @LiteOnE

Seems Valve has no server check for this.

I don't know how to avoid the title check though. I don't really want to rewrite steam's existing function. I do something with the `v_trim` function perhaps, but not sure what exactly.

**Comment by tfedor** [comment]
Empty titles doesn't seem useful at all, overcoming Steam's length check just may cause uneccessary trouble down the line (if for example Steam starts checking length more properly).

**Comment by LiteOnE** [comment]
Oh, hi there~ Such an old script you found. Quickly about things: empty title was useful for various guides, where no section title was needed and looked gut without that. And regarding section length, it was stable with ~1,000,000 chars (approx. 1 MB as it seems), any more will cause a clean up of the section -- it will become empty after some time.

And I agree with @tfedor , don't try to go beyond "official" limits
