### ISSUE TITLE
"Profile link images" setting "none" doesn't work

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#469]
Seems like it's set to the default "grayscale" instead.

btw, as shown in the image below
![註解 2019-08-20 015059](https://user-images.githubusercontent.com/54083835/63290653-7a3ae680-c2f4-11e9-8bd4-a1d3960dd433.jpg)

the SteamrepCN icon is not affected when set to "colored"

edit: oh it's because the "colored" icon itself is gray.
maybe change it to the purple one? https://steamrepcn.com/

**Comment by candela97** [comment]
possible cause
https://github.com/tfedor/AugmentedSteam/blob/10554b7af9d092ef0fa436dd6da9c4558ff26ec2/options.html#L627
should be `"false"`?

**Comment by candela97** [comment]
some more ideas to improve this setting:
1. make the "grayscale" setting apply to custom link icons as well
2. if the icon URL is left blank, hide the icon

**Comment by Revadike** [comment]
> some more ideas to improve this setting:
> 
> 1. make the "grayscale" setting apply to custom link icons as well
> 2. if the icon URL is left blank, hide the icon

Done :)
