### ISSUE TITLE
"Show the number of items on Wishlist" toggle not working

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#471]
If this is meant to show the number of wishlisted items on profiles, I don't think it's working.
![註解 2019-08-20 015059](https://user-images.githubusercontent.com/54083835/63300373-a4979e80-c30a-11e9-85d2-14d5449d784b.jpg)

**Comment by MxtOUT** [comment]
Ok, do you see any errors in your browser console (F12)?

**Comment by candela97** [comment]
No errors, but after checking the code, I think I know why:
https://github.com/tfedor/AugmentedSteam/blob/10554b7af9d092ef0fa436dd6da9c4558ff26ec2/js/content/community.js#L480

The stat is pulled from Game Collector showcases, so it will not appear on profiles without the showcase.
