### ISSUE TITLE
WSGF Certification icons go off-screen in Chrome 77 beta

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#472]
![註解 2019-08-20 015059](https://user-images.githubusercontent.com/54083835/63300488-eaecfd80-c30a-11e9-8bc5-ecdbbbe5199b.jpg)

might need to make them smaller or implement scrolling

**Comment by Revadike** [comment]
While I agree, a small size would look nicer, they don't go offscreen for me. I tested it on GTA V. On what page did you see this happen?

![image](https://user-images.githubusercontent.com/4411977/63356428-0cc89d80-c368-11e9-899f-186574dfd92c.png)

**Comment by candela97** [comment]
Your image looks just as I thought it should be! But on my side it goes off-screen on every page I tried on Chrome 77.0.3865.35 beta, with all other extensions disabled.
https://store.steampowered.com/app/320140/Absolute_Drift/
https://store.steampowered.com/app/812140/Assassins_Creed_Odyssey/

I tried changing the height value here
https://github.com/tfedor/AugmentedSteam/blob/5c9437581449ef5a0324736b77daf4a5692494ac/js/content/store.js#L1299
`height='60'`
![註解 2019-08-20 015059](https://user-images.githubusercontent.com/54083835/63382670-bd1cbd00-c3cd-11e9-8e9b-cc22a93c8452.jpg)

**Comment by Revadike** [comment]
Can you perhaps check if this bug persists in the stable version of chrome? I just can't seem to replicate it.

**Comment by candela97** [comment]
Stable versions of Chrome & Firefox both work fine, so something must have broke in the current Chrome beta.

**Comment by MxtOUT** [comment]
Closing since this is not AS related

**Comment by Revadike** [comment]
Actually I am now getting this too:
![image](https://user-images.githubusercontent.com/4411977/64998797-d558fc80-d8e5-11e9-806f-9367276b1a71.png)

From here: https://store.steampowered.com/app/368500/Assassins_Creed_Syndicate/

Using Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by MxtOUT** [comment]
Can confirm that

**Comment by candela97** [comment]
Seems to be fixed again on Chrome 78.0.3904.21 beta
