### ISSUE TITLE
Highlight Intermittent Invalid

### ISSUE THREAD

**Issue by vbmnvbn** [tfedor/AugmentedSteam#475]
Highlight Intermittent Invalid
Reinstalling the plugin will solve

**Comment by MxtOUT** [comment]
That is somehow not very helpful, could you explain it more?

**Comment by vbmnvbn** [comment]
https://imgur.com/a/GGNaqkS
This function often fails as shown

**Comment by MxtOUT** [comment]
Do you recognize any patterns when this happens?
Could you look at your console and the [console on your background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page)?

**Comment by vbmnvbn** [comment]
https://imgur.com/a/acpR4BS

The owned game store name does not display green

**Comment by MxtOUT** [comment]
Did you enable highlighting owned games?
If you just bought the game it can take some time to update

**Comment by vbmnvbn** [comment]
I have   enable highlighting owned games 
and I have bought the game  long ago 

chrome 77.0.3865.90

https://imgur.com/a/BMWcsQe
As shown Red exclamation mark in white circle
it show "1 request failed to send, please open the browser developer console for details"

then Press F12   show
https://imgur.com/a/WhLCNFh
   console.warn("The key %s doesn't exists in the English localization file", key);

I don't quite understand  Is it because of this reason?

**Comment by MxtOUT** [comment]
No, that's because of the "An error occurred in the background context".
Could you inspec the background page for errors?

**Comment by Revadike** [comment]
> how to inspect the background page?

https://github.com/tfedor/AugmentedSteam/wiki/Debugging

**Comment by vbmnvbn** [comment]
> No, that's because of the "An error occurred in the background context". Could you inspect the background page for errors?

https://imgur.com/a/LtwLCv0

**Comment by vbmnvbn** [comment]
> No, that's because of the "An error occurred in the background context". Could you inspect the background page for errors?

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

**Comment by vbmnvbn** [comment]
Can this problem be solved?

**Comment by MxtOUT** [comment]
Anything else on the background page?
Since this is a cookie problem, this may be related to #519 
I'm just wondering about the inconsistency

**Comment by vbmnvbn** [comment]
problem solved
