### ISSUE TITLE
Sync options across browsers

### ISSUE THREAD

**Issue by azumukupoe** [tfedor/AugmentedSteam#48]

**Comment by KarlCastle** [comment]
The options you set on the Options page should already be synced to your browser account, so if you log into Google Chrome with your Google account, then every PC with Chrome that you're logged into with the same account should share those settings. Similarly with Firefox Sync.

It's not possible to sync between two browsers from different vendors (ie Chrome, Firefox, Vivaldi, Opera, ...)
