### ISSUE TITLE
Some descriptions of achievement bars on "all games" page are translated and some not

### ISSUE THREAD

**Issue by DagiLajki** [tfedor/AugmentedSteam#490]
As in title I got descriptions in two languages... my native Polish and English why ?

Is this an easy fixable?

![obraz](https://user-images.githubusercontent.com/38035844/63499170-9c389280-c4c7-11e9-8e33-2ea286f83ddd.png)

**Comment by candela97** [comment]
Looks like `achievements.summary` isn't localized in Polish yet.

The localization string AS implemented is only used on games with leaderboards, so the ones without will display the approved translation from the Steam Translation Server.

Besides, all of that code in AS won't be necessary if VALVE FIXES THE DAMN TRANSLATION STRING

**Comment by Revadike** [comment]
> if VALVE FIXES THE DAMN TRANSLATION STRING

They won't. They'll let the community do that: https://translation.steampowered.com/

**Comment by MxtOUT** [comment]
It looks like only the first part is not translated by Steam
![image](https://user-images.githubusercontent.com/14999077/64173668-179b2c00-ce58-11e9-840f-bbf374cfde56.png)

**Comment by candela97** [comment]
yeah it's the page that's broken, not the translation

Only half of it is on STS, that's why only half appears translated. This can be fixed on Valve's end by using the same string used on games _without_ leaderboards, but Valve.
