### ISSUE TITLE
"Reset options" causes sidebar duplication

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#492]
![image](https://user-images.githubusercontent.com/4411977/63618827-4d851880-c5ed-11e9-8b50-70995935cc0b.png)

**Comment by Revadike** [comment]
@MxtOUT it's still not entirely fixed. In show language different than option it still duplicates the text in between brackets:
![image](https://user-images.githubusercontent.com/4411977/64481148-59b8ca80-d1d6-11e9-9c0c-e4d44a71eca6.png)

**Comment by candela97** [comment]
The custom links under "Show profile links to" section also malfunctions on options reset: all links get cleared, and clicking on "Add custom link" generates multiple default links, at least until you reload the page.

**Comment by MxtOUT** [comment]
Well, that profile links issue should already be fixed with 79a13c19
