### ISSUE TITLE
[SUGGESTION] Add "View stats" link to own achievements on Activity

### ISSUE THREAD

**Issue by MakoSipper** [tfedor/AugmentedSteam#502]
Similar to the (Compare) link that shows close to friends' achievements, I'd love to have a similar (View stats) link to my own achievements on the activity page, close to the achievements I've unlocked.

Thank you for reading, and for taking good care of Augmented Steam!

**Comment by candela97** [comment]
👍 Can be done in the compare link feature itself. Question is: should this be added by default, use and reword the existing option or a new option? I'm in favor of simply using and rewording the existing "show achievement compare links" option.

**Comment by MxtOUT** [comment]
Yes, I'm also for rewording the current option label
