### ISSUE TITLE
Remove redundant features

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#504]
Seems Valve is planning to implement some of the features offered by AS. They should be removed from AS, once they get implemented to Steam natively.

 - [x] Store search infinite scrolling
 - [x] Store search owned filter
 - [x] Store search ignored filter
 - [x] Store search wished filter
 - [x] Store search price filter
 - [x] More?

Source:
https://twitter.com/SteamDB/status/1167487329616957441
https://twitter.com/SteamDB/status/1167487492037193729

**Comment by Revadike** [comment]
Update: [Steam released the new features to the public](
https://steamcommunity.com/games/593110/announcements/detail/1714119088658959584)

**Comment by Revadike** [comment]
Also:
 - [ ] Store search tag filter
 - [ ] Store search discounted

That should be it. 
You may consider keeping or merging the price filter, since it works more precisely than valve's filter.

**Comment by Revadike** [comment]
Tracker: https://github.com/tfedor/AugmentedSteam/compare/edd764d...develop
You're doing a great job @MxtOUT !

**Comment by Revadike** [comment]
I've tested it and everything seems to be working, except hiding items in cart. Steam wasn't tagging the app in search either.

**Comment by Revadike** [comment]
Also, I found that the localization for "hide" was still needed for this:
![image](https://user-images.githubusercontent.com/4411977/77378631-c791a180-6d76-11ea-9240-4428c1979fdd.png)

**Comment by MxtOUT** [comment]
> I've tested it and everything seems to be working, except hiding items in cart. Steam wasn't tagging the app in search either.

You mean the search result row was not flagged with `.ds_cart`?
Then there is not much we can do about that

**Comment by Revadike** [comment]
Correct
