### ISSUE TITLE
[Suggestion] Discussion Forum Link

### ISSUE THREAD

**Issue by SpyderZT** [tfedor/AugmentedSteam#507]
Getting to the Steam Discussion forum takes either two pages of navigation (Community Hub > Discussions) or a Scroll down and hunt for the tiny link on the right side of the page:

![image](https://user-images.githubusercontent.com/14990202/64071086-d2dc7e80-cc26-11e9-8e36-75b3f7ef7294.png)

It would be amazing to have a link to the Forum right up top by splitting the "Community Hub" link in half:

![image](https://user-images.githubusercontent.com/14990202/64071099-0919fe00-cc27-11e9-8f7c-a3dbb7b0aa5a.png)

**Comment by Revadike** [comment]
Maybe add a setting to change the default "Community Hub"-button link to your favorite tab instead?
