### ISSUE TITLE
hide broadcasts from store pages

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#508]
Example store page currently broadcasting:
https://store.steampowered.com/app/814370/Monster_Sanctuary/

I suggest adding an option to the customize button on store pages to disable the broadcast banner/window, and the mini player that pops up when you scroll down.

There's actually an option in Account Preferences to disable these, but it doesn't seem to work.

**Comment by Revadike** [comment]
> There's actually an option in Account Preferences to disable these, but it doesn't seem to work.

Works just fine by me:
![image](https://user-images.githubusercontent.com/4411977/64079963-d8050080-ccee-11e9-91f6-4872ea5aab82.png)

**Comment by candela97** [comment]
Oh ok so it works. I was thinking of adding an option to hide it completely, and to hide it for users that are not logged in.

**Comment by thomas-ashcraft** [comment]
I'd like to have such option. Sometimes (lets be honest - each major sale) I open a hell of a lot tabs with those discounted games, and it start to devour RAM because those "dev's broadcastings" on almost each page at sales time.

**Comment by Revadike** [comment]
I think it is possible by blocking the web request `https://store.steampowered.com/broadcast/ajaxgetstreamersforpage` with the `webRequestBlocking` permission.

**Comment by andrewpros** [comment]
Due to security i never log in on steam website, i use pc client, so i cant disable this with account options.
Those broadcasts are very annoying, we should have and option to completely remove this, so im +1 for this. On the bright side, it looks like easy to add.

**Comment by Revadike** [comment]
There once was an Enhanced Steam for the client, which was pretty cool. It didn't last long though.

**Comment by Revadike** [comment]
Since @rafaelgssa has experience with `webRequestBlocking` now, perhaps he will be interested in picking up this PR as well?

**Comment by rafaelgssa** [comment]
Sure, I can pick this up.

**Comment by rafaelgssa** [comment]
This won't be possible, as Augmented Steam uses event pages instead of background ones, and they don't work with `webRequest`.

**Comment by MxtOUT** [comment]
As long as you do it dynamically, it is fine I think, you can't just intercept requests that are immediately executed.

When are these broadcasts loaded?

**Comment by Revadike** [comment]
Is it not possible to make a global rule to block any request to ` https://store.steampowered.com/broadcast/ajaxgetstreamersforpage`?

**Comment by MxtOUT** [comment]
Adblockers probably have a persistent background page

**Comment by andrewpros** [comment]
Why so much trouble, just remove the broadcast section and if it then still needed, stop the broadcast stream, the is no need to work like adblockers.

**Comment by MxtOUT** [comment]
It uses network resources, CPU time and RAM, that's why.
But I don't think we have another choice

**Comment by andrewpros** [comment]
No, i dont get from where it comes, it just easy remove broadcast html and if when it still streams then it needs to be found where and just close the stream.

**Comment by MxtOUT** [comment]
Yes, but before AS loads, a gpod amount of resources are already dedicated to the stream

**Comment by andrewpros** [comment]
Not really, it just streams, that's not many resources, if u close it, it just stops and all resources are free, we just need to close the stream and remove the broadcast html.
We cant do many things before AS loads, but after that it can do anything.
There is a slight delay on steam when the broadcast initializes, so maybe all it takes is to remove the html, steam wont find it so it wont initialize the broadcast, if it works that way, i didn't analyze steam js yet.
If not, then there are plenty of other ways.
We just need to look up how the broadcast is initialized and break it.

**Comment by rafaelgssa** [comment]
I just tested and removing the HTML element does not prevent the requests from happening.

**Comment by MxtOUT** [comment]
> Not really, it just streams, that's not many resources

I don't actually know what could take more resources

**Comment by andrewpros** [comment]
Yeah, removing html does not stop it, but it will be removed anyway, now we only need to find out whats beneath that show/hide broadcast and just do the same, either stop it or even better, find the init code and check if it can be blocked even before initializing. (the html and stream, as i can see, the html code is appended after some delay)
Resources was never an issue, end user will not even see it and it will be stopped immediately behind the scenes.
I will check the steam js.

**Comment by andrewpros** [comment]
Ok, found out there is a global object uiBroadcastWatchStore

And this code stop the stream uiBroadcastWatchStore.m_activeVideo.Stop();

Will do more digging, looks like good entry point.

**Comment by Revadike** [comment]
Yeah, I was wondering if something like that existed.
If you want to implement it into Augmented Steam, do it like this:
```js
ExtensionLayer.runInPageContext(function(){ uiBroadcastWatchStore.m_activeVideo.Stop(); });

**Comment by andrewpros** [comment]
Even better, found out
uiBroadcastWatchStore.m_broadcastInfos = null;
Stops everything at the start, its not even adding the html, with just 2 error messages in console, but everything else works.

**Comment by andrewpros** [comment]
Will anyone do a PR? I would do it but i think it should be and opt in option as def.

**Comment by Revadike** [comment]
> Will anyone do a PR? I would do it but i think it should be and opt in option as def. Not sure others agree.

I was assuming you'd do it. But I can too. Let me know.

**Comment by andrewpros** [comment]
Then do it, i dont know the code that much so would need to study it before, u will do it faster.

**Comment by Revadike** [comment]
After all the time and effort we all spend on this, it turns out there is a really simple solution that blocks any broadcast from being added without any errors...

**Comment by rafaelgssa** [comment]
That simple? I thought that wouldn't work because I assumed the element wouldn't be available on page load, but I guess it is?

**Comment by Revadike** [comment]
> That simple? I thought that wouldn't work because I assumed the element wouldn't be available on page load, but I guess it is?

yes it is. It is an empty div. You can check with ctrl+u.

**Comment by Revadike** [comment]
There are also broadcasts on sale pages. These are even more tricky, since the whole page is dynamically generated (not just the broadcast).
