### ISSUE TITLE
Download app store screenshots

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#510]
![image](https://user-images.githubusercontent.com/4411977/64080963-8ebaae00-ccfa-11e9-8ba9-ebe9ada9fe13.png)

This feature was added with https://github.com/tfedor/AugmentedSteam/pull/494, but currently only opens a new tab with the image.
It would be better, if it actually downloaded the image instantly.
This can be easily implemented, once https://github.com/tfedor/AugmentedSteam/pull/371 is merged.
Then we can assign a `click` event that triggers `Downloader.download` function from https://github.com/Revadike/AugmentedSteam/blob/feature-export-wishlist/js/content/common.js#L2123 .

Assign me to this issue.

**Comment by thomas-ashcraft** [comment]
If you really going to make forced download instead of convinient opening full-size image in new tab, then button should become a <a> tag so user can right-click on it and choose "copy link" or "open in new tab" in native browser's menu. Otherwise it will become forcible functionality.

I think it would be enough to:
* change ```<i>``` to ```<a>``` inside ```div.es_screenshot_download_btn``` (don't forget to adjust CSS);
* copying ```href``` from original link (can be easily done through already existing ```modalTitleLink``` variable);
// like:
```javascript
downloadButton.href = modalTitleLink.href;
```
* and in the end make sure to prevent ```preventDefault``` in function for plain click

**Comment by Revadike** [comment]
> then button should become a `<a>` tag so user can right-click on it and choose "copy link" or "open in new tab" in native browser's menu

That's fine, but can't you already do that just by right-clicking the image? That would make more sense to me?

**Comment by thomas-ashcraft** [comment]
> 
> That's fine, but can't you already do that just by right-clicking the image? That would make more sense to me?

That's the trick. They are not the same. Image that showed in modal popup and image that opens in new tab. You can see it when encounter a game with screenshots taken at more then FHD resolution. At least when your own screen have resolution HD, FHD, or between.

Modal popup showing images resized to be lesser than 1920x1080.

Check exactly that one screenshot from here: https://store.steampowered.com/app/392110/Endless_Space_2/
(most of screenshots for that game is FHD in original, but some of them are much bigger)
![Endless Space 2 - 4k screenshot](https://user-images.githubusercontent.com/6583664/64131610-67371480-cdd2-11e9-8248-abd3e6866dc4.png)

When you right-click on showed image, you got this link:
https://steamcdn-a.akamaihd.net/steam/apps/392110/ss_8ab2ac1bae46db5b1b9d70cd090c85c279c457a7.1920x1080.jpg?t=1566505865
Resulting image is having resolution **1920x1045**

When you click "full-size" link, you got this link:
https://steamcdn-a.akamaihd.net/steam/apps/392110/ss_8ab2ac1bae46db5b1b9d70cd090c85c279c457a7.jpg?t=1566505865
Resulting image is having resolution **3827x2048**

**Comment by Revadike** [comment]
Sounds to me that the fullscreen image should be replaced with the higher res one.

**Comment by thomas-ashcraft** [comment]
Thought about it. But my implementation of fullscreen image viewer for Steam was initially intended to be pure CSS as much as possible. No changes for original code. Thats why I didn't bothered to considering such change.

Other reason is, if we change viewer to load unlimited sized images, we potentially increase resource usage where it didn't needed. What I mean...

Steam's hardware survey showing that 63.95% of Steam users have exactly 1920x1080 resolution. 26,52% of users have lesser resolution. Only 7,74% of users have bigger then FHD resolution. And 1.78% is "other". So combined there is 90,47% of users with FHD or lesser screen resolution.

That means there is no need to upscale image resolution in viewer for 90.47% of users. So if implementing such thing at all, it should be on optional terms. Like responsive desing. Code should check the size of viewport and only if it more then FHD, then replace resized image with hi-res version. Here about it: https://stackoverflow.com/a/8876069

**Comment by tfedor** [comment]
I think opening image in new tab is good enough. I am with thomas here that it's not the best idea to change to original resolution either. If it ends up being confusing, we could change the icon for download (make it something like "show original"). This way you will also be able to see full res original image without actually downloading it. Direct download would remove this option.

**Comment by Revadike** [comment]
Yeah just have 2 buttons. One with the download icon to download it and one with an external link icon (![](https://steamcommunity-a.akamaihd.net/public/images/skin_1/ico_external_link.gif)) to open in new tab.

**Comment by thomas-ashcraft** [comment]
> Yeah just have 2 buttons. One with the download icon to download it and one with an external link icon (![](https://camo.githubusercontent.com/6ebc058ecc3924adc1850e68b8450b6d86a66918/68747470733a2f2f737465616d636f6d6d756e6974792d612e616b616d616968642e6e65742f7075626c69632f696d616765732f736b696e5f312f69636f5f65787465726e616c5f6c696e6b2e676966)) to open in new tab.

This may be a good compromise. Original confusing was made by Valve, when they call that link "download". We can make 2 buttons: one is "show full-size in new tab" and the other is "download full-size". Downside there is only that we need to implement 2 new localised strings (current implementation based upon original Valve localisation).

**Comment by Revadike** [comment]
> > Yeah just have 2 buttons. One with the download icon to download it and one with an external link icon (![](https://camo.githubusercontent.com/6ebc058ecc3924adc1850e68b8450b6d86a66918/68747470733a2f2f737465616d636f6d6d756e6974792d612e616b616d616968642e6e65742f7075626c69632f696d616765732f736b696e5f312f69636f5f65787465726e616c5f6c696e6b2e676966)) to open in new tab.
> 
> This may be a good compromise. Original confusing was made by Valve, when they call that link "download". We can make 2 buttons: one is "show full-size in new tab" and the other is "download full-size". Downside there is only that we need to implement 2 new localised strings (current implementation based upon original Valve localisation).

Or we can just use icons.

**Comment by thomas-ashcraft** [comment]
I agree, they should be icons. Just IMHO, tooltips - is a must have thing.
