### ISSUE TITLE
Language warning is always English by default

### ISSUE THREAD

**Issue by thomas-ashcraft** [tfedor/AugmentedSteam#517]
That thing causing inconvenience. Every fresh install, user should goes to "AS" settings and change language to his own by himself. And that is if user knows about such feature in "AS" at all. I bet most are not.

Anyway, this is inapropriate behavior. If that feature turned on by default it must detect user's language from Steam settings.

Can be related: https://github.com/tfedor/AugmentedSteam/issues/12

![Language warning screenshot](https://user-images.githubusercontent.com/6583664/64278956-9ffff680-cf56-11e9-83f0-366a866dae78.png)

**Comment by MxtOUT** [comment]
Yup, I also thought about that once a user had problems with this setting after a fresh install on Discord
