### ISSUE TITLE
"Costs more than" filter not working. 

### ISSUE THREAD

**Issue by hadbabits** [tfedor/AugmentedSteam#518]
I can't get the "Costs more than" filter to work. Whatever number I enter, the tag is left incomplete at the top without an amount: 

https://i.imgur.com/WecVv1v.png

The other filters seem to be working. I've also noticed if I try entering a letter or illegal character I still get an appropriate tool-tip warning under the text field. 

I'm using Firefox 68.0.2 on Linux 64bit. 

Edit: lil update: issue still present on Firefox 69

**Comment by candela97** [comment]
Problem with regex perhaps?
https://github.com/tfedor/AugmentedSteam/blob/c787dbab6998f8bc314ce71f2f27acad4acb1cdd/js/content/store.js#L2595
Also I don't think it takes into account currencies that don't have decimal separators and/or uses commas for thousands separators.

Steam has already implemeted a similar feature: https://store.steampowered.com/labs/search?snr=1_2500_4_
although it seems like you can only set the price in increments of $5.

**Comment by MxtOUT** [comment]
> Also I don't think it takes into account currencies that don't have decimal separators and/or uses commas for thousands separators.

According to currency.json there is no currency (that we support at least) that doesn't have decimal separators.
And yes, we don't account thousand separators because there are almost no products that have such high prices.

>Steam has already implemeted a similar feature: https://store.steampowered.com/labs/search?snr=1_2500_4_
although it seems like you can only set the price in increments of $5.

Yes, still thinking about how to handle this.
Replace it with our filter when the time has come?

**Comment by Revadike** [comment]
Or a hybrid: For example, if you filter on <$1, apply steam's <$5 and then filter those results further.
Also, maybe steam will add more precise price filters in the future.

**Comment by MxtOUT** [comment]
> Or a hybrid: For example, if you filter on <$1, apply steam's <$5 and then filter those results further.
> Also, maybe steam will add more precise price filters in the future.

From the [infinite scroll feedback thread](https://steamcommunity.com/groups/SteamLabs/discussions/4/1636418037464671886/):
> The search knows up-front how many games there are, but what it doesn't know how many are already in your library/wishlist/ignore-list, as we do that filtering on-the-fly (as results are loaded into your browser).

They seem to filter it on the client side too, so we wouldn't benefit more from letting their filter run first

**Comment by Revadike** [comment]
> They seem to filter it on the client side too, so we wouldn't benefit more from letting their filter run first

I think that's just for the library/wishlist/ignore-filter. I saw in the ajax request the price filter being applied.

**Comment by candela97** [comment]
> According to currency.json there is no currency (that we support at least) that doesn't have decimal separators.

For many currencies they're only used in banking, as fractions are no longer in circulation, and not displayed in prices.
> And yes, we don't account thousand separators because there are almost no products that have such high prices.

But you have to consider currency conversions, right? I think AS should at least support the currencies that Steam provides.
Here're some currencies that might be broken now:
![註解 2019-09-09 045432](https://user-images.githubusercontent.com/54083835/64494325-eee2be80-d2bd-11e9-9709-ea8b16ff7c06.jpg)

**Comment by hadbabits** [comment]
For the record I also tried entering whole numbers to no avail.

What more info is needed MxtOUT?

**Comment by MxtOUT** [comment]
@hadbabits So I believe I fixed this problem:
The cause of this was that we constrained the price strings of each product to start with a digit, but your currency prefixes the currency symbol, thus it would be always seen as a game without a price

**Comment by hadbabits** [comment]
@MxtOUT Right on. I'll let you know once it gets updated on FF :)
