### ISSUE TITLE
Addon broken with 'Third Party Cookies' disabled in Firefox

### ISSUE THREAD

**Issue by BlueRaja** [tfedor/AugmentedSteam#519]
Repro steps:
1. Open Firefox, disable third party cookies (tools --> options --> Privacy and Security --> Cookies --> All Third Party Cookies)
2. Visit the store page for any game you have on your wishlist
3. Click on the "Wishlist" button

Expected results:
Game is removed from your wishlist.

Actual results:
Augmented Steam makes it look like it's been removed, but if you visit your wishlist (or refresh the store page), it hasn't been

Note: Many other features are broken too, this is just a simple one.

**Comment by BlueRaja** [comment]
The cause appears that Firefox is not including cookies in the XHR to `https://store.steampowered.com/api/removefromwishlist`. I'm not sure why this is, since that's not a third-party URL.  I'm guessing Firefox is considering the addon as the "third party"??

Chrome does not have this issue with third party cookies disabled, so I'd probably say this is a Firefox bug...

**Comment by MxtOUT** [comment]
Also see #169

**Comment by MxtOUT** [comment]
[This dude](https://bugzilla.mozilla.org/show_bug.cgi?id=1579347#c5) is nuts, full credits go to him!

**Comment by MxtOUT** [comment]
@BlueRaja Thanks for opening that report!
