### ISSUE TITLE
"Make sure that you are logged into steamcommunity.com in order to be able to use all features of Augmented Steam."

### ISSUE THREAD

**Issue by BlueRaja** [tfedor/AugmentedSteam#520]
For some reason I see this error message at the top of [this store page](https://store.steampowered.com/app/342550/Phantasmal_Survival_Horror_Roguelike/).  Yes, I'm logged into steamcommunity.com

I have that game wishlisted _and_ ignored, but not owned.  I'm not seeing it on other store pages that I've tried, even after wishlisting+ignoring.

Browser: Firefox (I don't repro in Chrome)

**Comment by telans** [comment]
https://github.com/tfedor/AugmentedSteam/issues/479#issuecomment-528678126

**Comment by MxtOUT** [comment]
Duplicate of #479

**Comment by Revadike** [comment]
Maybe improve title of issue #479 ?
