### ISSUE TITLE
[SUGGESTION] Add an option to disable getting average price of items

### ISSUE THREAD

**Issue by Ryzhehvost** [tfedor/AugmentedSteam#523]
If someone needs more than one extension, both extensions can simultaneously try to get item price from trade market, and in case of huge amounts of items (like trade market or inventory) this will easily cause temporal block from steam because of rate limiting. So, it would be nice to make it configurable, to make AS not trying to get item prices on trade market.

**Comment by MxtOUT** [comment]
Wait, do you mean these prices?
![image](https://user-images.githubusercontent.com/14999077/64480960-32acc980-d1d3-11e9-978c-e668681c5c80.png)
Because they are not average prices, they are lowest prices.

**Comment by Ryzhehvost** [comment]
Yes, I meant those.

**Comment by MxtOUT** [comment]
Ok, will add this option later
