### ISSUE TITLE
Curator/Publisher/Developer pages fix

### ISSUE THREAD

**Issue by kirara** [tfedor/AugmentedSteam#528]
Steam recently upgraded curator pages with infinite scroll and it seems they break the layout on some of them in the proces.
![image](https://user-images.githubusercontent.com/445704/64496624-7a048a00-d2a7-11e9-842c-472f552b8b20.png)
Could you maybe fix it before Steam does?
Either way, highlights stopped working there.

**Comment by MxtOUT** [comment]
![image](https://user-images.githubusercontent.com/14999077/64526260-1b6cf980-d303-11e9-9ce8-a22a0a5353ac.png)
