### ISSUE TITLE
Blank game page on Steam

### ISSUE THREAD

**Issue by garyking** [tfedor/AugmentedSteam#529]
Most game pages work fine on Steam, but [the one for *Kingdom Come: Deliverance*](https://store.steampowered.com/app/379430/Kingdom_Come_Deliverance/) is blank. 

The page works fine in Chrome incognito mode, with all extension disabled.

I've attached a screenshot of what it looks like when I go there.

![Steam - Kingdom Come](https://user-images.githubusercontent.com/343940/64548860-7bf93800-d2fd-11e9-8cf9-4f5ac097349d.png)

**Comment by MxtOUT** [comment]
Hm, that's weird to say at least.
I don't think that this has something to do with AS if I'm honest.

Have you restarted everything, cleared caches and so on?
Does this happen without AS?

**Comment by Revadike** [comment]
Yes, I have this happen too. Its caused due to some steam cookie. You gotta clean your cookies. This is why I suggested this: https://github.com/tfedor/AugmentedSteam/issues/477

**Comment by garyking** [comment]
Okay thanks, clearing the coookies worked. 

So the problem is related to Steam cookies, and has nothing to do with AS at all? Or is a combination of the two?

**Comment by Revadike** [comment]
> Okay thanks, clearing the coookies worked.
> 
> So the problem is related to Steam cookies, and has nothing to do with AS at all? Or is it a combination of the two?

Well next time try disabling the extension, while retaining the same cookies.
