### ISSUE TITLE
Horizontal scroll bar

### ISSUE THREAD

**Issue by GabsletobarLT** [tfedor/AugmentedSteam#537]
**After install the Augmented Steam extension** I have a horizontal scroll bar at the bottom. When I disable the extension it goes back to normal (no horizontal scroll bar) so I assume it is an issue with the extension.

If it matters my laptop resolution is: 1366x768

Screenshots to you understand better:

![Inkedsteam1_LI](https://user-images.githubusercontent.com/47039784/65176914-9ba30580-da4d-11e9-955c-241737453953.jpg)

![Inkedsteam2_LI](https://user-images.githubusercontent.com/47039784/65176924-9fcf2300-da4d-11e9-99db-255db41595a3.jpg)

**Comment by MxtOUT** [comment]
Hm, I can't see such thing with your settings, but your page seems bugged anyway.
Did this resolve?
![image](https://user-images.githubusercontent.com/14999077/65520773-6d5b7500-dee8-11e9-97b7-0e75b59e662a.png)

**Comment by GabsletobarLT** [comment]
Thanks for the reply.

It only happens when steam has those big banners (like the screenshot -> frontier 25years) . 
Right now I don't have too.

**Comment by GabsletobarLT** [comment]
@MxtOUT if you try now with the THQNordic banner it should have the horizontal bar.

**Comment by MxtOUT** [comment]
Sorry, missed that one...

**Comment by Revadike** [comment]
> Sorry, missed that one...

I tried it. I found it only had horizontal scrolling at certain resolutions.

**Comment by candela97** [comment]
This might have to do with the "Customize" section, which seems to prevent Steam from correctly adjusting page elements at certain resolutions. I made a feature request (#509) to move this section to a more noticable position.
