### ISSUE TITLE
Some i18n changes

### ISSUE THREAD

**Issue by deluxghost** [tfedor/AugmentedSteam#542]
change `"1-Click " + turnWord ` to an i18n entry
https://github.com/tfedor/AugmentedSteam/blob/2d0d63d5830795c742b95e5fa9bb3ae6b7c8a8f8/js/content/community.js#L1698

remove `Hide` here because it has an options title `Hide`
https://github.com/tfedor/AugmentedSteam/blob/7dd2d3fad6a0adcff042240a8cfe950e56a41e10/localization/en/strings.json#L435

`Other` and `Images`
https://github.com/tfedor/AugmentedSteam/blob/7dd2d3fad6a0adcff042240a8cfe950e56a41e10/options.html#L909-L910

**Comment by Revadike** [comment]
I guess "implements" is not a keyword github recognizes to close this issue.
@MxtOUT this issue can be closed now.
