### ISSUE TITLE
Information position in the wishlist

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#544]
Maybe put the information under the product is better than on the product?
Because I install the "ITAD Everywhere", so when the mouse hovers over product, the layout will change, it caused the icon to change its position.

![image](https://user-images.githubusercontent.com/5698157/65230365-4ffd6400-db00-11e9-9f68-e84b43b3a595.png)

**Comment by mezzode** [comment]
Opened a PR that should work, but lmk if something's wrong with it.
