### ISSUE TITLE
screenshot thumbnails are not loading correctly (last update)

### ISSUE THREAD

**Issue by Evil-Raveen** [tfedor/AugmentedSteam#545]
With the last update began to load incorrectly screenshots thumbnails
before https://i.imgur.com/JuXa7nF.jpg 
after https://i.imgur.com/vVqbCF0.jpg

**Comment by MxtOUT** [comment]
@Revadike Any ideas on how to avoid that?

**Comment by Revadike** [comment]
> @Revadike Any ideas on how to avoid that?

No idea so far

**Comment by Revadike** [comment]
> @Revadike Any ideas on how to avoid that?

Lowering `min-height` would be fine. It just has to be high enough so it can be clicked (in case of long images).
