### ISSUE TITLE
Community profile center column slightly broken; bumped down 20px

### ISSUE THREAD

**Issue by Blutzen** [tfedor/AugmentedSteam#554]
When loading a community profile page you can watch the blue banner/header at the top of the page expand down exactly 20 pixels, which is odd behavior I don't really understand the necessity of, but beyond just being a weird quirk it breaks profile backgrounds by causing a misalignment in the entire center column.  

Here's an example from my own profile using a background that should easily show the error: 
![image](https://user-images.githubusercontent.com/55936273/65825679-b2184080-e247-11e9-80b1-a76f5c026c13.png)

**Comment by MxtOUT** [comment]
I can't reproduce this, could you give me your window size and the link to your Steam profile?

**Comment by Blutzen** [comment]
I noticed the 20px bump down happening on every profile I visited, and just re-tested another 10. It happens at the very end of page load, the bottom of the banner just expands down 20px for no apparent reason; there is nothing extra loading in that I can see to force it larger. 

I'm running Chrome v77.0.3865.90 on a 1920x1080 monitor, Window size (measured via alt+print screen to screen grab only active window) is maximized at 1846x1080 but resizing the window is not changing anything.

My profile link is https://steamcommunity.com/id/FFIXMaster/ if you think it's still helpful, and here are a few examples showing the difference between the page loaded with the extension disabled vs enabled on different profiles using different customization elements.

![hrpg](https://user-images.githubusercontent.com/55936273/65839433-8f376c00-e2db-11e9-854a-71c19ea052c5.gif)

![mine](https://user-images.githubusercontent.com/55936273/65839434-92325c80-e2db-11e9-8172-39bffd38b05a.gif)

![modgen](https://user-images.githubusercontent.com/55936273/65839438-95c5e380-e2db-11e9-99e6-d648e76a88dc.gif)

**Comment by candela97** [comment]
This has to do with the "Show SteamRep status on profile pages" option, so you can disable it if this is a constant issue.

There're checks in place that prevents creating this section if the profile has "No special reputation", but after checking a bunch of random profiles, I found that `data.steamrep` can sometimes contain an empty string, which passes the check.

**Comment by MxtOUT** [comment]
So, `data.stemrep` sometimes contains an array `[""]`.
I could reproduce it once, but I don't know why it changes that often for me...

**Comment by MxtOUT** [comment]
Alright, I'm not really sure about this, could you try clearing your cache by selecting "Clear cached data" in the dropdown menu of Augmented Steam?

**Comment by MxtOUT** [comment]
In any case, this is a server problem
