### ISSUE TITLE
Wrong conversion (?) in price comparison

### ISSUE THREAD

**Issue by scese250** [tfedor/AugmentedSteam#555]
![image](https://user-images.githubusercontent.com/12405564/65852302-bb76db00-e323-11e9-9f4b-7104062a2c7f.png)

**Comment by RahFael** [comment]
Same issue here. The conversion from Argentina Currency is wrong.

**Comment by MxtOUT** [comment]
@tfedor I don't know where the conversion rates are pulled from

**Comment by MxtOUT** [comment]
Conversion rates got an update, could you check again?

**Comment by scese250** [comment]
Fixed.
