### ISSUE TITLE
«Export Wishlist» doesn't work.

### ISSUE THREAD

**Issue by Tatsugi** [tfedor/AugmentedSteam#556]
I don't know can be it because over 1k games in my wishlist or not. Disabling Adblock and similar addons doesn't help. (Firefox Quantum 69.0.1 x64)

**Comment by Revadike** [comment]
> I don't know can be it because over 1k games in my wishlist or not. Disabling Adblock and similar addons doesn't help. (Firefox Quantum 69.0.1 x64)

What exactly isn't working? Does the button show up? Does the download button work? Does the copy button work? More info needed please.

**Comment by Revadike** [comment]
Maybe it's a firefox issue.

**Comment by Tatsugi** [comment]
> 
> 
> Maybe it's a firefox issue.

Yes it is. Just tested in chromium Microsoft Edge and was able to export the wishlist.

**Comment by mezzode** [comment]
FWIW it worked on Firefox Dev Edition (i.e. Firefox 70)

**Comment by MxtOUT** [comment]
Ok, the problem with the clipboard is that the clipboard function is called outside of a short-lived event handler for a user action.
Thus, Firefox will deny that action.

You could circumvent that by adding the `clipboardWrite` permission or by moving the relevant code into such handler.

**Comment by MxtOUT** [comment]
And the `Downloader` wasn't working because `a.click()` doesn't seem to be sufficient for FF, you have to explicitly call `a.dispatchEvent(new MouseEvent("click"))` for it to work
