### ISSUE TITLE
[Suggestion] Filter subscribed workshop items based on whether or not you have all the required items to run it

### ISSUE THREAD

**Issue by forealdo25** [tfedor/AugmentedSteam#56]
It would be good for those of us who have a lot of workshop mods and who want to check all the mods we're subscribed to are up to date with what they need.

**Comment by forealdo25** [comment]
Another good addition would be for when you try to subscribe to something on the workshop and it tells you that you need some additional items, we could just press a button that subscribes to them all, rather than just having to go to each of their pages one by one and subscribe to them.

**Comment by Revadike** [comment]
Could you provide some examples?

**Comment by forealdo25** [comment]
> Could you provide some examples?

I guess a good example would be if you decide to unsubscribe from a lot of workshop mods, but it turns out that some of the stuff you unsubbed from were needed for other mods. While you could potentially discover this when you try to use the mod, I think a better way to find out would be of you could search for it in your subscribed mods, especially since mods can add dependencies after you subscribed to them.

**Comment by Revadike** [comment]
>  some of the stuff you unsubbed from were needed for other mods.
Please provide concrete examples for `some of the stuff you unsubbed from` and `other mods`. 
That said, if there is no good way to distinguish dependencies among mods, I don't think we can do anything about that.

**Comment by forealdo25** [comment]
I suppose a good example would be this asset [https://steamcommunity.com/sharedfiles/filedetails/?id=1457697227](url). I unsubbed from it because I believed it was unnecessary, but I soon learned it was needed for this asset [https://steamcommunity.com/sharedfiles/filedetails/?id=1482575675](url).

**Comment by Revadike** [comment]
Where does it say `Plaenterwald Station` needs `S-Bahn Cube + Plänterwald Sign`?

**Comment by forealdo25** [comment]
It says so in the list of required items on the right for Plaenterwald Station, under the details.

**Comment by Revadike** [comment]
Okay, yes I see it:
![image](https://user-images.githubusercontent.com/4411977/74598202-7999c780-506d-11ea-97f5-c638e49c27eb.png)

Unfortunately, as far as I can see, this information is only available in the page itself. This means in order to implement your suggestion, we'd need to scape all search results and then apply the filter. This is recourse intensive and far from ideal. Is that worth it?

**Comment by forealdo25** [comment]
If it's very resource-intensive, then not really. Thanks for at least looking into it.

**Comment by Revadike** [comment]
I actually found an API that can do this too, which is good news.
`https://api.steampowered.com/IPublishedFileService/GetDetails/v1/?key=:APIKEY&publishedfileids[0]=1482575675&includechildren=1&includetags=0&includeadditionalpreviews=0&includekvtags=0&includevotes=0&short_description=0&includeforsaledata=0&includemetadata=0&return_playtime_stats=0&strip_description_bbcode=1`

**Comment by Revadike** [comment]
@forealdo25 can you be a bit more specific on where you'd like to see an enhancement?

Like, would you like to see subscribe all button here?
![image](https://user-images.githubusercontent.com/4411977/79149676-cd076800-7dc7-11ea-9a7e-fc10fcf36c66.png)

Anything else?

**Comment by forealdo25** [comment]
That is exactly what I would like. If there was a "Subscribe All" button, it would make getting all the required items less tedious. I don't think anything else would be necessary.

**Comment by forealdo25** [comment]
@Revadike  That is exactly what I would like. If there was a "Subscribe All" button, it would make getting all the required items less tedious. I don't think anything else would be necessary.

**Comment by Revadike** [comment]
> @Revadike That is exactly what I would like. If there was a "Subscribe All" button, it would make getting all the required items less tedious. I don't think anything else would be necessary.

Alright then. In that case the API isn't even neccesary.

**Comment by forealdo25** [comment]
@Revadike Good to hear! Thanks for the update.

**Comment by MxtOUT** [comment]
I think @forealdo25 means a "Subscribe All" button on the list view, right?

**Comment by MxtOUT** [comment]
I'm still confused about the original request, where should they get filtered?

**Comment by forealdo25** [comment]
> I think @forealdo25 means a "Subscribe All" button on the list view, right?

Yeah, that's pretty much what I mean.

**Comment by forealdo25** [comment]
> I'm still confused about the original request, where should they get filtered?

They should get filtered in the list of subscribed items. Steam recently let you filter your subscribed stuff using workshop tabs, so another tab could be included there for stuff that's missing dependencies.

**Comment by MxtOUT** [comment]
> Alright then. In that case the API isn't even necessary.

We're talking about two different requests here:

The first (original) was to filter your subscribed workshop items to those that are missing dependencies (somewhere like here I guess)
![image](https://user-images.githubusercontent.com/14999077/110638615-0e0e2500-81af-11eb-8041-85e8797c77da.png)
This doesn't seem feasible to me due to the expenses (one request per item).
The feature would only become more useful for users with a larger library, which would result in a longer time to filter and a higher probability of hitting API limits.

The second request was implemented by https://github.com/tfedor/AugmentedSteam/commit/5b04581744df735d4ff678c5db6622941a8a357a
