### ISSUE TITLE
AS displays Early Access overlay even though the game has already left Early Access

### ISSUE THREAD

**Issue by MarcinDAGS** [tfedor/AugmentedSteam#564]
AS displays Early Access overlay text even though the game has already left Early Access a month ago:
https://store.steampowered.com/app/815370/Green_Hell/

![greenhellea](https://user-images.githubusercontent.com/56167171/66221129-a527a100-e6ce-11e9-978a-690f0ee15211.png)

The same happens in the search results:
https://store.steampowered.com/search/?term=green+hell

![greenhellea2](https://user-images.githubusercontent.com/56167171/66221192-c5eff680-e6ce-11e9-8c0a-978fb8ed315a.png)

**Comment by MxtOUT** [comment]
That's a backend problem @tfedor

**Comment by tfedor** [comment]
AS now uses same data as ITAD, and I hope that it is behaving better now. Please reopen if issue still occurs (mind you, there might still be a little delay, but it should be hours max)
