### ISSUE TITLE
[Bug] Search terms with spaces (and probably other encodable chars) break paging of results

### ISSUE THREAD

**Issue by dahauns** [tfedor/AugmentedSteam#568]
Example: 
https://store.steampowered.com/search/?publisher=Daedalic%20Entertainment

When clicking on one of the pagination controls (the first time works), subsequently called URLs look like this and fail:
https://store.steampowered.com/search/?publisher=Daedalic%2BEntertainment&page=3

The problem arises in this line:
https://github.com/tfedor/AugmentedSteam/blob/7d0ac14f7992405b5c1c786b791b5db5f842dfde/js/content/store.js#L3066

params.toString() urlencodes the parameters (thus e.g. spaces are encoded to '+'), which would be fine for the href, but Steam itself intercepts the click on href and does another parameter manipulation and encoding step in searchpage.js:216 (via prototype.js' Object.toQueryString) resulting e.g. in `' ' -> '+' -> '%2B'`, which of course fails to return results.

Probably have to construct an unencoded query string, like e.g.  
    Array.from(params.entries(), entry => `${entry[0]}=${entry[1]}`).join("&");

**Comment by MxtOUT** [comment]
Nice find, thanks!
