### ISSUE TITLE
Regional Price Comparison not working 

### ISSUE THREAD

**Issue by FallOfVal** [tfedor/AugmentedSteam#576]
For the last few days when I hover my mouse over to the price the regional price comparison feature has not been working.
![steam 2](https://user-images.githubusercontent.com/56606868/66860229-4d9c0600-efe9-11e9-8377-7f0658b2554b.PNG)
![steam 1](https://user-images.githubusercontent.com/56606868/66860243-5391e700-efe9-11e9-8573-87eba35025fc.PNG)

**Comment by mahadi22** [comment]
Version 1.3.0 installed, have same error, but different currency 
"Uncaught (in promise) Could not establish conversion rate between ARS and IDR"

**Comment by FallOfVal** [comment]
> Version 1.3.0 installed, have same error, but different currency
> "Uncaught (in promise) Could not establish conversion rate between ARS and IDR"

Yeah it's working now. Thanks for your reply.
