### ISSUE TITLE
Font from reviews not right

### ISSUE THREAD

**Issue by dmlemos** [tfedor/AugmentedSteam#579]
The font from reviews is screwed up on version 1.3.0

Without extension
<img width="769" alt="Screenshot 2019-10-18 at 21 33 56" src="https://user-images.githubusercontent.com/1868454/67126499-1eef7c80-f1ef-11e9-8b9a-6ee53cd02c7c.png">

With extension
<img width="769" alt="Screenshot 2019-10-18 at 21 32 26" src="https://user-images.githubusercontent.com/1868454/67126515-2747b780-f1ef-11e9-803d-f112de9ed8af.png">

**Comment by BuryTomorrow12** [comment]
Same issue.

**Comment by snakecase** [comment]
Confirmed.

**Comment by jtm666** [comment]
Was gonna report this, seems that I am not the only one.

**Comment by Setmaster** [comment]
Same issue.

**Comment by IkeKap** [comment]
I still have the same issue. I don't think the pull request fixed this...

**Comment by MxtOUT** [comment]
Well, it's not live yet

**Comment by IkeKap** [comment]
ah I misunderstood. Sorry for sounding impatient.
