### ISSUE TITLE
Regional pricing not wok

### ISSUE THREAD

**Issue by Minidoracat** [tfedor/AugmentedSteam#580]
![image](https://user-images.githubusercontent.com/11269639/67138502-b2b85b80-f276-11e9-9cf7-bbb6f51b8bb8.png)
![image](https://user-images.githubusercontent.com/11269639/67138505-c19f0e00-f276-11e9-9de5-7193cb6dc7c7.png)

**Comment by mahadi22** [comment]
![image](https://user-images.githubusercontent.com/6297984/67148529-95ad7800-f2ca-11e9-8321-371899e738ba.png)

still not work for me, no addon/extension installed beside this AS

**Comment by mahadi22** [comment]
ok, another info, if i change "View in" option from auto to USD, its work like normal,
![image](https://user-images.githubusercontent.com/6297984/67911855-9becff80-fbba-11e9-8337-53e80c8b2a8c.png)

it seems it will break if its trying to convert to another currency than USD, like JPY, IDR, SGD, PLN and so on (so far currency that work, USD, CAD, GBP, EUR)
![image](https://user-images.githubusercontent.com/6297984/67912379-55000980-fbbc-11e9-883c-19a936001f69.png)

**Comment by Minidoracat** [comment]
"https://store.steampowered.com/api/packagedetails/?packageids="+subid+"&cc="+country
I think the wrong subid was used.

**Comment by MxtOUT** [comment]
Ok, in the next update you should be able to still see the regional pricing popup even if some conversion rates couldn't be established.
You won't see the converted price and the relative price differences for the affected currencies then of course

**Comment by MxtOUT** [comment]
The actual problem is that the rates are fetched from ITAD, which doesn't have price conversions between two unsupported currencies, so we have to wait for that to support more currencies
