### ISSUE TITLE
Quick Sell/Instant Sell buttons only loading for steam items

### ISSUE THREAD

**Issue by Canadiancookie** [tfedor/AugmentedSteam#582]
[Example of a steam item working](https://i.imgur.com/Ki9rj6F.png)

[CSGO item not working](https://i.imgur.com/f0kNnYe.png)

[TF2 item not working](https://i.imgur.com/tHQZJHv.png)

I have many other extensions installed, but disabling them so that only Augmented Steam was running did not change the outcome.

Google Chrome | 77.0.3865.120 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1903 (Build 18362.356)
JavaScript | V8 7.7.299.13

**Comment by MxtOUT** [comment]
We had that discussion some time ago and the reason why this only works for Steam items is that other ones are unlikely to have a market overview page.
I wanted to change this though, so thanks for tracking this now :)

**Comment by IanEarnest** [comment]
Is there still a discussion being held for the "quick sell" button on CSGO items?
I would be interested to know of the progress on the solution.
