### ISSUE TITLE
workshop items don't appear

### ISSUE THREAD

**Issue by Mr-Blondie** [tfedor/AugmentedSteam#586]
![Ek Açıklama 2019-10-20 235320](https://user-images.githubusercontent.com/46048586/67166125-644dae80-f395-11e9-9efe-832802eadf92.png)

**Comment by Revadike** [comment]
It's a Steam bughttps://www.reddit.com/r/Steam/comments/dkkosv/when_i_go_on_the_workshop_and_search_something/
