### ISSUE TITLE
[Feature Request] Base Price History Info on region

### ISSUE THREAD

**Issue by metapone** [tfedor/AugmentedSteam#589]
Currently the "current best" and "historical low" are displayed in regional price but are actually converted from USD. It would be useful if they are calculated based on regional price.
![Screenshot from 2019-10-21 16-34-12](https://user-images.githubusercontent.com/52821877/67194209-d61f0a00-f420-11e9-8493-336d63f3bff0.png)

**Comment by MxtOUT** [comment]
Your region probably isn't covered by ITAD, that's why it uses the US price and converts it to your currency.
Sadly new regions won't get added until new ITAD is finished
