### ISSUE TITLE
Review text on store pages is huge and goes past the review box boundaries

### ISSUE THREAD

**Issue by NTripleOne** [tfedor/AugmentedSteam#590]
![image](https://user-images.githubusercontent.com/23258957/67208297-2d1ae400-f40d-11e9-9e6e-5d7bfdc0a121.png)

Seems to break being able to expand reviews too? Disabling AS fixes the problem. Been happening for a few days now.

**Comment by Revadike** [comment]
dupe: https://github.com/tfedor/AugmentedSteam/issues/579
