### ISSUE TITLE
Store page reviews' text suddenly got really big

### ISSUE THREAD

**Issue by bottleblue** [tfedor/AugmentedSteam#596]
I noticed today that the text for store page reviews have gotten a lot bigger. If the review is lengthy enough it will overlap and you can't see all of it. The "Browse all reviews" page is not affected. Disabling Augmented Steam fixes it. Last update for AS was a month ago so I'm guessing Steam did something to their store page?

**Comment by Revadike** [comment]
Dupe: https://github.com/tfedor/AugmentedSteam/issues/579
