### ISSUE TITLE
White background on Gamepage

### ISSUE THREAD

**Issue by SirExtremis** [tfedor/AugmentedSteam#597]
![Untitled](https://user-images.githubusercontent.com/9652708/67286645-629bfc00-f4f7-11e9-95c9-e2f8c3f08f6b.png)

 Weirdly issue doesnt occur on all pages. Hope the image helps.

**Comment by Revadike** [comment]
You sure this is caused by Augmented Steam? I can't reproduce this.

**Comment by SirExtremis** [comment]
thats the thing. If i open the page after restarting firefox it behaves like normal. And this plugin is the only one that works on steam that I have installed.

**Comment by MxtOUT** [comment]
What FF version are you using?
How often do you get this?

**Comment by rhodwulf** [comment]
This sometimes happens because the Steam page does not load the background image properly, it has happened to me many times but nothing that a page reload did not solve.

**Comment by SirExtremis** [comment]
> 
> 
> What FF version are you using?
> How often do you get this?

Was using v69.

How often? It depends, sometimes it goes days without getting one of it. Sometimes its continuous until I restart the browser.
