### ISSUE TITLE
Extension being enabled messes with review font size

### ISSUE THREAD

**Issue by Tenshinen** [tfedor/AugmentedSteam#601]
When I have the extension enabled in Chrome, it makes the text in reviews very large and removes the read more button. I cannot find anything in the options menu for this, so I can only assume it's a bug of some kind?

Extension off: https://i.imgur.com/0dfO3Yb.png
Extension on: https://i.imgur.com/u17uiCm.png

**Comment by Revadike** [comment]
Update

**Comment by Tenshinen** [comment]
I literally installed it for the first time from the Chrome Web Store and it was immediately broken.

Redownloaded it today, works fine.

**Comment by MxtOUT** [comment]
Yes, there was an update

**Comment by Tenshinen** [comment]
Gotcha.
