### ISSUE TITLE
Message icon position

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#610]
This page: <https://store.steampowered.com/account/history/>
![image](https://user-images.githubusercontent.com/5698157/67656405-afb41e00-f98e-11e9-833a-58d81c55b66b.png)
Other page
![image](https://user-images.githubusercontent.com/5698157/67656539-09b4e380-f98f-11e9-8045-dc13e2746a18.png)

**Comment by Revadike** [comment]
Not sure why you'd close this. It's a proper bug.
My suspicion is this is happening because of https://github.com/tfedor/AugmentedSteam/commit/c19c889799ea18038fd783285e684375a216a3f0 and a solution would be to rename these classes.

**Comment by MxtOUT** [comment]
Because that's not our bug, look at the site without AS

**Comment by Revadike** [comment]
Shoot, you're right.

**Comment by bestpika** [comment]
Yes, I try disabled ES then the icon still weird.
