### ISSUE TITLE
AS sell-buttons doesn't work after last update.

### ISSUE THREAD

**Issue by AtlasRedux** [tfedor/AugmentedSteam#619]
As title states.
Quick-selling etc. just shows the waiting "wheel" indefinitely.
Tried other extensions as well and they work, so it's definitely a current AS issue, as it worked fine before last update.

EDIT : it seems sometimes / most of the time it does actually put up for sale, despite the "wheel" still spinning.

**Comment by MxtOUT** [comment]
When does this happen?
After you sell a lot of items in a row?

**Comment by ThisIsABug** [comment]
I can confirm this on Firefox 71.0 (with disabled 'Enhanced Tracking Protection').
It happens always at any time to any item. But as AtlasRedux mentioned the sale still seems to go through.

**Comment by MxtOUT** [comment]
> it seems sometimes / most of the time it does actually put up for sale, despite the "wheel" still spinning.

The reason for that probably was that the item needed further confirmation, so it would still show in your inventory

**Comment by AtlasRedux** [comment]
Don't close a ticket without reading.
This is NOT fixed. Read what the bug is, your reply is nonsensical. AGAIN, when clicking SELL on an item it just indefinitely loops. There even was confirmation on this bug.

**Comment by ThisIsABug** [comment]
> > it seems sometimes / most of the time it does actually put up for sale, despite the "wheel" still spinning.
> 
> The reason for that probably was that the item needed further confirmation, so it would still show in your inventory

I thought so too, but I can not confirm, the spinner stays, even if everything is confimed.

**Comment by MxtOUT** [comment]
> Don't close a ticket without reading.
> This is NOT fixed. Read what the bug is, your reply is nonsensical. AGAIN, when clicking SELL on an item it just indefinitely loops. There even was confirmation on this bug.

Right, I could reproduce this and I fixed it (see the commit that closes this issue).

Have you checked the develop branch yourself? I doubt it.

And please be a little more polite

**Comment by MxtOUT** [comment]
> > > it seems sometimes / most of the time it does actually put up for sale, despite the "wheel" still spinning.
> > 
> > 
> > The reason for that probably was that the item needed further confirmation, so it would still show in your inventory
> 
> I thought so too, but I can not confirm, the spinner stays, even if everything is confimed.

Yes, the fix isn't live yet

**Comment by Revadike** [comment]
Well he has a point that you easily close issues/PR's without heads up.

**Comment by MxtOUT** [comment]
I referenced a commit that fixes the issue, that's the heads-up
