### ISSUE TITLE
Recommend game page item style

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#620]
In the recommend game page only the first game can apply the style.
![image](https://user-images.githubusercontent.com/5698157/68101928-39be3280-ff0b-11e9-8ded-2fb08d0ddc8e.png)

**Comment by MxtOUT** [comment]
Can you give me the URL?

**Comment by bestpika** [comment]
@MxtOUT The links at the bottom of the game page.
The URL like `https://store.steampowered.com/recommended/morelike/app/{appid}/`.
For me, the page is <https://store.steampowered.com/recommended/morelike/app/1016960/>.

**Comment by Revadike** [comment]
It works fine here. I can't reproduce it. What version of AS are you running?

**Comment by bestpika** [comment]
v1.3.1

**Comment by bestpika** [comment]
I got some error at console.
![image](https://user-images.githubusercontent.com/5698157/68261578-87f24380-007b-11ea-8253-4d5068919b95.png)
