### ISSUE TITLE
Make localization uniform with help of Crowdin or other similar service.

### ISSUE THREAD

**Issue by Ryzhehvost** [tfedor/AugmentedSteam#621]
I may be wrong, but it seems the localization of AS is made completely by hands, and because of that it's a mess without uniform structure. My suggesion is to use some service (I suggest Crowdin) to make localization process as automatic as possible. It would require some efforts to put existing parts of localization to Crowdin, but in exchange we will have a convenient platform, where everyone interested will be able to participate in translation, files will have uniform structure, and it will be **much** easier to see the progress of every language localization.

**Comment by MxtOUT** [comment]
We use [POEditor](https://poeditor.com/join/project/yGk0CFH2Uu)
