### ISSUE TITLE
Add pagination on "all games" page of user profiles.

### ISSUE THREAD

**Issue by Ryzhehvost** [tfedor/AugmentedSteam#622]
It is known that steam may be extremely slow when trying to load huge game libraries (>1k games), it can freeze for a couple of minutes to show it, you can see what I'm talking about for example here: https://steamcommunity.com/id/ArchiPL/games/?tab=all
Recently I was told about this add-on http://lab.nyan.link/sliwipi/ (source code is available here https://github.com/Yusyuriv/Sliwipi ) that can add a pagination to that page, effectively removing the freezes when opening it. This add-on seems to be long abandoned, I had to meddle with it a little even to make it start, but it indeed solves the above issue. So, my suggestion is to integrate this feature to AS instead. That add-on also used to work with wishlists, but it seems unnecessary now, when Valve made new dynamic wishlist page, so we only need library part.

**Comment by Revadike** [comment]
Were you also gonna do this? If so, perhaps you can be assigned to this issue.

**Comment by Ryzhehvost** [comment]
Yes, I'm working on a PR. Unsure if it will be of proper quality though(

**Comment by Revadike** [comment]
> Yes, I'm working on a PR. Unsure if it will be of proper quality though(

You got us reviewers for that ;)

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/71229064-8bb4ef00-22e4-11ea-8b57-c7c01de2f442.png)

**Comment by Ryzhehvost** [comment]
since #735 is closed, this probably should be closed too.
