### ISSUE TITLE
Price comparison not showing

### ISSUE THREAD

**Issue by bestpika** [tfedor/AugmentedSteam#624]
`AS v1.3.1`
Setting
![image](https://user-images.githubusercontent.com/5698157/68354204-affaa900-0146-11ea-8ddc-7207f205c42a.png)
Game page example: <https://store.steampowered.com/app/790820/>
![image](https://user-images.githubusercontent.com/5698157/68354183-9eb19c80-0146-11ea-9d42-c6a18800d7f7.png)
Console get this error
![image](https://user-images.githubusercontent.com/5698157/68354241-d3bdef00-0146-11ea-8b57-90ae97de0883.png)

**Comment by candela97** [comment]
This has been fixed with 8702d5bee20c11371c682cc4c6f6dc296260a8de.
