### ISSUE TITLE
Sorting during managing resets checkboxes

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#642]
If you are managing your friend list and you sort it, the checkboxes disappear. You would have to reopen the manager section, for the checkboxes to appear again.

**Comment by MxtOUT** [comment]
What do you mean?
If I select some friends, then sort it, the checkboxes work as intended

**Comment by Revadike** [comment]
Seems to only happen if you click the manage button fast enough on page load (which it did in my earlier friend commenter PR).

**Comment by MxtOUT** [comment]
So this can be closed?

**Comment by Revadike** [comment]
> So this can be closed?

Technically still a bug, but a rare bug currently. I'll leave it up to you.

**Comment by MxtOUT** [comment]
Sorting during managing would also remove the checkboxes, so that was deeper than I thought first
