### ISSUE TITLE
Epic Store Price in wrong currency

### ISSUE THREAD

**Issue by duguzuyang** [tfedor/AugmentedSteam#647]
I noticed that the pricing for Epic Game Store is incorrect when the default currency is set to another currency other than USD in the region of the account. The price from Epic Game Store should be in USD while it's in local currency for now.

**Comment by MxtOUT** [comment]
Yes, that is done in order to get a relation between the Steam store price (which is in your local currency) and the EGS price.

If you still want to show the prices in USD, you can do so by setting the custom currency in the options to USD

**Comment by duguzuyang** [comment]
I understand this feature and I really appreciate it. The [problem I'm having is that the price from EGS is wrong. For example my Steam local currency is CNY, the price from EGS is showing 60 CNY while the real price in EGS is 60 USD (~420 CNY).

**Comment by MxtOUT** [comment]
On what game are you seeing this?

**Comment by duguzuyang** [comment]
Star Wars Jedi: Fallen Order
https://store.steampowered.com/app/1172380/_/
https://www.epicgames.com/store/en-US/product/star-wars-jedi-fallen-order/home

**Comment by duguzuyang** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/7322443/69090997-639d4c00-0a17-11ea-8404-b7c3e80cd3f0.png)

Obviously EGS price is in the wrong currency.
