### ISSUE TITLE
Wrong price for games with similiar games

### ISSUE THREAD

**Issue by VitalD** [tfedor/AugmentedSteam#648]
Hi guys!

Please check this game https://store.steampowered.com/app/378610/Valley/
It's name "Valley", but when I'm on it's page I see lowest price of another game on Steam and link follows to https://store.steampowered.com/app/1169500/The_Valley/
This game's name is "The Valley".
Is it possible to fix game's name detect to avoid this problem?

**Comment by MxtOUT** [comment]
This is an ITAD problem, will report that, thanks!

**Comment by MxtOUT** [comment]
Should be fixed
