### ISSUE TITLE
Context menu initially not working

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#649]
So, when you restart the web browser and wanna use the context menu option, the first click won't work, unless you clicked before or opened a extension page before, like background page. It also gives no errors, hence debugging this is really hard.

**Comment by MxtOUT** [comment]
The code definitely executes until to the point where it registers the listener, I think that's due to registering it asynchronously

**Comment by Revadike** [comment]
According to [this](https://stackoverflow.com/questions/17632919/chrome-extension-execute-background-page-only-once-when-chrome-starts) it is only possible if you set persistent to `true`

**Comment by Revadike** [comment]
Fixed it by adding this to core.js:
![image](https://user-images.githubusercontent.com/4411977/69014523-7e29e380-098b-11ea-8616-9676db54d756.png)

It would have fit better in background.js, but somehow it only worked on core.js.

**Comment by MxtOUT** [comment]
Don't know what didn't work for you in `background.js`
