### ISSUE TITLE
Wrong price when argumentedsteam enabled.

### ISSUE THREAD

**Issue by heroboy** [tfedor/AugmentedSteam#656]
![图片](https://user-images.githubusercontent.com/54468/69107772-7cf0d780-0aad-11ea-998b-adfbdb659372.png)
It should be 121-50.
When argumentedsteam disabled, it is correct.
----
https://store.steampowered.com/sub/127633/

**Comment by MxtOUT** [comment]
Hm, if you look closely, the currency signs are different.
Are they interchangeable?

And what is your store currency?

**Comment by heroboy** [comment]
No, it's same. But with different font or style.  And the symbol is also used for Japanese yen.
My store currency is Chinese yuan.
Today's screenshot:
![image](https://user-images.githubusercontent.com/54468/69237249-3516a100-0bd0-11ea-836b-742aaf3d7a1f.png)
![image](https://user-images.githubusercontent.com/54468/69237252-35af3780-0bd0-11ea-8dbb-a5d3c3491185.png)

You will see: (335-200)/8.77 = yen / yuan = 5999/389.52
Maybe your program think the upper price is yen, and when calculate the saved price it is converted to yuan for me. But actually the 335,200 is yuan, because if it is yen , it will be bigger.

**Comment by heroboy** [comment]
By the way, I do not login. Steam guess my currency via my IP address.

**Comment by MxtOUT** [comment]
> Maybe your program think the upper price is yen

This seems to be it, it interprets the '¥' as yen.

Do you see any errors in your browser console (F12)?

**Comment by MxtOUT** [comment]
Wait, I see:
Since Japan and China use the same currency symbol, there is an ambiguity when trying to assign a string containing a price to JPY or CNY.
Currently this is implemented as treating such strings as JPY

**Comment by heroboy** [comment]
I wonder there are so many currencies shared the same symbol. How do you distinguish them?

**Comment by MxtOUT** [comment]
What currencies do you mean?
I only know of CNY and JPY

**Comment by heroboy** [comment]
Sorry I just find there is a prefix before many $ currency.

**Comment by deluxghost** [comment]
is this related? it messed up custom funds features under cny currency

![image](https://user-images.githubusercontent.com/5835759/79061093-2a63c200-7cbf-11ea-9a9f-b1dc020476d0.png)

**Comment by MxtOUT** [comment]
Yeah, that is this problem

**Comment by MxtOUT** [comment]
Would be nice if someone impacted that has knows how to checkout the dev version could try this.
@candela97 Don't you also have CNY currency?

**Comment by candela97** [comment]
I'm afraid I'm using NT$.

@deluxghost @heroboy Can you sideload the dev branch and see if this issue is fixed?

**Comment by heroboy** [comment]
@MxtOUT @candela97 

![图片](https://user-images.githubusercontent.com/54468/79175585-b0ebe100-7e30-11ea-8a96-2de1076fe384.png)

**Comment by heroboy** [comment]
I'm not familiar with the code. But do you not trim the symbol? `value` should be convertted to `number`, because in later code: `this.value + otherPrice.value`.
![图片](https://user-images.githubusercontent.com/54468/79175811-47b89d80-7e31-11ea-9e36-a614aea50878.png)

**Comment by MxtOUT** [comment]
@heroboy You're absolutely right, could you check develop once more please?

**Comment by deluxghost** [comment]
tested custom funds, the price is correct, but symbol is wrong

![image](https://user-images.githubusercontent.com/5835759/79216035-15ce2800-7e7f-11ea-8e9d-f59300b908be.png)

![image](https://user-images.githubusercontent.com/5835759/79216050-1c5c9f80-7e7f-11ea-8f0d-c493d9f5f4a8.png)

**Comment by deluxghost** [comment]
by the way should these be updated?

https://github.com/tfedor/AugmentedSteam/blob/3daf982ba15ae6de35bb82223840f4e89e6f0902/js/content/common.js#L662

https://github.com/tfedor/AugmentedSteam/blob/3daf982ba15ae6de35bb82223840f4e89e6f0902/js/content/common.js#L776

https://github.com/tfedor/AugmentedSteam/blob/3daf982ba15ae6de35bb82223840f4e89e6f0902/json/currency.json#L24

**Comment by MxtOUT** [comment]
@deluxghost If you set a breakpoint at store.js:2654, what is the value of `Currency.storeCurreny` and `currency.format.symbol`?

> by the way should these be updated?
I think you could update the symbol of CNY but it won't make any difference

**Comment by deluxghost** [comment]
strange, `Currency.storeCurrency` is always set by my first IP, no matter I logged in or not. so while I was taking the screenshot, the value is USD. to refresh the value I must exit the browser completely

`getCurrencyFromDom()` and `getCurrencyFromWallet()` just failed

about the bundle, it's getting worse, it shows that bundle saved -$200 for me 🤔

**Comment by MxtOUT** [comment]
Yeah, that's because the price string is CNY but it's interpreted as USD.
Another problem though, so let's discuss that in #858

**Comment by heroboy** [comment]
![图片](https://user-images.githubusercontent.com/54468/79287852-ab0d0300-7ef7-11ea-8660-861211a6f76c.png)
