### ISSUE TITLE
Context menus do not work in Firefox

### ISSUE THREAD

**Issue by rafaelgssa** [tfedor/AugmentedSteam#660]
In Firefox, `contextMenus` can be used as an alias of `menus`, but it cannot be requested as an optional permission.

Possible solutions I thought of:

* Make the permission required instead of optional. It doesn't appear that `contextMenus` gives a warning when updating the extension (https://developer.chrome.com/apps/permission_warnings).
* Remove the context menus options on Firefox, by detecting the browser through #661.

Let me know if any of these solutions is ok and I can pick this up.

**Comment by MxtOUT** [comment]
I'm not too sure whether this is already fixed when we use the browser polyfill, see the ITAD integration branch

**Comment by MxtOUT** [comment]
Fixed with 549198ba37726d1928bca0d48dc0cd103115f682
