### ISSUE TITLE
[Feature Request] disable custom themes for all profiles

### ISSUE THREAD

**Issue by ThisIsABug** [tfedor/AugmentedSteam#667]
It would be nice to have a checkbox somewhere in the options menu, to disable custom themes in the whole.

**Comment by Revadike** [comment]
Well, you can use the View in Client button to see the vanilla profile in your steam client

**Comment by ThisIsABug** [comment]
I know that button from store pages, but where is it on profile pages?

**Comment by Revadike** [comment]
> I know that button from store pages, but where is it on profile pages?

Check augmented steam options, you can replace the Install Steam button with a View In Client button.

**Comment by ThisIsABug** [comment]
Would be a good alternative, didn't know that, thanks. 
But I wouldn't like to see bright different color schemes in the first place.

**Comment by Revadike** [comment]
Assign me to this @MxtOUT
