### ISSUE TITLE
Option not working - Show "Add to Wishlist" button on community app hubs

### ISSUE THREAD

**Issue by sunbeams001** [tfedor/AugmentedSteam#670]
Using extension version 1.3.1
Already check this option, but seems no link node has been added to html

![image](https://user-images.githubusercontent.com/3478170/69786555-a28c8800-11f5-11ea-811c-e2326f47113c.png)

![image](https://user-images.githubusercontent.com/3478170/69782316-98fe2280-11eb-11ea-8ed8-ea76dded4c28.png)

**Comment by candela97** [comment]
Currently the button won't appear if you wishlisted the game already, which, according to the color of the game name in your screenshot, you have.

**Comment by sunbeams001** [comment]
@candela97 Thanks for your explanation.
I had thought that I can remove game from wishlist here, since some games has been removed by valve.

**Comment by candela97** [comment]
yeah, there's a TODO to implement that
