### ISSUE TITLE
"Show 3rd-party DRM warnings" broken on brave

### ISSUE THREAD

**Issue by xeropresence** [tfedor/AugmentedSteam#673]
https://store.steampowered.com/app/883710/RESIDENT_EVIL_2__BIOHAZARD_RE2/

on chrome Version 78.0.3904.108 (Official Build) (64-bit):
https://i.imgur.com/uHEuZy9.png

on brave Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit) :
https://i.imgur.com/l9PsRvs.png

Toggling the option does nothing for brave, no errors reported in the console.

**Comment by candela97** [comment]
Are you using the same version of AS to test on both browsers?

**Comment by xeropresence** [comment]
Apparently not, chrome wasn't running the latest version. After I started chrome again it updated to 1.3.1 and now it is no longer displaying the drm banner.

**Comment by MxtOUT** [comment]
This has already been fixed by e42dec4 and will be included in the next version of AS

**Comment by xeropresence** [comment]
Thanks, is there an ETA on when a new version will be pushed? Looks like that commit was over two weeks ago.

**Comment by Revadike** [comment]
> Thanks, is there an ETA on when a new version will be pushed? Looks like that commit was over two weeks ago.

This year. They always take a long time, unless they're a hotfix.
