### ISSUE TITLE
Developer link replacement searches publisher

### ISSUE THREAD

**Issue by NLZ** [tfedor/AugmentedSteam#674]
The developer link replacement is bugged, searches for publisher instead of developer:
![image](https://user-images.githubusercontent.com/884277/69902629-4f027180-1390-11ea-8c8e-c834d0f3853d.png)

Seems like this line is the culprit, but I leave it up for the experts to troubleshoot:
https://github.com/tfedor/AugmentedSteam/blob/b6c5f7e814e42f64ba759de54781b6219ab8abbb/js/content/store.js#L2999

**Comment by MxtOUT** [comment]
Just if you're interested, the line you mentioned affects the hide buttons on the search page.

Thanks for reporting!

**Comment by candela97** [comment]
Seems like franchise links (if present) are broken as well...
https://store.steampowered.com/app/582010/MONSTER_HUNTER_WORLD/
https://store.steampowered.com/app/813780/Age_of_Empires_II_Definitive_Edition/
I think they shouldn't be modified.

**Comment by bestpika** [comment]
Did this version publish to the Chrome store?
I saw some page's link still wrong.

- <https://store.steampowered.com/app/286690/>
![image](https://user-images.githubusercontent.com/5698157/72771045-9c85b700-3c3a-11ea-8c38-2474f102b4a7.png)

**Comment by candela97** [comment]
Can't reproduce on latest stable Chrome, and the commits that fixed this issue didn't affect this area.
![註解 2020-01-22 055757](https://user-images.githubusercontent.com/54083835/72846965-934d2680-3cdc-11ea-9362-503b9c70fd44.jpg)

**Comment by bestpika** [comment]
🤔
Yesterday, the link is wrong.
Today, the link is correct.

Maybe the issue is Steam's issue...

**Comment by bestpika** [comment]
It has happened again.
![image](https://user-images.githubusercontent.com/5698157/73158442-c5b4b480-411e-11ea-891c-1855b5ad786f.png)

**Comment by Revadike** [comment]
I can confirm this happens when using steamdb's extension.
Can't see check the curator link in order to determine if it's a dev or pub?

**Comment by MxtOUT** [comment]
Better to open a new issue

**Comment by Revadike** [comment]
> Better to open a new issue

Do you think we can check the curator link in order to determine if it's a dev or pub?

**Comment by MxtOUT** [comment]
Should be possible, yes

**Comment by Revadike** [comment]
> Should be possible, yes

No, because the link path can be `/curator/` too and then what?
