### ISSUE TITLE
Remove duplicating checkbox on library page

### ISSUE THREAD

**Issue by Ryzhehvost** [tfedor/AugmentedSteam#681]
When viewing a library page of someone other than yourself, vanilla steam adds there a checkbox `Filter to games you both own`. When AS is enabled, it also adds two more checkboxes there: `Hide games that you do not own` and `Hide games that you own`. As a result, both `Filter to games you both own` and `Hide games that you do not own` do *exactly the same*, which seems excessive, and also does not look good, because there is not enough space to fit three checkboxes. Either original steam checkbox should be removed, or AS should add only `Hide games that you own` one, to avoid duplication.
![изображение](https://user-images.githubusercontent.com/15903022/70225958-aae64500-1758-11ea-9688-77faed1b2945.png)

**Comment by candela97** [comment]
yeah I think removing our duplicate option is fine here, since using it also carries the problem of not loading unloaded images

**Comment by Ryzhehvost** [comment]
One more thing to consider - while both checkboxes result in the same list of games, they work slightly differently - original steam checkbox leads to page reload, while AS filters the games without reload, and hence seems to work faster. Maybe it would be better to remove original checkbox and replace it with our implementation? Of course if it's possible to solve the issue with images loading.
