### ISSUE TITLE
Hiding items marked as not interested doesn't work

### ISSUE THREAD

**Issue by scowalt** [tfedor/AugmentedSteam#69]
**Extension version:** 0.9.3
**Repro steps:**

0) Log into Steam
1) Navigate to a Steam search selection where there are visible items marked "Not Interested" (https://store.steampowered.com/search/?term=)
2) Under the "Hide" filter options, select "Items marked not interested"

**Expected:** items marked not interested are hidden
**Actual:** items marked not interested are still shown
**Screenshot:**
![image](https://user-images.githubusercontent.com/1100550/52901306-be6af400-31b6-11e9-8627-4e5b15692a5e.png)
**Notes:** This has been a bug in Enhanced Steam for a while. This would be a huge value add to the extension for me. I've marked almost 2,000 products as "Not Interested" on Steam, and it would be great to truly have those be gone instead of cluttering my searches.

**EDIT:** Spent some time digging into the root cause. Here's the code that's supposed to do the hiding: https://github.com/tfedor/Enhanced_Steam/blob/779d0954ae62ec64c4d1d03ed2e5c3516b5022cc/js/store.js#L2262 Unlike the code for the other hide functionality, this one doesn't `node.style.display = "none";`. If I manually add a css rule to `.ds_ignored {display: "none";}`, the games appear to be hidden correctly. I imagine this is a one-line fix of adding `node.style.display = "none";` to the end of this logic. Unfortunatley, I'm not sure how to test this fix locally without a `js\config.js`

**Comment by MxtOUT** [comment]
Sorry for the mess, should be fixed with #60

**Comment by MxtOUT** [comment]
And regarding `js/config.js`: I got my copy from the [homepage](https://es.isthereanydeal.com/) when you could directly download the release as a zip.
Now, if you have Chrome, you can retrieve the file at `C:\Users\<UserName>\AppData\Local\Google\Chrome\User Data\Default\Extensions\dnhpnfgdlenaccegplpojghhmaamnnfp\<AS_Version>\js\config.js`.

**Comment by MxtOUT** [comment]
I also noticed that the option to hide both owned and ignored items was already implemented and working, but only accessible through the options page under the section "Hide" (first two entries).
Imo these should be completely removed from this page
