### ISSUE TITLE
Region Price and Historical/Current Lowest Price wrong caused by IP region mismatch

### ISSUE THREAD

**Issue by sunbeams001** [tfedor/AugmentedSteam#692]
Environment: Chrome version 78 , extension version 1.3.1, view store page under network proxy (which IP region is HK)
Steam account region: China
Extension Option: view_in_currency: CNY; regional_price: us, ru, cn, hk

The store page looks like this
![image](https://user-images.githubusercontent.com/3478170/70690670-22384d80-1cf2-11ea-86eb-41e435097d44.png)

Seems that currency is judged as HK Dollar because of the network proxy I use, regardless of my account region.

How can I fix this?

**Comment by sunbeams001** [comment]
Actually, the Region Price seems using HK region price, but the Historical/Current Lowest Price is using the US price

**Comment by MxtOUT** [comment]
> Actually, the Region Price seems using HK region price, but the Historical/Current Lowest Price is using the US price

This might be due to your region not being supported by ITAD?

**Comment by MxtOUT** [comment]
Could you tell me

a) the first two characters of your `steamCountry` cookie
![image](https://user-images.githubusercontent.com/14999077/70801071-26c23c00-1dae-11ea-9885-f3e4d4c3dea8.png)

b) the value of the `userCountry` LocalStorage entry?
![image](https://user-images.githubusercontent.com/14999077/70801178-7d2f7a80-1dae-11ea-8909-43d6438a0a04.png)

**Comment by sunbeams001** [comment]
@MxtOUT 
The Cookie starts with "HK" and the LocalStorage has no such key of "userCountry"

**Comment by MxtOUT** [comment]
How does the page https://store.steampowered.com/account/change_country/ look like for you?

**Comment by sunbeams001** [comment]
@MxtOUT 
Page seems ok, the region is CN
![image](https://user-images.githubusercontent.com/3478170/70842949-38b2e600-1e65-11ea-8368-6e61a7a9bb91.png)

But in browser console there are some errors:
![image](https://user-images.githubusercontent.com/3478170/70842959-6b5cde80-1e65-11ea-8ba0-457216d53ff9.png)

**Comment by sunbeams001** [comment]
I here detail my current situation as much as possible, for you to locate the key problem.

1. Cannot read property 'l' of undefined
In the expression "unsafeWindow.g_oSuggestParams.l", this part "unsafeWindow.g_oSuggestParams" is undefined
2. Failed to initialize Currency
In function _getRates(), the target array value is ["CNY"]

**Comment by MxtOUT** [comment]
On the page where you can change the country, what is the output when you execute `document.querySelector("#dselect_user_country").value` in the console?

**Comment by sunbeams001** [comment]
@MxtOUT It's "CN"
BTW I reinstall the extension and the userCountry key is back, but when the key is missing, whether refresh page or disable/enable extension does no work.

I think my situation is by some reason the userCountry key is missing, then it just will not be readded unless you reinstall the extension.

**Comment by MxtOUT** [comment]
The `userCountry` entry is set by Augmented Steam.

So you say that the entry will vanish after you use it for some time?
I don't understand

**Comment by sunbeams001** [comment]
@MxtOUT 
To some extent, I didn't changed this entry manually, but it just gone. And the extension just add this entry when installed, and this caused my wrong price problem.

For now, reinstall extension solved my problem.
