### ISSUE TITLE
[Feature Request] Highlight game purchased/wishlisted (etc.) status on the Steam community pages

### ISSUE THREAD

**Issue by Twistorian** [tfedor/AugmentedSteam#700]
I would like to see a highlight if there's a game mentioned in the discussions, Steam profiles, or particularly in an announcement, and a link to it is written using Steam url linking. This already works for announcements when viewed in the activity feed, but if you visit the page of the announcement, the highlighting is not working over there.

E.g. if someone creates a link using `[url=link_to_some_steam_game_store_page]Example Game[/url]`, it would do high-lighting according to the status of this game in your profile (i.e. owned, wishlisted, ignored, etc.).

**Comment by MxtOUT** [comment]
Now tracked in #901
