### ISSUE TITLE
Store page hours played text overlap

### ISSUE THREAD

**Issue by Californ1a** [tfedor/AugmentedSteam#701]
For a game in your library that you have achievements done for, the hours played and amount of achievements earned get overlapped:

![](https://i.imgur.com/l0cFwil.png)

**Comment by candela97** [comment]
IMO not really a bug per se, English just takes up more space
![註解 2020-01-21 130426](https://user-images.githubusercontent.com/54083835/72847674-ff7c5a00-3cdd-11ea-9843-01c0c3fe005e.jpg)

**Comment by MxtOUT** [comment]
Yeah, but the layout is unfortunate, it should wrap the text.
I tried playing around with it, but something (I don't remember what) prevented the lines from properly breaking

**Comment by masteratt** [comment]
Hello,
I've made a PR for this: #807 

See result:
![Hours played text overlap fix](https://user-images.githubusercontent.com/36424101/76822579-70854d00-6809-11ea-997e-1e36d3ec4a5e.PNG)

**Comment by Revadike** [comment]
This can be closed now. PR #807 was merged.
