### ISSUE TITLE
Suggestion to add current price/discount to exported wishlist

### ISSUE THREAD

**Issue by Ryzhehvost** [tfedor/AugmentedSteam#713]
If it's not too hard to implement - would be nice to have current price and optionally discount in exported wishlist data. this way it would be possible to process this data in third-party tools (like excel for example).

**Comment by Revadike** [comment]
Funny you say excel. I originally developed this feature with a CSV export, but the CSV option was deemed unnecessary according to the ITAD staff. :/

**Comment by Ryzhehvost** [comment]
Well, format conversion is not a problem, as long as data is there. I wouldn't mind having CSV, but if maintainers believe it should not be there - so be it.
