### ISSUE TITLE
Add a link button to Steamtradematcher on the badge page.

### ISSUE THREAD

**Issue by Eremeir** [tfedor/AugmentedSteam#723]
The direct badge page or within the page for individual game badges could benefit from a link button.

**Comment by Revadike** [comment]
Steamtradematcher is still operational?

**Comment by Eremeir** [comment]
I used it this morning. Why wouldn't it be operational?

**Comment by candela97** [comment]
Can you perhaps provide more info on how this site works, and what kind of link you want displayed?

**Comment by Eremeir** [comment]
Steamtradematcher scans your inventory and tries to set up 1:1 card trades with trade bots or other site users.

It outputs a list which you can use to setup trade offers.  It's pretty self explainable if you use it.

I'd suggest adding a button aside wherever steamcardexchange links are currently.

**Comment by candela97** [comment]
A button that links to the homepage? That doesn't sound useful. Or do you mean a link to scan your inventory?
Steamcardexchange links for instance links to individual badges.

**Comment by Eremeir** [comment]
The homepage is essentially an about section, so yeah the scan "compare" page.

 I think it's a useful tool and a link would save some clicks, as well as inform people the thing exists, broadening the card pool and getting more users to expand the number of potential matches.

**Comment by candela97** [comment]
Hmm, I dunno about endorsing the services of a particular site. Currently 3rd party site links included in AS are simple queries to a relevant page with additional info.

Also, I noticed they have a userscript. Is it open source? Maybe it can be integrated into AS some way if the maintainer agrees and somebody can work on it.

**Comment by Eremeir** [comment]
The userscript is open source, but it wouldn't do much without the site. 

The userscript just auto-selects cards that the tradematcher setup in its 1:1 trade results so you don't have to look for them on your own. It doesn't do anything without the matcher and I don't know how you'd be able to divorce it.

**Comment by Revadike** [comment]
I have to agree, this feature would fit more into STM's own userscript.
