### ISSUE TITLE
How to synchronize the notes？

### ISSUE THREAD

**Issue by guoyitian315** [tfedor/AugmentedSteam#725]
I miss every notes on wishlist page and game page when update the version 1.4.0, so how to synchronize notes?
When i switch the browser in two PC, any notes are not found neither.

**Comment by MxtOUT** [comment]
The notes weren't properly transferred from the old to the new storage location, will be fixed with the next update

**Comment by MxtOUT** [comment]
e89339a348b56ad6d1fbd9dd6c548f4c8ce3eee9
