### ISSUE TITLE
 Website/email on app pages

### ISSUE THREAD

**Issue by Tauri141** [tfedor/AugmentedSteam#727]
Ver 1.4.0, Firefox and Chrome. Missing Information about emails (developers support) in all games.

**Comment by Revadike** [comment]
Seems `            let response = await Background.action("appdetails", {"appids": appid, "filters": "support_info"});
` returns `null` somehow

**Comment by Revadike** [comment]
Likely something went wrong here: 
![image](https://user-images.githubusercontent.com/4411977/72010090-83066780-3257-11ea-945a-968507472bde.png)

**Comment by Revadike** [comment]
BTW, the request get fired and returns all valid json.
