### ISSUE TITLE
AugmentedSteam crashes repeatedly on Chrome Version 79.0.3945.117 

### ISSUE THREAD

**Issue by barryjj** [tfedor/AugmentedSteam#731]
Recently updated to Chrome Version 79.0.3945.117  on Mac OSX (Catalina Version 10.15.3 Beta) and AugmentedSteam is repeatedly crashing -- if I re-enable the extension manually, it just immediately crashes.

I tried to grab logs but couldn't manage to find them; if you need me to grab them, just let me know where to look and I'll do what I can to collect them for you.

**Comment by Revadike** [comment]
Try checking the background page: https://github.com/tfedor/AugmentedSteam/wiki

**Comment by barryjj** [comment]
I open up the background page but when the plugin crashes the background page goes with it before I have any chance to really see anything -- I'd probably be better off using a breakpoint somewhere if I had any clue where to start.  I'm guessing it must be in some common library because the plugin is crashing both on steampowered and steamcommunity sites.  Unsure if helpful, but I think the loading bar at the top usually stops about 75% of the way through and then I get the popup telling me the plugin crashed.

**Comment by barryjj** [comment]
I was able to find the following in the Chrome Developer Tools console after the plugin crashes:

`A cookie associated with a cross-site resource at http://nflent-vh.akamaihd.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:2328  Augmented Steam v1.4.0  https://es.isthereanydeal.com/
chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:1387 Uncaught (in promise) TypeError: Cannot read property '973580' of undefined
    at checkNodes (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:1387)
chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:1387 Uncaught (in promise) TypeError: Cannot read property '736220' of undefined
    at checkNodes (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:1387)
chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/content/common.js:1895 Uncaught (in promise) Object
(index):1 A cookie associated with a cross-site resource at http://steamcommunity.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
(index):1 A cookie associated with a cross-site resource at https://steamcommunity.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2browser-polyfill.js:1144 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1144
    at new Promise (<anonymous>)
    at wrappedSendMessage (browser-polyfill.js:1141)
    at Object.apply (browser-polyfill.js:862)
    at Function.message (core.js:30)
    at Function.message (common.js:227)
    at Function.action (core.js:35)
    at Function.getAppStatus (common.js:92)
    at Object.self.highlightAndTag (common.js:1874)
    at store.js:3955`

**Comment by tfedor** [comment]
Thanks for log, can you try disabling "Show Early Access image banners" option? You should be able to get there from addons page, or this link should work too:
chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/options.html

**Comment by barryjj** [comment]
> Thanks for log, can you try disabling "Show Early Access image banners" option? You should be able to get there from addons page, or this link should work too:
> chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/options.html

That worked -- disabling that option allowed the page to successfully load without Augmented Steam plugin crashing.

**Comment by MxtOUT** [comment]
Hm, setting a breakpoint would indeed help here.
Could you
- set a breakpoint at `background.js:1356` (on the background page) so that any errors are caught
- set a breakpoint at `common.js:1384` (available through any store page) and report the value of `appidsMap`
- check how the `earlyAccessAppids` object store is looking like (from the background page, select Application > IndexedDB > Augmented Steam > earlyAccessAppids

**Comment by barryjj** [comment]
> Hm, setting a breakpoint would indeed help here.
> Could you
> 
> * set a breakpoint at `background.js:1356` (on the background page) so that any errors are caught
> * set a breakpoint at `common.js:1384` (available through any store page) and report the value of `appidsMap`
> * check how the `earlyAccessAppids` object store is looking like (from the background page, select Application > IndexedDB > Augmented Steam > earlyAccessAppids
> 
> Of course with the early access banners enabled

I set one on `common.js:1386` in addition to `common.js:1384` so I could catch the values after the call returned; Here's the local scope on 1386 on the main store page:

Local
```
selectors: (8) [".cap", ".special", ".game_capsule", ".cluster_capsule", ".recommended_spotlight_ctn", ".curated_app_link", ".dailydeal_ctn a", ".tab_item:last-of-type"]
selectorModifier: ""
appidsMap: Map(4)
[[Entries]]
0: {792220 => a.tab_item.es_ea_checked}
1: {813780 => a.tab_item.es_ea_checked}
2: {851850 => a.tab_item.es_ea_checked}
3: {982970 => a.tab_item.es_ea_checked}
size: 4
__proto__: Map
size: (...)
constructor: ƒ Map()
get: ƒ ()
set: ƒ ()
has: ƒ has()
delete: ƒ delete()
clear: ƒ clear()
entries: ƒ entries()
forEach: ƒ forEach()
keys: ƒ keys()
values: ƒ values()
Symbol(Symbol.toStringTag): "Map"
Symbol(Symbol.iterator): ƒ entries()
get size: ƒ size()
__proto__: Object
selector: ".cap:not(.es_ea_checked),.special:not(.es_ea_checked),.game_capsule:not(.es_ea_checked),.cluster_capsule:not(.es_ea_checked),.recommended_spotlight_ctn:not(.es_ea_checked),.curated_app_link:not(.es_ea_checked),.dailydeal_ctn a:not(.es_ea_checked),.tab_item:last-of-type:not(.es_ea_checked)"
nodes: NodeList(4) [a.tab_item.es_ea_checked, a.tab_item.es_ea_checked, a.tab_item.es_ea_checked, a.tab_item.es_ea_checked]
eaAppids:
792220: false
813780: false
851850: false
982970: false
__proto__: Object
this: Window
```


As far as the earlyAccessAppids, every key pulls a null value:
```
1 | 16500 | null
2 | 16900 | null
3 | 108600 | null
4 | 213550 | null
5 | 217120 | null
6 | 221560 | null
7 | 223490 | null
8 | 224440 | null
9 | 227720 | null
10 | 229560 | null
11 | 230290 | null
12 | 232450 | null
13 | 232810 | null
14 | 236370 | null
15 | 238590 | null
16 | 244770 | null
17 | 246300 | null
18 | 246820 | null
19 | 247310 | null
20 | 248630 | null
21 | 250540 | null
22 | 251570 | null
23 | 251790 | null
24 | 251890 | null
25 | 251950 | null
26 | 252090 | null
27 | 252870 | null
28 | 253110 | null
29 | 254590 | null
30 | 257930 | null
31 | 258240 | null
32 | 259570 | null
33 | 261350 | null
34 | 261550 | null
35 | 262370 | null
36 | 263040 | null
37 | 263200 | null
38 | 263440 | null
39 | 263920 | null
40 | 266190 | null
41 | 266370 | null
42 | 266430 | null
43 | 266470 | null
44 | 266550 | null
45 | 266620 | null
46 | 268650 | null
47 | 268670 | null
48 | 268970 | null
49 | 269190 | null
```

**Comment by barryjj** [comment]
Update:  I noticed that while it looks like it loads successfully, when left long enough, AS still crashes even with the Early Access banners turned off.

Ok, I may have found the culprit -- I realized that I had recently tried the ability to sign in to ITAD using the connect feature; I have disconnected ITAD from my AS plugin and now the crashes seem to have stopped.

This would further back up the errors seen in the console in my first update dealing with cookies, SameSite and Secure settings.

**Comment by MxtOUT** [comment]
Could you do me a favor and try it again with ITAD connected?

On the background page, can you [create a timeline recording](https://developers.google.com/web/tools/chrome-devtools/memory-problems#visualize_memory_leaks_with_timeline_recordings)?
Make sure that you stop the recording before it crashes again

**Comment by barryjj** [comment]
> Could you do me a favor and try it again with ITAD connected?
> 
> On the background page, can you [create a timeline recording](https://developers.google.com/web/tools/chrome-devtools/memory-problems#visualize_memory_leaks_with_timeline_recordings)?
> Make sure that you stop the recording before it crashes again

Oddly, now it's not crashing.

[Heap-20200116T205232.heaptimeline.zip](https://github.com/tfedor/AugmentedSteam/files/4074673/Heap-20200116T205232.heaptimeline.zip)

The first time loading afterwards was pretty slow, but it eventually finished loading and displayed the greenlight.  I decided to reload the page and it was pretty fast overall to get to the finished status.  So I tried it a third time with the memory heap recording running and the result is attached.

Perhaps the cache just needed to be regenerated, either due to corruption or to updated URLs, etc.?

**Comment by MxtOUT** [comment]
That's odd, hm.
There weren't any other reports regarding this bug, so I'm hoping that this only occurred under very special conditions.
Please report back if you encounter it again

**Comment by dojima** [comment]
I was getting an unusually large amount of hard drive activity when visiting the Steam website with this version of Chrome and the Augmented Steam extension enabled.  Left alone, the hard drive activity would continue for a number of minutes before stopping.  The hard drive activity immediately stops when disabling the extension.  I didn't test the result of rebooting, but generally speaking, visiting other Steam pages or reloading the first Steam page afterward, even after closing and reopening Chrome, would not cause a repeat in unusual hard drive activity until the next day.    Unchecking the 'Show Early Access image banners' option more or less solved the problem.  There's still a small amount of excessive drive access, but it finishes within seconds.  I believe this first happened after updating to Chrome 79.

**Comment by MxtOUT** [comment]
Could you also create a timeline recording please?

**Comment by dojima** [comment]
Sure.  I'm not a developer, so how should I go about doing that?  Just follow the wiki's instructions for getting to the background page, click record under the Performance tab, then load a Steam page?  How long should I let it profile?

**Comment by MxtOUT** [comment]
Exactly, try to create a snapshot during the phases where the hard drive activity goes up.
You can also try a snapshot directly on a Steam page, since we don't know yet whether it's a problem with the background or the content script

**Comment by dojima** [comment]
All right, hopefully I did it correctly.  Took two from the background page and one from Steam.  The largest one is from the start of the issue, and the other two are as it concludes.

[snap.zip](https://github.com/tfedor/AugmentedSteam/files/4167820/snap.zip)

**Comment by MxtOUT** [comment]
Hm, I didn't find anything suspicious there, could you create a memory snapshot for both pages please?
![image](https://user-images.githubusercontent.com/14999077/74023800-c6f8a380-49a0-11ea-97a8-2a2664b658df.png)
(Select "Allocation instrumentation on timeline" and tick "Record allocation stacks")

**Comment by MxtOUT** [comment]
Let's continue in #760

**Comment by MxtOUT** [comment]
I did some debugging, the write operations are extremely slow on Vivaldi and Chromium.

Tests are all using the latest version of the browser

Vivaldi:
![image](https://user-images.githubusercontent.com/14999077/74027729-03c89880-49a9-11ea-95bd-137fdd854876.png)

Chromium:
![image](https://user-images.githubusercontent.com/14999077/74027755-1773ff00-49a9-11ea-96a7-6a19cdeec248.png)

Chrome:
![image](https://user-images.githubusercontent.com/14999077/74027834-42f6e980-49a9-11ea-945d-0213fdc9f770.png)

Firefox:
![image](https://user-images.githubusercontent.com/14999077/74027990-98cb9180-49a9-11ea-8079-e54e12f80e24.png)

I don't know why there's such a big difference...

**Comment by MxtOUT** [comment]
I found the issue, I just don't know why Firefox handles it that well
