### ISSUE TITLE
Fix Steam's notification button styling bug

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#739]
This happens on [some steam pages](https://store.steampowered.com/account/registerkey)
![image](https://user-images.githubusercontent.com/4411977/72472820-a09e7880-37e5-11ea-83c1-f15ba4400e84.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/4411977/72472930-e4917d80-37e5-11ea-9604-196ecb15594e.png)

I tried fixing it myself, but what works for the one page doesn't work for the other page. I can't find the underlying problem either. The HTML and CSS appears exactly the same on both pages, at least for this section.

**Comment by MxtOUT** [comment]
This one's Steam's bad, see without AS enabled

**Comment by Revadike** [comment]
> This one's Steam's bad, see without AS enabled

Yes, I am well aware. I just thought, since this has been a ongoing issue for a long time, it would be nice to fix it for at least AS users. Also, it does seem to affect the augmented steam menu positioning too.
