### ISSUE TITLE
Market price fetch not retrying due to bug

### ISSUE THREAD

**Issue by mocmocamoc** [tfedor/AugmentedSteam#743]
https://github.com/tfedor/AugmentedSteam/blob/1ceab9f242c9f2b81a4dcb5843ccc843a421f1fb/js/content/community.js#L3412

errorCode is actually an Error object rather than an integer, so this will not evaluate to true even when there actually has been a 429 error. Hence the market price will not be retried in these cases.

**Comment by Revadike** [comment]
Is there a property of the `errorCode` object that has the error code as value?

**Comment by mocmocamoc** [comment]
There's just the _message_ property which contains the error text, which is created [here](https://github.com/tfedor/AugmentedSteam/blob/9da41611eb991b4d01d62fdb7cb405edaccb4a5a/js/content/common.js#L507). It starts with "HTTP" and the status code, so this could replace the if clause above:

`if (errorCode.message.startsWith("HTTP 429")) {`
