### ISSUE TITLE
Was there a DRM notification?

### ISSUE THREAD

**Issue by andrewpros** [tfedor/AugmentedSteam#747]
Hi.

Just want to ask cuz i don't remember if it was in this extension.

Was there an option to show DRM warning on the steam game page, a warning box with for example denuvo protected game, this is now gone? It doesn't show anymore.

**Comment by candela97** [comment]
Which browser? Did you update the extension? This should be fixed in the latest version.

**Comment by JanPokorny** [comment]
You can test on this game: https://store.steampowered.com/app/526980/Handball_17/

It works for me (Firefox 72.0.2):

![obrazek](https://user-images.githubusercontent.com/4580066/72849624-67fc1480-3ca7-11ea-8e1f-50583dfa270b.png)

Note that a good alternative is to follow this curator: https://store.steampowered.com/curator/26095454-Denuvo-Games/

**Comment by andrewpros** [comment]
Well i did need to update and drm warning shows up again, but now price rates are not working and probably blocks other parts past some point, i dont see the WSGF data for example.

https://i.imgur.com/UMO85VM.png
