### ISSUE TITLE
Buggy behavior while scrolling wishlist

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#754]
https://store.steampowered.com/wishlist/profiles/76561198042965266/#sort=price

I suggest to disable itad pricing panel while scrolling.

**Comment by MxtOUT** [comment]
Yeah, sometimes it works, sometimes it doesn't, but why?
I like the idea though

**Comment by MxtOUT** [comment]
Or a whole other idea, which would clear this mess up:
We don't have to care about changing the positions of the list elements if the info is just displayed to the right of the element

**Comment by candela97** [comment]
Testing on Chrome 88 with the develop branch, the current solution doesn't work anymore, unless the scroll/resize event is re-registered...
The previous solution (removed in https://github.com/tfedor/AugmentedSteam/commit/908ba792bc6d5a85042f7958aaa0c22971f73e22) surprisingly works though.

**Comment by Revadike** [comment]
Related to https://github.com/tfedor/AugmentedSteam/issues/1037 ?

**Comment by candela97** [comment]
I don't think so. This issue is about wishlist rows overlapping the ITAD pricing panel while scrolling, right?

**Comment by MxtOUT** [comment]
> Or a whole other idea, which would clear this mess up:
> We don't have to care about changing the positions of the list elements if the info is just displayed to the right of the element

Hm, I don't think we have enough space there.

> I suggest to disable itad pricing panel while scrolling.

This seems like a better approach after all

**Comment by MxtOUT** [comment]
> Testing on Chrome 88 with the develop branch, the current solution doesn't work anymore, unless the scroll/resize event is re-registered...
> The previous solution (removed in [908ba79](https://github.com/tfedor/AugmentedSteam/commit/908ba792bc6d5a85042f7958aaa0c22971f73e22)) surprisingly works though.

Yeah, this worked, thanks!
I think the problem was that `OnScroll` was bound by `Function.prototype.bind()` in the event handler, thus creating a new function which we couldn't hook onto
