### ISSUE TITLE
[Suggestion] "Remove from Wishlist" button on game's page

### ISSUE THREAD

**Issue by axredneck** [tfedor/AugmentedSteam#758]
Sometimes it's faster to open game's page than open the Wishlist and search for the game.

**Comment by Revadike** [comment]
Already a feature

**Comment by axredneck** [comment]
@Revadike where is it? I can't find it.

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/73577097-591e1a80-447c-11ea-8007-c024efcf2db9.png)

**Comment by axredneck** [comment]
@Revadike it just opens Wishlist for me but doesn't remove the game from it.

**Comment by Revadike** [comment]
Then this should be a bug report. Are you sure Augmented Steam is enabled and running? Latest version?

**Comment by axredneck** [comment]
@Revadike yes, i use it's features a lot

**Comment by axredneck** [comment]
Excuse me, it works, i just didn't know i need to press this icon:
![73577097-591e1a80-447c-11ea-8007-c024efcf2db9](https://user-images.githubusercontent.com/20617900/73745033-27020680-4763-11ea-90a7-933701ee1553.png)

**Comment by Revadike** [comment]
Not on the icon specifically. The whole button should work.

**Comment by axredneck** [comment]
Now it works for some reason ...
