### ISSUE TITLE
Version update changelog message keeps popping up

### ISSUE THREAD

**Issue by AsadAlrafidain** [tfedor/AugmentedSteam#759]
Every new browser session, when I open a tab for steamcommunity.com or store.steampowered.com , augmented steam greets me with a changelog message as if it just got updated, happens only on one of my vivaldi browser installations although I have both installations set up the same way, even the same addons and settings

Browser: Vivaldi version 2.10.1745.27 (Stable) (32-bit)
Augmented steam version: 1.4.1

Edit: I noticed that another steam related addon (tampermonkey script to be more accurate) steam economy enhancer keeps getting it's preferences reset, and this issue disappeared upon disabling augmented steam.

**Comment by MxtOUT** [comment]
Could you [set a breakpoint](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#setting-a-breakpoint) at core.js:131 and report the values of `lastVersion` and `currentVersion`?

**Comment by AsadAlrafidain** [comment]
> Could you [set a breakpoint](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#setting-a-breakpoint) at core.js:131 and report the values of `lastVersion` and `currentVersion`?

Ok, first of all I have to say that I have little to no experience with the debugger, but I tried following the instructions on setting a breakpoint and this is what I got:

![Untitled](https://user-images.githubusercontent.com/60561484/74035159-cc6ae380-49ca-11ea-9188-32496f144ce4.jpg)


I hope these are the values You asked me to find

**Comment by MxtOUT** [comment]
The screenshot is good, but everything is as it should be.
Did the changelog show up after that?

You can also set a breakpoint at line 139:
At this point you can still see the variables and the changelog should have popped up.

It would be helpful if you can create this scenario

**Comment by AsadAlrafidain** [comment]
the problem is the changelog (and preference reset) appears only the first tab ( steamcommunity or steam store) I open in a given browser session, after that I have to close the browser and open it again to recreate the scenario, so unless I can start the browser with the debugger forced on, I don't think the cause will appear in the debugger

I'm not tech-savvy, but I get the feeling that when I enable augmented steam, some browser files get read-only properties, as I noticed it also affect other script (steam economy enhancer), and also some speed-dial bookmarks (which is a vivaldi feature" loose their thumbnails...these problems disappear when I disable Augmented Steam

**Comment by AsadAlrafidain** [comment]
Ok, so I managed to recreate the scenario while Debugger is enabled and this is what I got:

![Untitled](https://user-images.githubusercontent.com/60561484/74049034-5b382a00-49e4-11ea-8c34-51296d0199b6.jpg)

**Comment by MxtOUT** [comment]
I'm afraid that this is out of our scope.
It seems like your browser doesn't save some preferences, but this can't be related to Augmented Steam (especially the preferences of the other scripts)

**Comment by AsadAlrafidain** [comment]
Ok so I don't know why I didn't try this before...
I removed Augmented Steam extension and installed it again, now the issues disappeared.
I just wanted to mention that the issues started when the addon got updated, so may be something went wrong during the update process.
