### ISSUE TITLE
Issue with EU pricing on tooltips

### ISSUE THREAD

**Issue by dgc1980** [tfedor/AugmentedSteam#76]
https://i.imgur.com/kswrxXk.png

been happening since I changed to your fork on Chrome , since the original stopped working after AUD was added

as per the image, the EU price shows up as AUD

this seems to be happening with a friend in UK also, shows GBP price in place of EUR using Firefox

**Comment by k0zyrev** [comment]
same issue, EU just repeats current currency

**Comment by KarlCastle** [comment]
This is because the `/api/packagedetails/` call in `StorePageClass.showRegionalPricing` is sending "&cc=eu1" which Steam is ignoring.

I'm not sure what the correct cc is? 'eu' gets a USD price, 'eu2' and 'eur' get local prices.

**Comment by KarlCastle** [comment]
Oh. It looks like "eu1" has been replaced by country specific country codes?

be, fr, de, it, cz, es, pt, nl, gi, gr, ee, fi, ... all seem to return EUR
