### ISSUE TITLE
Some type of memory leak on certain pages (game tag pages)

### ISSUE THREAD

**Issue by infekSK** [tfedor/AugmentedSteam#760]
Not sure how I can explain the issue but if I go on any tag website e,g: https://store.steampowered.com/tags/en/CityBuilder it does some weird hanging and the page barely loads, my CPU fan speeds right up and my FF task manager puts this extension at high energy impact. I've tested the same page without this extension enabled and everything is fine. 

I have noticed that the loading bar loads _really_ slow and never fully completes, I also noticed that if a particular title has been ignored, there will be [multiple](https://user-images.githubusercontent.com/15379158/73907685-05d02000-48f3-11ea-8345-438f0f2774c3.png) 'not interested' tags, and I'm curious if this could be a reason.

Using latest version of AS (1.4.1) and latest Firefox (72.0.2 64bit)

If there's anything I can add let me know, the issue has only been happening the past week at the very least (I only noticed yesterday).

**Comment by candela97** [comment]
Should be fixed by 665216bf0c4e4a75b044ba1ad5a4a1b7509a4856. In the meanwhile, checking the corresponding option under "Highlight" (in your case "Items marked not interested") seems to prevent this problem.

**Comment by MxtOUT** [comment]
@infekSK Could you do a performance record when this happens?
F12 > "Performance" tab

**Comment by infekSK** [comment]
What @candela97 suggested fixed the issue. 

@MxtOUT I re-enabled the option I was told to disable and the issue has gone completely, I'm wondering if disabling and re-enabling fixed it, there's no longer multiple tags of 'not interested'.

Very peculiar. I guess it's solved for now?

**Comment by candela97** [comment]
I'm not clear why either. I guess that's why I didn't notice problems when I tested, because I always had both options enabled. See if you can sideload the develop branch to test if there're still problems without the workaround.

**Comment by MxtOUT** [comment]
This is super weird, this was also reported multiple times in #731

**Comment by MxtOUT** [comment]
I did some debugging, the write operations are extremely slow on Vivaldi and Chromium:

Vivaldi:
![image](https://user-images.githubusercontent.com/14999077/74027729-03c89880-49a9-11ea-95bd-137fdd854876.png)

Chromium:
![image](https://user-images.githubusercontent.com/14999077/74027755-1773ff00-49a9-11ea-96a7-6a19cdeec248.png)

Chrome:
![image](https://user-images.githubusercontent.com/14999077/74027834-42f6e980-49a9-11ea-945d-0213fdc9f770.png)

Firefox:
![image](https://user-images.githubusercontent.com/14999077/74027990-98cb9180-49a9-11ea-8079-e54e12f80e24.png)

I don't know why there's such a big difference...

**Comment by MxtOUT** [comment]
Since 665216bf0c4e4a75b044ba1ad5a4a1b7509a4856 likely fixes this, I'm closing this

**Comment by MxtOUT** [comment]
I found the issue, just don't know why Firefox handles it that well
