### ISSUE TITLE
High CPU usage / page does not respond after a few seconds

### ISSUE THREAD

**Issue by spajdrEX** [tfedor/AugmentedSteam#797]
Hello,
when I'm logged under my account and then going to the page
https://store.steampowered.com/updated/all/
Firefox CPU usage is hovering between 15-35% all the time and the page stops responding after a few seconds.
Any idea what is causing this? I had this problem for a few weeks and just found it's this addon doing it.

Thanks in advance
Marek S.

**Comment by spajdrEX** [comment]
Just tested it via Chrome, for like 10-20 seconds it's running fine but than same issue as running that page under Firefox.

**Comment by MxtOUT** [comment]
Duplicate of #760
