### ISSUE TITLE
Price comparison base country is wrong.

### ISSUE THREAD

**Issue by AR45H** [tfedor/AugmentedSteam#804]
In the latest update in the price comparison panel, the primary currency that is being compared against is chosen by IP instead of account store country which should be the default behaviour. This can not be changed manually.
![image](https://user-images.githubusercontent.com/20746569/76143617-2f18d300-608e-11ea-9883-078cd947599b.png)
As you can see in this picture my store country is Argentine as is apparent by the currency on the bottom but the extension is comparing Germany's Euro (I am connected to a Germany VPN) to other currencies. This was not the case before the update.

**Comment by AR45H** [comment]
Update: It seems to have just been fixed on its own. Looks to be random.

**Comment by MxtOUT** [comment]
Yeah, we've been encountering this problem multiple times.
We're depending (amongst other things) on a cookie set by Steam, which sometimes seems to be not set correctly
