### ISSUE TITLE
AS menu opens automatically if I open web browser

### ISSUE THREAD

**Issue by gizellos** [tfedor/AugmentedSteam#806]
If I open Chrome, AS menu will open automatically and I have to close it by clicking on the arrow. Clicking anywhere on the steam page won't close the menu.

I suspect the ITAD auto sync doing this because it didn't happen when I wasn't using it.

**Comment by MxtOUT** [comment]
You're on the latest AS?
You mean this only happens when you enable "Periodically import to ITAD waitlist/collection"?

**Comment by gizellos** [comment]
Yes, it's on 1.4.1. I activated the ITAD auto sync after I updated to this version so it is either because of this function or the version itself.

However it didn't happen since I wrote this issue. I will close this issue and open it if it happens again.
