### ISSUE TITLE
[Feature Request] Separate Youtube and Expand Video functionalities 

### ISSUE THREAD

**Issue by Black3ird** [tfedor/AugmentedSteam#813]
Dear Sir,

Thank you so much for keep _updating_ Augmented Steam as it has surpassed its ancestor thanks to your efforts. I'm using Chrome version of Extension and was Turning _On_ the show Youtube Videos "embedded" into Steam Store Page Trailer feature for ease. But the Database of Videos are working most of the time 50% so that it's hit or miss that usually _Not_ worth to keep that feature always on.

Adding on top of that the mandatory "Spectre Isolation" feature of modern browsers, Chrome Memory Usage is DOUBLED for each tab opened for Steam Store as on **Average** it's ~100Mb for Steam Store page and "another" ~100Mb just for Youtube Video _even if_ you may NEVER play the Youtube Video at all. After noticing such consumption with questionable aid of the feature due missing videos, I turned that feature _Off_.

However, I was also using "Video Expand" Button (Dual arrows pointing SW and NE) that was TIED to that Youtube Feature (I didn't know they were tied so I'm asking to make them _Separate_) so to see Steam Store Official Trailers Extended to provide "Theatre View" (Centered, Enlarged, usually Dimmed) like many Video sites are featuring right now. So turning off the Youtube Feature due memory consumption also took my ability to see Trailer in relaxed manner as I have to find other ways to reach that Theatre View now.

So what I'm asking for you to just SEPARATE already existing but "Bound" functions of Youtube Videos and Expand Videos by TWO checkboxes in Settings instead of One checkbox that's enabling or disabling both. Since Coding of both functions are there, there should not be much of a problem for you REARRANGE already written code to achieve what I asked of you _without_ having to code much anything unlike most other requests.

So I'm asking a Setting looking like this:

☑️ Show YouTube gameplay videos on app pages

☑️ Show YouTube review videos on app pages (and)

☑️ Show Expand videos button on app pages (will be added by you)

If necessary, the location of current button that resides on Top Right Corner of Images can be relocated to something more suitable if you like. Please give more thought about this...

Best Regards.

**Comment by candela97** [comment]
If you've disabled showing youtube gameplay videos on app pages, the expand slider should appear on the top right corner of screenshots or trailers once you hover over them:
![註解 2020-03-20 183901](https://user-images.githubusercontent.com/54083835/77156319-1f5fac80-6ada-11ea-95d6-7faca639504f.jpg)

**Comment by Revadike** [comment]
After hearing your concerns, I think the YouTube tab should be disabled by default. I rarely use it myself too and therefore is a huge waste of recourses.

**Comment by MxtOUT** [comment]
> After hearing your concerns, I think the YouTube tab should be disabled by default. I rarely use it myself too and therefore is a huge waste of recourses.

No, the iframe is only being loaded when you click on the tab.
I *think* there existed an issue that suggested also adding the review YT player to the tabs.
This would then reduce the memory usage.
