### ISSUE TITLE
[Feature Request] Hide Early Access games in search

### ISSUE THREAD

**Issue by scowalt** [tfedor/AugmentedSteam#815]
Add it to this section:
![image](https://user-images.githubusercontent.com/1100550/77170308-16d68a00-6a78-11ea-8c51-ada871d7e01c.png)

Context: I generally like to wait until games are out of Early Access to play them. I would love the ability to filter out all of the games that aren't finished yet when I'm looking for things to play.

**Comment by candela97** [comment]
Doesn't this work?
![註解 2020-03-20 221221](https://user-images.githubusercontent.com/54083835/77172128-72e0f300-6af8-11ea-9088-6b94c3ab268f.jpg)

**Comment by scowalt** [comment]
> Doesn't this work?
> ![註解 2020-03-20 221221](https://user-images.githubusercontent.com/54083835/77172128-72e0f300-6af8-11ea-9088-6b94c3ab268f.jpg)

That depends on the user tag "Early Access". Not every Early Access game will get the user tag "Early Access" (For example, [Mechanica](https://store.steampowered.com/app/1226990/Mechanica/)) Also, when a game leaves Early Access, the "Early Access" user tag isn't removed. (Example: [Wreckfest](https://store.steampowered.com/app/228380/Wreckfest/)).

Therefore, filtering by the user tag will have both false positives and false negatives, which makes it unreliable.

**Comment by candela97** [comment]
I suppose you can use this with AS enabled then:
![註解 2020-03-20 234129](https://user-images.githubusercontent.com/54083835/77180154-7d08ee80-6b04-11ea-93f4-faa5c098ccbc.jpg)

Also if you're interested, this feature works by searching for a match in the element's `ds-tagids` dataset property (492 = early access):
![註解 2020-03-20 221221](https://user-images.githubusercontent.com/54083835/77180688-4089c280-6b05-11ea-9357-1ece37b46298.jpg)
which is information provided by Steam, so I have no idea why their native implementation can somehow be "unreliable". You might want to post about this on the steamlabs discussions.

**Comment by MxtOUT** [comment]
@candela97 This array contains the tag ids of the most popular user defined tags.
So this is not something that Steam / the devs have any control over
