### ISSUE TITLE
Firefox's First Party Isolation will cause AS's warning banner show up

### ISSUE THREAD

**Issue by Whoareyouagain** [tfedor/AugmentedSteam#818]
I turned on First Party Isolation in Firefox via about:config by enabling privacy.firstparty.isolate. Then AS threw off a warning:
`Make sure that you are logged into steamcommunity.com in order to be able to use all features of Augmented Steam.`
I was confused because I knew that I am logged in both domain and it still showing me the errors. Took me to realize that it was privacy.firstparty.isolate was causing this. I tested it by disabling the first party isolation then the warning disappeared. I turned it back on, then warning came back on even that I triple-checked that I am logged on in both site. 

I am not sure what AS features are being impacted with First Party Isolation enabled. I couldn't tell the difference with it. I am not a power user of AS, I only use AS for checking ITAD for other stores that have better pricing. So I couldn't tell what feature is being impacted with the option enabled in Firefox.

Version List:
OS: Window 10 1909
Firefox: 74.0
AS: 1.4.2

**Comment by scowalt** [comment]
Unless Firefox is considering turning First Party Isolation on by default, I wouldn't consider this a bug in Augmented Steam.

I don't think it should be an expectation of any project to support non-standard browser configurations, unless they are going to become mainline. It looks like First Party Isolation has been in Firefox for over two years, and there's no indication that either Firefox or the web platform as a whole will pick this up as a default behavior.

**Comment by MxtOUT** [comment]
Exactly what @scowalt said :)
