### ISSUE TITLE
[Feature request] Add ITAD tags similar to ITAD highlight option in settings

### ISSUE THREAD

**Issue by enchained** [tfedor/AugmentedSteam#819]
ITAD was integrated with AS https://github.com/tfedor/AugmentedSteam/issues/338 and it is very useful. We can highlight titles we have on other stores etc, but when you own it both on Steam and in another place, the highlight will override. Same with wishlist/waitlist.

I was thinking about the way to display both ITAD and Steam info on the pages with many games.
As far as I remember we have tags to display the additional info while avoiding the highlight override. They work with search results, package and bundle pages, but there's no option to use ITAD-related tags for now, only highlights.

And I don't see any tags on the main and sale pages (although it might be tricky to implement due to the lack of space (maybe an icon with one letter and a tooltip will suffice?)).

**Comment by candela97** [comment]
Should be fine to add the tags. Only need to add the corresponding translation strings and options.

> And I don't see any tags on the main and sale pages (although it might be tricky to implement due to the lack of space (maybe an icon with one letter and a tooltip will suffice?)).

Any example pages/items that you think should be tagged? And yes some items are excluded due to insufficient space.
