### ISSUE TITLE
"Install Steam" button replace/hide option doesn't work

### ISSUE THREAD

**Issue by lainverse** [tfedor/AugmentedSteam#824]
I've checked all 3 modes (Show / Hide / Replace with "View in Client"), but in all 3 cases "Install Steam" button is shown and "View in Client" is nowhere to be found. 

It looks like `handleInstallSteamButton` function in content/common.js targets wrong button `div.header_installsteam_btn` (that one in header which AS replaces with own menu anyway) instead of `.game_area_already_owned_btn > a[href*="/store.steampowered.com/about/"]` (which only visible for owned games).

BTW, there's `removeAboutLink` function in content/store.js which actually targets that button controlled by option `Hide "About" link` and actually hides it. Except, it's labeled "Install Steam" and prompts to download and install Steam.

**Comment by Revadike** [comment]
It works here. I think what you're experiencing is SteamDB's extension removing the button. 
![image](https://user-images.githubusercontent.com/4411977/78270272-e75d5e00-750a-11ea-9dad-7afd3041d18b.png)

There is a 2nd install steam button, the one you're talking about, which originally wasn't even considered for this feature. However, the `Hide "About" link` option handles that case. But I agree the name for that option is somewhat confusing.

**Comment by lainverse** [comment]
Ah, I think I know what's wrong. I also have SteamDB extension installed and it also hides this button. Just disabled it and button appeared in the header. Not an issue then, but names of these options really should be more clear. Especially `Hide "About" link` since nowhere in the interface it's called "About". It literally called "Install Steam".

**Comment by candela97** [comment]
That option does remove "About" links (it's under the "Store" dropdown if you're logged in), and the "Install Steam" button is removed because...well it links to the "About" page. I personally don't think it is all that useful though.

I kinda agree the button should work with our existing setting. I'll make a PR and see what the maintainers think.
