### ISSUE TITLE
"Current best" and "Historical low" prices are wrong in UAH (Ukrainian Hryvnia)

### ISSUE THREAD

**Issue by lainverse** [tfedor/AugmentedSteam#827]
![chrome_iqU8VmdfrD](https://user-images.githubusercontent.com/4563325/78281788-e553c900-7523-11ea-8cbd-3a16a565ed96.png)

Looks like instead of using regional prices AS uses there prices from US converted to UAH. Most of the time this generates prices which are nowhere near to the actual one (unlike SteamDB on the same screenshot).

In some cases percentage of a discount is slightly off too (±1%, but that's not important).

Curiously enough price in comparison list is actually fine:
![chrome_dpjHYl1haU](https://user-images.githubusercontent.com/4563325/78282856-a0309680-7525-11ea-83fe-08f46d2ff7f6.png)

**Comment by MxtOUT** [comment]
Duplicate #482
