### ISSUE TITLE
Wishlist export not ordered

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#835]
It used to keep the current order of the wishlist, when exporting in text form, but now it always orders by appid.

**Comment by MxtOUT** [comment]
These are the normal ordering rules of objects.
Where did this work differently?

**Comment by Revadike** [comment]
> These are the normal ordering rules of objects.
> Where did this work differently?

I may be misremembering, but I believe it used to keep the order, like if wishlist was ordered by date added, the export to text will also export it into that order. 
To do this, you just have to use the array order from some global variable, but I'll look into it later.

**Comment by MxtOUT** [comment]
Yeah, that global variable is `g_rgAppInfo`, but that's ordered by appid

**Comment by Revadike** [comment]
It's `g_Wishlist.rgAllApps`. This array is always sorted by the order the user picked.
