### ISSUE TITLE
Wrong game price shown !

### ISSUE THREAD

**Issue by Nsan** [tfedor/AugmentedSteam#837]
Hello,

Just came across this issue. The game **Dark Light** is referenced as the so similar title **DarkLight** and the price displayed of the second one is present if you have the first one listed in your wishlist !

Dark Light : https://store.steampowered.com/app/1134520/
DarkLight : https://store.steampowered.com/app/1216370/

![darklighgt](https://user-images.githubusercontent.com/614275/78388417-3fff2a80-75e1-11ea-8d5c-3f9a0150fcbe.png)

Thanks :)

**Comment by MxtOUT** [comment]
Hey, this is an ITAD issue, please report it there :)
