### ISSUE TITLE
Disappearing notes

### ISSUE THREAD

**Issue by GiantLizard** [tfedor/AugmentedSteam#848]
I use a lot the option to Add a note into a game's page. Sadly sometimes it doesn't save it and I don't know why. If I reopen the game's page (be careful, opening, not just refreshing it) sometimes the note has simply disappeared.

**Comment by MxtOUT** [comment]
Yeah, this sadly happens due to storage limitations, we're working on finding a solution to this problem

**Comment by GiantLizard** [comment]
I see, thank you :) it seems like that limit has been actually reached right now because I can't put notes anymore, on any game :/

**Comment by Revadike** [comment]
@MxtOUT Maybe close the duplicate issues to keep things organized?

**Comment by yaron-dav** [comment]
Even if this is somehow still unsolvable (very big problem for me, while augmentedsteam has a lot of nice features I like, adding notes/comments is the main reason I have for using it, and the one that caused me to start using it in the first place, and I now reached the state where it's apparently useless) maybe at least show some clear message when that limit is hit?

Being told that it's not possible to add a note is a problem, but it's a much much much smaller problem that going on adding notes and comments to games, to only later see something that should have had a note and doesn't, wondering how much info I thought was important to keep was silently lost. Having notes silently disappear is much worse than not having the ability to add notes in the first place.

And I'd think it should be easy to check automatically? Even if writing to the storage doesn't return any error messages and doesn't have a way to check if it's at max ( really? ), at least after trying to write a note it would be possible to try to immediately read it back, and see if it actually loads or nothing is returned.
