### ISSUE TITLE
[Suggestion] Compare store prices in local AND set currency

### ISSUE THREAD

**Issue by KitsuneFM** [tfedor/AugmentedSteam#87]
The comparing prices feature has been great since original Enhanced Steam. I prefer it to set to EUR, as it's my region in most of the sites. BUT on Steam I got different currency (PLN). Would be nice to optionally make it set to both my local currency and the one I set additionaly. It's not a big deal, since my browser can convert currencies on its own, but thjat way it would be faster.

If You decide to make this to the code, I suggest to be it like:
**Current Lowest Price: SET (LOCAL)**

So e.g. it would be for me like that:
**Current Lowest Price: 56,49€ (244,86zł)**

**Comment by BrutuZ** [comment]
Like #53 ?

**Comment by KitsuneFM** [comment]
No, I meant it... [Like that](https://i.imgur.com/91w5KWJ.png)

The current and historical lowest prices display normally only set currency (so either EUR or PLN), but would be cool to have an optional feature to make it to both set price and the local currency price in a bracker, like in the edited pic.

I usually prefer to see original prices but I also convert them to see how it is in PLN. But I still want to see original price as well. It's not a big deal, cause as I said, Opera can convert currencies just by highlighting them.
