### ISSUE TITLE
Cannot open send a message dropmenu

### ISSUE THREAD

**Issue by MetalfanBlackness** [tfedor/AugmentedSteam#879]
I am using Firefox 75.0 with all only "Augmented Steam" and "Livemarks" add-ons enabled and cannot click on the "Send a Message" button, to get the dropdown for sending a message.

The version of augemented steam I am running is: 1.4.4

Steps to reproduce:
* Go directly to a friends page https://steamcommunity.com/id/{steamid} (for me https://steamcommunity.com/id/MfBTrade)
* Try to push the button "Send a Message" to get the dropdown.

What did I found during debugging community.js (sorry I am not a javascript developer, might have same terminology wrong):
On my PC the debugger executes the function chatDropdownOptions. I does the HTML replace from: HTML.replace(sendButton, ....
Then it executes the document.querySelector("#btnWebChat").addEventListener("click", () => { (cannot really tel if this goes wrong or something)
It does **not** execute the document.querySelector("#profile_chat_dropdown_link").addEventListener("click", () => { as far as I can see, this should be the place for adding the clicking functionality.

Can someone help me and see if this is only broken on my pc and/or how I can better debug this problem

**Comment by MxtOUT** [comment]
Fixed by #878
