### ISSUE TITLE
[Suggestion] Steam Skins

### ISSUE THREAD

**Issue by KitsuneFM** [tfedor/AugmentedSteam#88]
I just came by some random idea. As there is an option to set color for profiles, it would also be cool to make this possible for whole site. Like making Steam pink, black or red for example.

**Comment by skrrt** [comment]
seconded. would also like to see the old grey Steam site be reintroduced as such a theme.

**Comment by Revadike** [comment]
Perhaps implement a browser of userstyles styles for steam.

**Comment by MxtOUT** [comment]
While that feature would be nice to have, the layout of, for example, the front page changes way too often and it wouldn't be very light to maintain.
Also, older skins (like the grey one mentioned) would be missing certain features that the current one contains

**Comment by Revadike** [comment]
I think this would be a prime candidate for https://github.com/tfedor/AugmentedSteam/issues/1073
