### ISSUE TITLE
Add "Skip You are leaving Steam" page option

### ISSUE THREAD

**Issue by Korb** [tfedor/AugmentedSteam#890]
![2020-05-10_01-22-03](https://user-images.githubusercontent.com/3509797/81486337-c0f2b700-925c-11ea-83b5-de3c53623aac.png)
For example:
```
    getParameterByName = function(name) {
        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
            results = regex.exec(location.search);
        return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
    }
    var filteredLink = getParameterByName('url');
	if (!!window.location.hash) {
        var filteredLink = filteredLink + window.location.hash;
    }
    window.location = filteredLink;
```

**Comment by Revadike** [comment]
uh, check options: 
![image](https://user-images.githubusercontent.com/4411977/81486833-f2b54f00-9257-11ea-8ef4-bd3e7a46f34b.png)

**Comment by candela97** [comment]
I've proposed to move this option to a more appropriate section in #875

**Comment by Revadike** [comment]
Also, I think this should be enabled by default

**Comment by deluxghost** [comment]
I think it's better to let us config a skip website whitelist and check the domain. This way is safer, normally you will only meet a few websites on steam, for example, mod website, github, cloud drives, etc.

**Comment by deluxghost** [comment]
Oh BTW, with this idea, you could also add a "Trust Forever" button on the warning page

**Comment by candela97** [comment]
Nice idea, opened an issue for that

**Comment by MxtOUT** [comment]
Tracked in #895
