### ISSUE TITLE
Regional price, not showing on some games

### ISSUE THREAD

**Issue by N3ars** [tfedor/AugmentedSteam#894]
Example : https://store.steampowered.com/app/838380/DEAD_OR_ALIVE_6/

console : ![image info](https://i.imgur.com/TGAphEi.png)

but this doesnt work only when on price mouseover is enabled, ![image info](https://i.imgur.com/Bw2FWGK.png)

**Comment by MxtOUT** [comment]
Do you have some more examples of apps that fail with this message?

**Comment by N3ars** [comment]
I can't see price on the bundles, but i think its normal right ?
I didnt find any other games, i guess DOA is an exception.
