### ISSUE TITLE
Wishlist button no longer removes app

### ISSUE THREAD

**Issue by dmlemos** [tfedor/AugmentedSteam#904]
The wishlist button on the app page used to removed it from the wishlist when clicked. But now it just opens the wishlist page, which unfortunately takes ages to load.

Hope this is a bug and not as intended. This feature alone was worth installing the extension.

**Comment by candela97** [comment]
Are you using the latest version of the extension? What browser are you using? Does the icon change when you mouseover the wishlist button? Like this:
![註解 2020-06-02 222431](https://user-images.githubusercontent.com/54083835/83531820-09318c00-a520-11ea-896c-b7fc03e00e9d.jpg)

**Comment by dmlemos** [comment]
The button was not changing upon mouseover. I got to the bottom of it. It turns out the extension must have been using old site access. It was only given access to "store.steampowered.com" (which is not on the automatically list).

I've allowed access to all sites, which include:
* "*.steampowered.com"
* "steamcommunity.com"
* "*.isthereanydeal.com"
works fine now :)
