### ISSUE TITLE
feature request: remove "you are now leaving steam" page for links.

### ISSUE THREAD

**Issue by yarrmateys** [tfedor/AugmentedSteam#906]
whenever you click on any external link, instead of going there you're getting this annoying notice where you have to scroll down and click continue to external site. could this be automated by stripping the link filter part, so direct links are properly direct?

**Comment by Revadike** [comment]
This is already possible, check your AS settings.

**Comment by yarrmateys** [comment]
oh. i was searching for wrong keywords. nevermind then.
