### ISSUE TITLE
Firefox rendering bugs in achievement comparision

### ISSUE THREAD

**Issue by ThisIsABug** [tfedor/AugmentedSteam#907]
![image](https://user-images.githubusercontent.com/19193534/84862513-9a057d00-b073-11ea-9282-a77997ae482f.png)

Firefox 77.0.1(64-bit)

Possible fix:
- remove the following images (the rounded corners are done with css already anyway)
https://steamcommunity-a.akamaihd.net/public/images/skin_1/statsSummaryBoxTop.gif
https://steamcommunity-a.akamaihd.net/public/images/skin_1/statsSummaryBoxBottom.gif

- add `<div style="clear:both"></div><br>` after `div.topAvatarsRight`

Additional small fix:
- replace `padding:5px 6px 0 0` with `padding:2px 0 0 0` on `div#topSummaryAchievements`

Additional small bug:
- remove duplicate colon after the text 'Achievements Earned::' inside `div#topSummaryAchievements`

EDIT: actually only the avatars being below the first box of achievements seems to be an AugmentedSteam bug in firefox, the rest is even there without the extension and also in Chrome. But since your extension changes the layout, maybe you could be so nice and fix the other stuff too?

**Comment by candela97** [comment]
The bug shown in the screenshot is due to
https://github.com/tfedor/AugmentedSteam/blob/5cd57701c855544cc41d16d15f26b0f91da3c959/js/content/community.js#L1526
A simple fix would be to exclude `br` elements that have the `clear` attribute
```js
for (let br of personal.querySelectorAll(":scope > br:not([clear])")) br.remove();
```

For the small fix, I honestly don't see much difference, as for the achievement text, see https://github.com/tfedor/AugmentedSteam/issues/490#issuecomment-527590625. IMO there's not much point in fixing a stray colon, might as well fix the whole string altogether.

**Comment by MxtOUT** [comment]
I can reproduce this on the live version on Firefox, but not on the development version (branch featureModules)

**Comment by candela97** [comment]
> I can reproduce this on the live version on Firefox, but not on the development version (branch featureModules)

That's strange...I can still reproduce this with the current develop branch.
I came up with the fix by looking at the page html:
![issue](https://user-images.githubusercontent.com/54083835/101519580-2e241300-3938-11eb-9596-69b59d74da2b.jpg)
If you remove this `br` element like we're doing in the code, the bug in OP's screenshot appears.

**Comment by MxtOUT** [comment]
I have solved it now by only selecting the <br> elements that sit in between achievements.
I guess I couldn't reproduce it before because I was selecting the default sorting option where the transformation code won't run
