### ISSUE TITLE
Developer and Publisher search mixed up

### ISSUE THREAD

**Issue by hgdagon** [tfedor/AugmentedSteam#909]
When replacing developer/publisher homepage links to search (awesome feature, btw), the links are mixed up should be the other way around. Noticed just now, so it must have been introduced in one the latest updates.

**Comment by Revadike** [comment]
I thought we fixed this. What store page?

**Comment by hgdagon** [comment]
Um... every page?

**Comment by hgdagon** [comment]
Hmmm... Actually no, not every not every page. I don't remember which page I noticed it on when I started this issue, but on `Serena`'s page it's mixed up, on `Payday 2` it's not... So, yeah... at least 2 pages.

**Comment by Revadike** [comment]
I can't find Serena's page, can u link me?

**Comment by hgdagon** [comment]
@Revadike https://store.steampowered.com/app/272060/Serena/

**Comment by Revadike** [comment]
> @Revadike https://store.steampowered.com/app/272060/Serena/✔

Looks fine to me.  Are you sure you're on the latest version of AS?

**Comment by hgdagon** [comment]
> Looks fine to me. 

On my side it's still switched. I also found a few other examples, but they have the same developer and publisher.

> Are you sure you're on the latest version of AS?

I'm not... It's weird, I'm on 1.4.0, mozilla page says 1.4.6, but when I press "check for updates", it says "no updates found". Anyway, seems like the problem on my side. Sorry for wasting your time.

P.S. the new GitHub does not send me notifications for this issue. WTF?

**Comment by Revadike** [comment]
So, did the update fix it?

**Comment by hgdagon** [comment]
It did, yes. I had to uninstall, and then manually reinstall from Mozilla's website. Waterfox's add-ons manager page says 1.4.6 is incompatible (which is probably why it wasn't updating), yet I do see the changes on Steam. What sucks is it seems like I'm gonna have to update manually every time...

**Comment by Revadike** [comment]
Maybe close this and open a new issue for the update bug.

**Comment by candela97** [comment]
Minimum browser version has been bumped to Firefox 57 since 1.4.1, so WaterFox might not be supported.
