### ISSUE TITLE
Custom Backgrounds/Colours option missing since edit profile page was changed

### ISSUE THREAD

**Issue by mdoyle-cvi** [tfedor/AugmentedSteam#913]
Since the new options page was added today, I can no longer see the option to choose custom backgrounds/profile colours, which means I am also unable to switch them off.

**Comment by likecyber** [comment]
While we all waiting for new update, you can remove custom background from your profile by using this link.
https://esapi.isthereanydeal.com/v01/profile/style/edit/delete/

**Comment by MxtOUT** [comment]
This will be fixed by https://github.com/tfedor/AugmentedSteam/commit/720a4273746e998e31d06ba8330a28d6704e1f96 to https://github.com/tfedor/AugmentedSteam/commit/4a63d5b15015d9f32c9ff6b78a1dc5e1a2d3ac1a when the next update releases

**Comment by MxtOUT** [comment]
> While we all waiting for new update, you can remove custom background from your profile by using this link.
> https://esapi.isthereanydeal.com/v01/profile/style/edit/delete/

This actually removes the custom style/theme, if you have a custom background this can be deleted with https://esapi.isthereanydeal.com/v01/profile/background/edit/delete/

**Comment by candela97** [comment]
For anyone encountering issues with these sections not showing up on the profile edit page, here are the new endpoints to remove them:
`https://api.augmentedsteam.com/profile/background/delete/v2`
`https://api.augmentedsteam.com/profile/style/delete/v2`

**Comment by scoobydooami** [comment]
I am having this problem still today in 2026.  The esapi.isthereanydeal.com website gets a *problem loading page* error. Is there any way I can still get rid of a custom background I did long ago. I have looked at settings in Augmented Steam and I cannot find anything there to do it.

Any assistance appreciated
