### ISSUE TITLE
AugmentedSteam keeps changing my profile background

### ISSUE THREAD

**Issue by zubairamrani** [tfedor/AugmentedSteam#917]
I changed my profile steam background a long time ago, but after steam updated their site, I can't seem to find the option to change it.

Now when I change my profile background in steam legit option and open my profile it stays for half a second, then when the extension loads it revert back to the old background which I can change anymore, removing the extension or using another browser fixes it, but as soon as I install the extension back again, the issue also comes back.

**Comment by Revadike** [comment]
https://github.com/tfedor/AugmentedSteam/issues/913
