### ISSUE TITLE
Default Price not working

### ISSUE THREAD

**Issue by baxenko** [tfedor/AugmentedSteam#918]
I chose UAH by default, but it does not appear during conversion.
![image](https://user-images.githubusercontent.com/36725292/85997349-1011c880-ba12-11ea-8354-3a4cf8f7b266.png)
![image](https://user-images.githubusercontent.com/36725292/85997373-1738d680-ba12-11ea-815f-395d05a648ba.png)

**Comment by supakorn-ras** [comment]
Can you check the developer console? I might have the same problem as you. For me, my console says error:
```
Error: Could not establish conversion rate between AUD and THB
    inCurrency moz-extension://02348f77-ece7-44f1-b75c-e9f1c0987e64/js/content/common.js:978
    showRegionalPricing moz-extension://02348f77-ece7-44f1-b75c-e9f1c0987e64/js/content/store.js:427
    AppPageClass moz-extension://02348f77-ece7-44f1-b75c-e9f1c0987e64/js/content/store.js:650
    <anonymous> moz-extension://02348f77-ece7-44f1-b75c-e9f1c0987e64/js/content/store.js:4112
    async* moz-extension://02348f77-ece7-44f1-b75c-e9f1c0987e64/js/content/store.js:4164
```

Firefox 79.0 Windows 64-bit, Augmented Steam v.1.4.7

**Comment by supakorn-ras** [comment]
Apparently clearing cache works for me
