### ISSUE TITLE
How is worth approximately on the steam badges page calculated?

### ISSUE THREAD

**Issue by superusercode** [tfedor/AugmentedSteam#919]
![image](https://user-images.githubusercontent.com/60588434/86058975-d5b72400-ba2f-11ea-93ef-f80b827208e2.png)
I got $32 as my estimate earlier but now that I've gotten down to $24 i've only yielded $2 from selling my cards.

**Comment by superusercode** [comment]
https://github.com/tfedor/AugmentedSteam/blob/develop/src/js/Content/Features/Community/Badges/FBadgeCompletionCost.js

Relevant bits of code seem to be here, in the dropworthavg part. I'm not totally sure of the parts it pulls from, but it seems to take the average cost of completing a badge and applies it indiscriminately to all cards of a set. So if a certain card costs more than others (seen in puyo puyo tetris), it won't be represented properly. Thus we get inflated worth approximately values if you have a game with inflated card values or outright no one buying cards.

![image](https://user-images.githubusercontent.com/60588434/103303470-0aeb0180-49d4-11eb-9659-5b94ffabf86e.png)
like right now I have half of the card drops as I did in summer yet the value is $10 more.

**Comment by MxtOUT** [comment]
Yes, it uses the average of all cards in a set and multiplies this value with the count of drops remaining.
While I think the server could provide the lowest price for each card for a more accurate representation of the worth, the client won't be able to find which cards are missing from the badge overview page.

**Comment by Revadike** [comment]
@MxtOUT close this maybe? Or turn this into feature request?

**Comment by MxtOUT** [comment]
I don't see a feasible way of improving the accuracy of the approximation.
Infeasible ways would be querying the badge page for each badge you have or try to work with the limited amount of cards that are visible from the badge overview page.
For those cards visible you would have the exact value, but for others you would still need to use the average.

Therefore I'm closing this issue
