### ISSUE TITLE
[Feature Request] Auto-clicking the Steam Subscriber Agreement box, Booster Pack creator shortcut on badge pages

### ISSUE THREAD

**Issue by jimbo4273** [tfedor/AugmentedSteam#920]
Let's face it, this box just gets in the way while trying to buy stuff on the Community Market... (At least, I feel it does)
I'd also like to be able to craft boosters while seeing what cards I'd need for a set. Maybe you could add a gem total next to the account's Wallet total?

**Comment by candela97** [comment]
The functionality for saving SSA checkbox states is already there, but the selector for buy orders needs to be updated:
https://github.com/tfedor/AugmentedSteam/blob/2e8cd0e68835331cdf00af481ea7c26c4c52676b/js/content/common.js#L1443
```js
        let nodes = document.querySelectorAll("#market_sell_dialog_accept_ssa,#market_buyorder_dialog_accept_ssa,#accept_ssa");
````

This should be labeled as a bug, so can you open a new issue detailing what you have in mind for the other feature? (Preferably with screenshots and /or mockups)

**Comment by MxtOUT** [comment]
@candela97 I'm trusting you on this one, I don't have any funds on my account currently
