### ISSUE TITLE
Make profile transparency effects optional

### ISSUE THREAD

**Issue by bottleblue** [tfedor/AugmentedSteam#921]
Can you make the transparency an option? It can be hard to see some of the text on the right hand side depending on what background someone uses.  Also some people might prefer the new color themes Steam just came out with.

**Comment by Revadike** [comment]
You mean disabling the custom themes for other profiles (yourself included)?

**Comment by bottleblue** [comment]
I assume that's what it is. I couldn't find any setting in the Option/Profile to turn off transparency. When I disable Augmented Steam addon the transparency effects go away.

**Comment by MxtOUT** [comment]
Hm, not sure if that's required.
If the user picks a custom background then he wants his profile to be presented in this way

**Comment by bottleblue** [comment]
I was mistaken about this. I thought the transparency was from the new update at the time. I forgot it's the "Clear theme" from the Custom Themes option.  

I'll just close this.
