### ISSUE TITLE
Unable to remove custom profile colour.

### ISSUE THREAD

**Issue by BuryTomorrow12** [tfedor/AugmentedSteam#922]
Hello. 

Back in the day, when this was Enhanced steam, there was a feature that allowed us to select a colour gradient for our profiles.

Now, with the new steam profiles, I can't find this option anywhere, and the colour palette overrides the golden profile, for example.

Is there any way to disable the colour gradients?

Pic showing purple-ish custom colour overriding golden profile.

![image](https://user-images.githubusercontent.com/40051760/86330795-926ed800-bc1e-11ea-8f2c-f1418f214430.png)

**Comment by Revadike** [comment]
This was already solved in the new version. Please update and check your profile options.

**Comment by BuryTomorrow12** [comment]
Already using 1.4.6 and I do not see this option - however, there was something regarding this in the patch notes.

Mind telling me the specific option that I should be looking for on my profile edit page, please? I might be overlooking it.

**Comment by Revadike** [comment]
Sure, go [here](https://steamcommunity.com/my/edit/theme) and change Custom Theme at the bottom.
![image](https://user-images.githubusercontent.com/4411977/86358336-9a0a9d00-bc6f-11ea-9c5c-4994726ac7d7.png)

**Comment by BuryTomorrow12** [comment]
Thank you, I see where the problem lies: The golden profile makes us unable to access the "Themes" section.

I was able to modify it by using your link straight to the Themes section, deactivating the purple background and then logging in as per Steam's request.

Closing!
