### ISSUE TITLE
Add "Hide SteamDB Online now, Peak today, All-time peak, and Followers data"

### ISSUE THREAD

**Issue by Korb** [tfedor/AugmentedSteam#926]
![View more information and charts on SteamDB](https://user-images.githubusercontent.com/3509797/86904654-b009d900-c119-11ea-81ae-0b52b729a08b.png)

**Comment by Revadike** [comment]
This is from the steamdb extension. Has nothing to do with augmented steam.

**Comment by Korb** [comment]
> This is from the steamdb extension.

Yes, it is "Steam Database" add-on, sorry.
