### ISSUE TITLE
Sync to ITAD fails with SyntaxError: Unexpected end of JSON input at wrappedSendMessageCallback

### ISSUE THREAD

**Issue by lainverse** [tfedor/AugmentedSteam#931]
Exact error message:
common.js:59 Error: SyntaxError: Unexpected end of JSON input
    at wrappedSendMessageCallback (browser-polyfill.js:1126)

**Comment by MxtOUT** [comment]
Does this happen all the time?

**Comment by lainverse** [comment]
It did happen all the time for at least a months for me. It works fine right now, though. So, probably the issue is gone now.
