### ISSUE TITLE
Add option to disable Performance Survey

### ISSUE THREAD

**Issue by DarthRaziel** [tfedor/AugmentedSteam#935]
It will be good if you'll add an option to disable or hide Performance Survey block
![Аннотация 2020-08-03 211127](https://user-images.githubusercontent.com/62831760/89213638-10335400-d5ce-11ea-862c-30756d75814d.jpg)

**Comment by masteratt** [comment]
See the linked PR #940 

Pretty clean change.

**Comment by MxtOUT** [comment]
This is already available if you click on the "Customize" button on any app page
![image](https://user-images.githubusercontent.com/14999077/90315212-f244e800-df19-11ea-843e-49886a8aca13.png)
