### ISSUE TITLE
[Suggestion] Black/Grey profile theme

### ISSUE THREAD

**Issue by skrrt** [tfedor/AugmentedSteam#94]
Since custom profile themes/colours have been added again, would it be possible to add a few extra colour palettes such as a black/grey colour theme? At the moment the clear theme doesn't exactly seem to look too good on certain monochrome profiles.

**Comment by tfedor** [comment]
If you send me CSS, no problem :)

**Comment by skrrt** [comment]
cool! here it is, i already took the blue theme and just made it grayscale, with CSS to match it. only thing missing is a preview.
[grey.zip](https://github.com/tfedor/AugmentedSteam/files/2942774/grey.zip)
