### ISSUE TITLE
QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by bluedasher13** [tfedor/AugmentedSteam#943]
While I edit the notes of apps, I got an error message  "QUOTA_BYTES_PER_ITEM quota exceeded" in the console.

It seems that [the quota of the extension is 5242880 bytes](https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot):
[https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot](https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot)

But I want to save more notes.

**Comment by MxtOUT** [comment]
Duplicate of #848
