### ISSUE TITLE
Lowest Price misleadingly shows a different store

### ISSUE THREAD

**Issue by ChrisG683** [tfedor/AugmentedSteam#947]
Kind of a nitpick, but I was looking at the current release of Untitled Goose Game and it shows the Epic Game Store as being the lowest price, when it's really the same price.

Shouldn't it just show nothing, or just the same store you're currently looking at?  (Steam)

No one wants to use that EGS trash anyways :P

![image](https://user-images.githubusercontent.com/7797815/94060116-039ad300-fda9-11ea-8828-dab3d0f1d423.png)

**Comment by MxtOUT** [comment]
> Shouldn't it just show nothing

That's basically wasted space then where you could just show another store with the same price.

> or just the same store you're currently looking at?

Same argument as above, you already have this information and you just have to compare two prices.
This pricing info should just give you a quick overview, if you want more elaborate information click on the "Current best" link

**Comment by Jacosci** [comment]
> 
> 
> > Shouldn't it just show nothing
> 
> That's basically wasted space then where you could just show another store with the same price.
> 
> > or just the same store you're currently looking at?
> 
> Same argument as above, you already have this information and you just have to compare two prices.
> This pricing info should just give you a quick overview, if you want more elaborate information click on the "Current best" link

But it's still misleading and confusing. Here's another example.
![image](https://user-images.githubusercontent.com/10607576/95690847-db362400-0c44-11eb-9a44-f7155dae7abc.png)
When did Book of Demons was priced $0.00 at Steam? Does it also show record from Free Weekend?
I've seen several other cases on other games but I always forgot to take a screenshot.
It's particularly frustrating when you want to know if the current discount is matches the historical low or not.

**Comment by MxtOUT** [comment]
This isn't the same problem though.
It's a problem with how the data is created and not how it's displayed.

**Comment by Jacosci** [comment]
> 
> 
> This isn't the same problem though.
> It's a problem with how the data is created and not how it's displayed.

I see. Should I open separated issue?

**Comment by MxtOUT** [comment]
I opened one #984
