### ISSUE TITLE
[BUG] Savings inflated 100-fold

### ISSUE THREAD

**Issue by myxal** [tfedor/AugmentedSteam#948]
On some games, the AS-injected info panel shows savings of thousands of €, usually with the assumed base price being 100-times the actual base price. Haven't investigated deeper, but my guess is this is a decimal separator mismatch, and some shop's `€39,99` is parsed for `.` and turned into `€3999`

My setup is probably not typical, with Chrome's preferred languages set to `English, English (US), Slovak, Czech`, while steam account country is Slovakia (which is what I assume causes the decimal comma; I also have Slovak style number format set in the OS, but I don't believe web pages or Chrome extensions have access to this setting).
![Screenshot 2020-10-05 at 12 54 33](https://user-images.githubusercontent.com/16622343/95074675-3c269f00-070f-11eb-9ba9-ce0af6611782.png)

**Comment by MxtOUT** [comment]
This is not Augmented Steam
