### ISSUE TITLE
Get currency from page instead of cookie

### ISSUE THREAD

**Issue by BrutuZ** [tfedor/AugmentedSteam#95]
If we get the currency from the page element `<meta itemprop="priceCurrency" content="USD">` instead of the `steamCountry` cookie, we get the wallet region, which is what the store currency will be when logged in from another region.

**Comment by KarlCastle** [comment]
That is what `Currency.getMemoizedCurrencyFromDom()` does, and is used for interpreting prices on the page.

`steamCountry` cookie is only used if there's no `?cc=` country code and you're logged out.

When you're logged in, the extension will try to read the current wallet currency from `https://store.steampowered.com/account/change_country/`

**Comment by BrutuZ** [comment]
It doesn't seem to be working for me then.
My wallet is in a different region, and auto-detect is using my local currency instead of the same as the store.

Or is my understanding of how this (auto-detect) should work just wrong?

**Comment by KarlCastle** [comment]
You're absolutely correct. PRs #104 and #106 are intended to fix the currency issues. Once the next version is released (0.9.4, hopefully this week) "auto-detect" should more reliably pick up the store currency.

**Comment by tfedor** [comment]
This should be done now, in case it isn't please reopen.
