### ISSUE TITLE
Opencritic review score on Steam page for Mount & Blade: Warband is for console edition

### ISSUE THREAD

**Issue by iamacatnotaperson** [tfedor/AugmentedSteam#957]
The console edition had much lower review scores than pc edition. This gives a false bad impression of the game.

**Comment by candela97** [comment]
Looks like this is the only version reviewed on OpenCritic though...
In any case, Augmented Steam displays the same info from [the ITAD site](https://isthereanydeal.com/#/page:game/info?plain=mountandbladewarband), so if you notice any problems in the future, I suggest posting in the ITAD Discord or Steam group for a faster response!
