### ISSUE TITLE
[BUG] Price Shown is not reflective of lowest price

### ISSUE THREAD

**Issue by jodyfarnden** [tfedor/AugmentedSteam#958]
I am getting results on some steam store pages that do not reflect the current lowest price.
Using [Digimon Cyber Sleuth](https://store.steampowered.com/app/1042550/Digimon_Story_Cyber_Sleuth_Complete_Edition/)  as an example - it is showing Gamersgate with a coupon code as the lowest price, 
![image](https://user-images.githubusercontent.com/38027671/99629621-3818cb80-2a88-11eb-85f7-dcb8337595cf.png)

but when i click "Current Best" the lowest price is actually Indie Gala:
![image](https://user-images.githubusercontent.com/38027671/99629679-51ba1300-2a88-11eb-9ecd-04058c9a06eb.png)

In addition, the link to gamersgate is being populated as: http://www.dpbolvw.net/click-6305441-10785951?URL=https%3A%2F%2Fwww.gamersgate.com%2FDD-DIGIMON-STORY-CYBER-SLEUTH-COMPLETE-EDITION%2Fdigimon-story-cyber-sleuth-complete-edition%3Fcaff%3D3964022
instead of the direct link to GamersGate, but the dpbolvw site is blocked by my spam filter.

Other exampels include
- [Ni no Kuni II](https://store.steampowered.com/app/589360/Ni_no_Kuni_II_Revenant_Kingdom/) - IndieGala Cheaper
- [Tales of Vesperia](https://store.steampowered.com/app/738540/Tales_of_Vesperia_Definitive_Edition/) - IndieGala Cheaper
- [Tales of Vesperia: Definitive Edition](https://store.steampowered.com/app/738540/Tales_of_Vesperia_Definitive_Edition/) - Steam Cheaper

I had thought maybe it was the conversion rate, but games where Steam, Amazon or Humble Bundle are listed as cheapest and there is no GamesGate price recorded seem to be showing the accurate prices.

### Specifications

  - Augmented Steam Version: 1.4.7
  - Browser Version : 87.0.4280.66 (Official Build) (64-bit)
  - Australian Currency specified

**Comment by MxtOUT** [comment]
Well, the difference between ITAD and AS here is that AS calculates the lowest price while considering all applicable coupons.

25.69 * (1 - 0.15) = 21.84

If you want to not include coupons in the price calculation, disable the option "Include coupon codes in price comparison" in settings.

The dpbolvw.net link is a referral link and only source of income for ITAD
