### ISSUE TITLE
[BUG] Nicknames not staying after blocking account

### ISSUE THREAD

**Issue by 11Thor11** [tfedor/AugmentedSteam#959]
### Expected Behavior
Nickname stays after blocking

### Actual Behavior
Nickname gets removed

### Steps to Reproduce the Problem

  1.  give nickname
  2.  Block the account

### Specifications

  - Augmented Steam Version: 1.4.7
  - Browser Version : Chrome Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by MxtOUT** [comment]
I can't reproduce this, it also shouldn't happen since the nickname feature actually is a feature of Steam itself.
Your assigned nicknames should be stored on their servers and be loaded for you
