### ISSUE TITLE
Add custom amount to Steam Wallet not working

### ISSUE THREAD

**Issue by gabkyo** [tfedor/AugmentedSteam#96]
Using Augmented Steam 0.9.3 on Firefox 65.0.1 on Windows 10 x64, regular window logged in. Upon setting custom amount on the add funds to wallet page and clicking the button, on the next page the amount is back to the initial default value of 10. Using Inspect Element(Q) on the button and changing in the Inspector the field data-amount then clicking the button does wield the desired value to show up next page.
![1](https://user-images.githubusercontent.com/34278677/53290936-00cd9b80-378a-11e9-8017-7e4054d297dc.PNG)
![2](https://user-images.githubusercontent.com/34278677/53290937-01663200-378a-11e9-8aa7-cd7b5c1659ef.PNG)

**Comment by MxtOUT** [comment]
I can't reproduce this.
Could you maybe set a breakpoint at [line 2036 in store.js](https://github.com/tfedor/Enhanced_Steam/blob/779d0954ae62ec64c4d1d03ed2e5c3516b5022cc/js/store.js#L2036) and report the value of `jsvalue`?
