### ISSUE TITLE
[FEATURE REQUEST] Is there way to Export Wishlist with the filters applied?

### ISSUE THREAD

**Issue by Tenome** [tfedor/AugmentedSteam#961]
### Current Behavior (if any)
Seems to copy the entire wishlist.
### Desired Behavior
I want to copy the Wishlist results after filtering it (on sale, exclude pre-prelease, under $5 for example)
### Motivation / Use Case for Changing the Behavior
Useful during sales, and in general just copy-pasting a filtered wishlist.

**Comment by Revadike** [comment]
I believe its supposed to do that, at least how I originally designed it. It has changed a lot since then.

**Comment by Revadike** [comment]
I tested this today with the `price` sort on, and the export didn't respect that. I tested other sorting settings too, but it is not respecting it.

Edit:
I see now that sorting hadn't even been discussed, just filtering was. My original code respected both filtering and sorting settings. At least, that how I remember it. I think that's how it should be. Should I make a new issue to add sorting support to exporting wishlist?

**Comment by Revadike** [comment]
While I'm at it, I think the wishlist stats should either update, when applying filters, or just get hidden. Because the wishlist will no longer show you all the wishlist items those stats was calculated on, making it potentially confusing.

**Comment by MxtOUT** [comment]
> While I'm at it, I think the wishlist stats should either update, when applying filters, or just get hidden. Because the wishlist will no longer show you all the wishlist items those stats was calculated on, making it potentially confusing.

It would be best if you open a new issue for that
