### ISSUE TITLE
Cannot  Remove old style.

### ISSUE THREAD

**Issue by zatone** [tfedor/AugmentedSteam#962]
Long time ago there was a way to add a custom profile style which makes your profile looks with snow. That option is removed, but if you have it enabled there is no way to turn it off. Automatically add a style to your profile page called holidayprofile.

Please helpme get rid of this. It has been bothering me for years.

Code injected:
<img width="659" alt="Injected profile code" src="https://user-images.githubusercontent.com/1188528/100517980-8fe0c200-316d-11eb-8c76-58170b99688e.png">

How it looks:
<img width="501" alt="Profile Holiday" src="https://user-images.githubusercontent.com/1188528/100517973-848d9680-316d-11eb-8706-97736baa387f.png">

**Comment by MxtOUT** [comment]
Hey, visit https://steamcommunity.com/my/edit/theme and scroll down to "Custom theme" where you should be able to remove it

**Comment by zatone** [comment]
Thank you so much, i feel like a major idiot!!
