### ISSUE TITLE
[BUG] Uncaught TypeError on store pages with no addition features

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#976]
### Expected Behavior
Extension should work with default features

### Actual Behavior
`Uncaught TypeError: Cannot read property 'DOMHelper' of undefined` reported in browser console

### Steps to Reproduce the Problem
Visit store pages with no addition features like https://store.steampowered.com/about/, https://store.steampowered.com/digitalgiftcards/, or with malformed urls like https://store.steampowered.com//

### Specifications

  - Augmented Steam Version: latest dev branch
  - Browser Version : Chrome 88 beta

**Comment by candela97** [comment]
uh, I guess this is due to malformed url

**Comment by MxtOUT** [comment]
Fixed by dfc270d939026a960f7efa71dd58fb53905d2569
