### ISSUE TITLE
[FEATURE REQUEST] Update our button styles to match Steam's

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#978]
### Current Behavior (if any)
![螢幕擷取畫面 2020-12-06 022625](https://user-images.githubusercontent.com/54083835/101284105-342cbf00-3793-11eb-815e-d3b7d5713799.jpg)

### Desired Behavior
Our custom bottons are still using the old style. We should update them to match the new look and feel of Steam's.
Looks like there're 3 new ones at the moment: `btn_green_steamui`, `btn_blue_steamui`, `btn_grey_steamui`
https://store.cloudflare.steamstatic.com/public/shared/css/buttons.css

**Comment by candela97** [comment]
Only dialog buttons and certain pages in the store section are using the new style at the moment. I've updated the button classes in related features for now, but we should keep this issue open to track future changes.

**Comment by MxtOUT** [comment]
I think it's better if we close it when all current styles have been updated, since the requested feature is implemented then.
If they add other pages with the new style, we can just open an issue for that
