### ISSUE TITLE
[BUG] "YouTube Gameplay"- & "YouTube Review"-tabs stopped containing videos

### ISSUE THREAD

**Issue by scharmach** [tfedor/AugmentedSteam#985]
### Expected Behavior

The expected behavior would be that you see gameplay- and review-videos from YouTube in the corresponding tabs.

### Actual Behavior

Videos aren't displayed at all, not even a container:

![grafik](https://user-images.githubusercontent.com/9080980/101948148-de707080-3bf1-11eb-96df-95ac22b99b70.png)

![grafik](https://user-images.githubusercontent.com/9080980/101948262-02cc4d00-3bf2-11eb-8c24-39e16f6ba750.png)

### Steps to Reproduce the Problem

  1. Got to any game page on Steam, e.g. https://store.steampowered.com/app/1091500/Cyberpunk_2077/
  2. Make sure the features are enabled and click on the "YouTube Gameplay"- & "YouTube Review"-tabs
  3. Problem can be seen as in screenshots above

There has also been at least some discussion about this here: https://github.com/tfedor/AugmentedSteam/issues/936

The problem as I can see it too is that YouTube-searches like these:

https://www.youtube.com/embed?listType=search&list=intitle%3A"Cyberpunk 2077 Gameplay" "PC" 

don't seem to work anymore. They only return a completely blank page.

### Specifications

  - Augmented Steam Version: 1.4.8
  - Browser Version : Firefox 83.0

**Comment by MxtOUT** [comment]
Yes, YouTube deprecated this type of embed player, we're working on a fix

**Comment by MxtOUT** [comment]
We're temporarily removing the YouTube video player functionality for the next version until we have worked out a server side solution

**Comment by deluxghost** [comment]
You shouldn't disable "Show Youtube link" option, it has nothing to do with embed player

**Comment by scharmach** [comment]
> 
> 
> You shouldn't disable "Show Youtube link" option, it has nothing to do with embed player

This is still there for me in the newly released version?!

**Comment by deluxghost** [comment]
> > You shouldn't disable "Show Youtube link" option, it has nothing to do with embed player
> 
> This has nothing to do with this option and it's still there and fully functional in the newly released version?!
> 
> ![grafik](https://user-images.githubusercontent.com/9080980/106508822-1f3b8600-64cd-11eb-87b4-f9b8f6991730.png)

Have you ever checked the option page before post this? You cannot toggle this feature anymore, but if it's enabled before the release, it will keep working.

https://github.com/tfedor/AugmentedSteam/blob/a7896cfd50ad25fbd93cba590837622b7d91d0b0/src/html/options.html#L207-L209

The 3rd option

**Comment by scharmach** [comment]
No, I haven't, because it's still displaying for me and I then wrongly assumed it's still displaying in general. Your comment before seemed out of context therefore, I guess posting the code earlier would have helped and I could have investigated this a little further.

I totally agree then, it makes no sense to disable this, since a) the feature is still working if enabled and b) it indeed has nothing to do with the embeds.

**Comment by MxtOUT** [comment]
You're right, I accidently disabled the links to YouTube too
