### ISSUE TITLE
[FEATURE REQUEST] Open in Steam Client

### ISSUE THREAD

**Issue by philraj** [tfedor/AugmentedSteam#993]
### Current Behavior (if any)
Missing "Open in Steam Client" button like Enhanced Steam had.

### Desired Behavior
Add a button that allows opening a game store page in the Steam client.

### Motivation / Use Case for Changing the Behavior
Would be cool to have the button, handy when the browser forgets my login session to open a game's store page in the Steam Client and be able to wishlist it, etc.

**Comment by Revadike** [comment]
I'm sorry, the maintainers declined this feature in the past, but perhaps they'll change their mind.
In case you're curious, this is how I implemented this feature, or tried to anyway:
https://github.com/tfedor/AugmentedSteam/pull/489
as well as https://github.com/tfedor/AugmentedSteam/pull/486

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/103142854-90885c00-470b-11eb-8533-b14cfc176b92.png)

**Comment by Revadike** [comment]
Seems broken actually

**Comment by philraj** [comment]
Beautiful, thank you.
