### ISSUE TITLE
[FEATURE REQUEST]  Improve display of achievement bars on "All Games" tab

### ISSUE THREAD

**Issue by candela97** [tfedor/AugmentedSteam#997]
### Current Behavior (if any)
https://steamcommunity.com/my/games/?tab=all
Steam has added achievement bars to the "All Games" tab, though a) it uses the blue theme and doesn't show completion percentage; b) it doesn't display for games with profile features limited.

### Desired Behavior
a) Stop fetching user stats for games that already have achievement bars
b) Update our styles to match Steam's
c) Calculate and display completion percentage?
d) Do the same for the "Perfect Games" tab, which only shows achievement bars for 10 most recent games by default? (https://steamcommunity.com/my/games/?tab=perfect)

### Motivation / Use Case for Changing the Behavior
Now we can improve upon Steam's implementation instead of fetching user stats for each game.

**Comment by MxtOUT** [comment]
Resolved by #1051
